// ═══════════════════════════════════════════════════
//  FITNESS CATEGORY — 18 Hobbies
//  Seed data for TrySomething v3
// ═══════════════════════════════════════════════════

export const fitnessHobbies = [
  {
    id: "bouldering",
    title: "Bouldering",
    hook: "Solve puzzles with your body.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=600&h=800&fit=crop",
    tags: ["physical", "social", "technical"],
    costText: "CHF 20-60/month",
    timeText: "3h/week",
    difficultyText: "Moderate",
    whyLove: "Every route is a unique puzzle that demands creative problem-solving with your whole body. The community is incredibly welcoming, and there's nothing like the rush of sending a problem you've been projecting for weeks. Progress is tangible and addictive.",
    difficultyExplain: "Strength builds quickly, but technique takes months. Start with easy grades (V0-V1) and let your tendons adapt before pushing hard.",
    pitfalls: [
      "Climbing too often too soon — tendons need weeks to strengthen, muscles recover in days",
      "Neglecting footwork and relying on upper body strength alone",
      "Comparing yourself to experienced climbers instead of tracking your own progress"
    ],
    sortOrder: 0,
  },
  {
    id: "yoga",
    title: "Yoga",
    hook: "Strength, flexibility, and calm in one practice.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&h=800&fit=crop",
    tags: ["physical", "meditative", "solo", "relaxing"],
    costText: "CHF 0-30",
    timeText: "3h/week",
    difficultyText: "Easy",
    whyLove: "Yoga meets you exactly where you are. It builds functional strength and flexibility while calming a busy mind. After a few weeks, you'll notice you stand taller, sleep better, and handle stress differently.",
    difficultyExplain: "Start with beginner Vinyasa or Hatha. Most poses have modifications. No flexibility required to begin.",
    pitfalls: [
      "Pushing into painful stretches instead of respecting your body's limits",
      "Skipping Savasana because it feels unproductive — it's where integration happens",
      "Trying advanced poses from Instagram before mastering foundations"
    ],
    sortOrder: 1,
  },
  {
    id: "swimming",
    title: "Swimming",
    hook: "The full-body workout that feels like freedom.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=600&h=800&fit=crop",
    tags: ["physical", "solo", "relaxing"],
    costText: "CHF 15-40/month",
    timeText: "3h/week",
    difficultyText: "Easy",
    whyLove: "Water supports your body while giving every muscle a workout. It's meditative — just you, your breath, and the rhythm of strokes. Swimming builds endurance without the joint stress of running, and Swiss lakes add a magical outdoor dimension.",
    difficultyExplain: "If you can float and do basic freestyle, you can start lap swimming. Technique improvements come steadily with practice.",
    pitfalls: [
      "Holding your breath instead of learning proper bilateral breathing",
      "Swimming the same pace every session — mix in intervals for faster progress",
      "Skipping warm-up laps and jumping straight into hard sets"
    ],
    sortOrder: 2,
  },
  {
    id: "martial-arts",
    title: "Martial Arts",
    hook: "Discipline your body, sharpen your mind.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=600&h=800&fit=crop",
    tags: ["physical", "social", "technical", "competitive"],
    costText: "CHF 80-150/month",
    timeText: "4h/week",
    difficultyText: "Moderate",
    whyLove: "Martial arts transform your relationship with your body and mind. You'll gain confidence, learn self-defense, and join a community built on mutual respect. The belt progression system gives constant motivation to keep showing up.",
    difficultyExplain: "The first month is the hardest — your body isn't used to the movements. After that, muscle memory kicks in and learning accelerates.",
    pitfalls: [
      "Choosing a style based on movies rather than trying introductory classes at several dojos",
      "Training through injuries instead of allowing proper recovery",
      "Focusing only on sparring and neglecting fundamental drills and forms"
    ],
    sortOrder: 3,
  },
  {
    id: "dance",
    title: "Dance",
    hook: "Move to the music, forget everything else.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=600&h=800&fit=crop",
    tags: ["physical", "social", "creative"],
    costText: "CHF 20-40/class",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove: "Dance is the workout that doesn't feel like exercise. Whether it's salsa, hip-hop, or contemporary, you'll build coordination, express yourself, and meet people. The social aspect makes it the most fun way to stay fit.",
    difficultyExplain: "Everyone feels awkward in their first class. By week three, basic rhythms click. No dance background needed — beginners are the majority in intro classes.",
    pitfalls: [
      "Staring at your feet instead of feeling the music and trusting your body",
      "Skipping social dance events where the real learning happens",
      "Getting discouraged when you can't nail choreography immediately — repetition is everything"
    ],
    sortOrder: 4,
  },
  {
    id: "crossfit",
    title: "CrossFit",
    hook: "Community-powered functional fitness.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&h=800&fit=crop",
    tags: ["physical", "social", "competitive"],
    costText: "CHF 150-220/month",
    timeText: "4h/week",
    difficultyText: "Hard",
    whyLove: "CrossFit combines weightlifting, gymnastics, and cardio into constantly varied workouts. The box community pushes you further than you'd go alone, and scaling means every workout fits your level. Tracking PRs makes progress undeniable.",
    difficultyExplain: "Start with the On-Ramp or Fundamentals course every box offers. Movements are complex but coaches break them down. Expect to be sore for the first two weeks.",
    pitfalls: [
      "Sacrificing form for speed during WODs — injury risk spikes with bad technique",
      "Skipping the fundamentals course to jump into regular classes",
      "Not scaling weights down enough as a beginner — ego is your enemy"
    ],
    sortOrder: 5,
  },
  {
    id: "boxing",
    title: "Boxing",
    hook: "Hit things. Feel amazing.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=600&h=800&fit=crop",
    tags: ["physical", "technical", "competitive"],
    costText: "CHF 60-120/month",
    timeText: "3h/week",
    difficultyText: "Moderate",
    whyLove: "Boxing is the ultimate stress release and full-body workout rolled into one. Learning combinations, footwork, and defense sharpens your mind while sculpting your body. You'll feel more confident after the first week.",
    difficultyExplain: "Jab-cross takes minutes to learn, months to master. Cardio is intense at first but adapts quickly. No sparring required if you prefer bag and pad work.",
    pitfalls: [
      "Throwing punches with just your arms instead of rotating your hips for power",
      "Neglecting defense drills — blocking and slipping are half the sport",
      "Wrapping hands improperly and risking wrist injuries"
    ],
    sortOrder: 6,
  },
  {
    id: "pilates",
    title: "Pilates",
    hook: "Build a body that moves without pain.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&h=800&fit=crop",
    tags: ["physical", "solo", "relaxing"],
    costText: "CHF 25-50/class",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove: "Pilates strengthens the deep stabilizer muscles most workouts miss. After a few sessions, back pain fades, posture improves, and everyday movements feel effortless. It's the workout that makes every other workout better.",
    difficultyExplain: "Gentle start with mat Pilates. Movements look easy but engaging the right muscles takes concentration. Reformer classes add variety once you grasp the basics.",
    pitfalls: [
      "Holding your breath during exercises instead of using the lateral breathing technique",
      "Rushing through movements — Pilates rewards slow, controlled precision",
      "Skipping the beginner foundations and jumping to advanced classes"
    ],
    sortOrder: 7,
  },
  {
    id: "cycling",
    title: "Cycling",
    hook: "Explore your city at the perfect speed.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "solo"],
    costText: "CHF 300-800",
    timeText: "4h/week",
    difficultyText: "Easy",
    whyLove: "Cycling lets you cover serious distance while being gentle on joints. Switzerland's cycling infrastructure is world-class, and every ride reveals new routes and views. It's transportation, fitness, and adventure wrapped into one.",
    difficultyExplain: "If you can ride a bike, you can start. Fitness builds within weeks. Learning to shift gears on hills and basic bike maintenance are the main skills to pick up.",
    pitfalls: [
      "Buying an expensive bike before confirming you enjoy regular riding",
      "Setting the saddle height wrong — knee pain is almost always a fit issue",
      "Ignoring weather gear for Swiss conditions and ending up miserable in rain"
    ],
    sortOrder: 8,
  },
  {
    id: "skateboarding",
    title: "Skateboarding",
    hook: "Four wheels and endless possibilities.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1564982752979-3f7bc974d29a?w=600&h=800&fit=crop",
    tags: ["physical", "creative", "outdoors"],
    costText: "CHF 80-200",
    timeText: "3h/week",
    difficultyText: "Moderate",
    whyLove: "Skateboarding is pure freedom — no rules, no teams, just you and concrete. Landing your first ollie delivers a rush that never gets old. The culture is creative, inclusive, and uniquely expressive.",
    difficultyExplain: "Balance and pushing take a few sessions. Your first trick (ollie) might take 2-4 weeks of practice. Expect falls — pads help.",
    pitfalls: [
      "Skipping protective gear because it 'looks uncool' — wrist guards save beginners constantly",
      "Practicing on rough surfaces instead of finding smooth pavement or a skatepark",
      "Trying kickflips before you can comfortably ride, turn, and stop"
    ],
    sortOrder: 9,
  },
  {
    id: "parkour",
    title: "Parkour",
    hook: "Turn the whole city into your playground.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1564769610726-59cead6a6f38?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "creative", "technical"],
    costText: "CHF 0-30",
    timeText: "3h/week",
    difficultyText: "Hard",
    whyLove: "Parkour changes how you see the world — every wall becomes a vault, every railing a balance challenge. It builds explosive strength, agility, and confidence. The progression from basic vaults to fluid movement is deeply satisfying.",
    difficultyExplain: "Start at a gym or with a coach, not on rooftops. Basic vaults and precision jumps come within weeks. Real flow takes months of consistent training.",
    pitfalls: [
      "Attempting big jumps or flips without mastering basic landings and rolls first",
      "Training alone without spotters when learning new movements",
      "Neglecting strength conditioning — parkour demands pulling, pushing, and core power"
    ],
    sortOrder: 10,
  },
  {
    id: "fencing",
    title: "Fencing",
    hook: "The physical chess match you didn't expect.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1515586838455-8f8f940d6853?w=600&h=800&fit=crop",
    tags: ["physical", "technical", "competitive", "social"],
    costText: "CHF 40-80/month",
    timeText: "3h/week",
    difficultyText: "Moderate",
    whyLove: "Fencing is strategy at sword-speed. Every bout is a conversation of feints, parries, and ripostes that demands both physical agility and tactical thinking. Swiss fencing clubs are welcoming, and the sport's elegance is unmatched.",
    difficultyExplain: "Basic stance and simple attacks are learned in the first class. Reading opponents and developing tactical depth takes a full season. Most clubs provide equipment for beginners.",
    pitfalls: [
      "Lunging with the arm instead of leading with the blade tip — form prevents shoulder injuries",
      "Choosing a weapon (foil/epee/sabre) before trying all three in introductory sessions",
      "Tensing up during bouts instead of staying relaxed for faster reactions"
    ],
    sortOrder: 11,
  },
  {
    id: "archery",
    title: "Archery",
    hook: "Find your calm, then release it.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1510925758641-869d353cecc7?w=600&h=800&fit=crop",
    tags: ["physical", "meditative", "solo", "technical"],
    costText: "CHF 30-60/month",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove: "Archery is meditation with a target. The ritual of nocking, drawing, aiming, and releasing demands total presence. Watching arrows group tighter week after week is quietly thrilling. Swiss clubs often have beautiful outdoor ranges.",
    difficultyExplain: "Hitting the target is easy from day one. Consistent grouping takes weeks of developing muscle memory. Proper form matters more than strength.",
    pitfalls: [
      "Gripping the bow too tightly — a relaxed hand produces better shots",
      "Using too heavy a draw weight as a beginner, leading to shaky aim and fatigue",
      "Anchoring inconsistently — the draw hand must touch the same face point every shot"
    ],
    sortOrder: 12,
  },
  {
    id: "rowing",
    title: "Rowing",
    hook: "Power, rhythm, and water at sunrise.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1543333995-a78aea2eee50?w=600&h=800&fit=crop",
    tags: ["physical", "social", "outdoors"],
    costText: "CHF 50-100/month",
    timeText: "4h/week",
    difficultyText: "Moderate",
    whyLove: "Rowing is the ultimate team sport that also works as solo training. It engages 86% of your muscles in one fluid stroke. Dawn sessions on Swiss lakes are transcendent, and the fitness gains are extraordinary.",
    difficultyExplain: "The stroke sequence (legs-back-arms) feels unnatural at first. An ergometer helps build the pattern before going on water. Expect 4-6 sessions to feel coordinated.",
    pitfalls: [
      "Pulling with your back first instead of driving with your legs — it's 60% legs",
      "Rushing the recovery (forward) phase instead of maintaining a controlled ratio",
      "Skipping ergometer training — it's essential for building stroke technique"
    ],
    sortOrder: 13,
  },
  {
    id: "jump-rope",
    title: "Jump Rope",
    hook: "The cheapest full-body cardio on Earth.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1434596922112-19b563067271?w=600&h=800&fit=crop",
    tags: ["physical", "solo", "competitive"],
    costText: "CHF 15-50",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove: "Ten minutes of jump rope equals 30 minutes of jogging, and you can do it anywhere. Once basic bouncing clicks, the trick vocabulary is endless — double-unders, crossovers, side swings. It's rhythmic, portable, and surprisingly creative.",
    difficultyExplain: "Basic bounce takes 2-3 sessions. Timing trips up most beginners but clicks quickly. Start with a beaded or PVC rope — too light ropes are harder to control.",
    pitfalls: [
      "Using too long or too short a rope — step on center, handles should reach your armpits",
      "Jumping too high — small, efficient bounces on balls of feet prevent shin splints",
      "Skipping rest intervals and burning out in the first five minutes"
    ],
    sortOrder: 14,
  },
  {
    id: "aerial-silks",
    title: "Aerial Silks",
    hook: "Defy gravity and look stunning doing it.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1596377554080-751080dcf1ff?w=600&h=800&fit=crop",
    tags: ["physical", "creative", "technical"],
    costText: "CHF 30-60/class",
    timeText: "2h/week",
    difficultyText: "Hard",
    whyLove: "Aerial silks merge art and athletics in the most dramatic way possible. Climbing, wrapping, and dropping through fabric builds incredible grip and core strength. The first time you hold a pose high above the ground, you'll feel invincible.",
    difficultyExplain: "Grip strength is the initial bottleneck — most beginners can't climb at first, and that's normal. Basic wraps and poses come within a month. Skin toughens with exposure.",
    pitfalls: [
      "Expecting to climb on day one — grip and pull-up strength need to develop first",
      "Wearing loose clothing that gets tangled in the fabric instead of fitted leggings and tops",
      "Skipping skin conditioning — fabric burns are part of the process, long sleeves help initially"
    ],
    sortOrder: 15,
  },
  {
    id: "ice-skating",
    title: "Ice Skating",
    hook: "Glide through winter like it's magic.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "creative"],
    costText: "CHF 10-25/session",
    timeText: "2h/week",
    difficultyText: "Moderate",
    whyLove: "Ice skating is pure elegance in motion. Gliding across ice activates deep stabilizer muscles and builds balance you can't get from any gym exercise. Switzerland's outdoor rinks and frozen lakes make it a seasonal treasure.",
    difficultyExplain: "Standing and gliding take one session. Stopping and turning confidently take 3-4 sessions. Crossovers and backward skating develop over a season.",
    pitfalls: [
      "Leaning backward when nervous — bend your knees and lean slightly forward for balance",
      "Renting skates that are too loose — a snug boot prevents ankle injuries",
      "Skipping gloves — your hands will touch ice when you fall, and you will fall"
    ],
    sortOrder: 16,
  },
  {
    id: "tai-chi",
    title: "Tai Chi",
    hook: "Moving meditation that builds hidden strength.",
    categoryId: "fitness",
    imageUrl: "https://images.unsplash.com/photo-1524863479829-916d8e77f67b?w=600&h=800&fit=crop",
    tags: ["physical", "meditative", "relaxing", "solo"],
    costText: "CHF 20-40/class",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove: "Tai Chi is deceptively powerful. The slow, flowing movements build deep leg strength, improve balance, and calm the nervous system. Studies show it reduces fall risk, lowers blood pressure, and improves sleep quality. It's fitness you can practice at any age.",
    difficultyExplain: "Movements are slow and gentle — the challenge is memorizing the form sequences and developing body awareness. No flexibility or strength prerequisites.",
    pitfalls: [
      "Rushing through movements instead of embracing the deliberate slowness",
      "Standing too upright — the slight knee bend is where the strength benefit comes from",
      "Practicing only in class and not doing the short daily form practice at home"
    ],
    sortOrder: 17,
  },
];

export const fitnessKitItems = [
  // Bouldering
  {
    hobbyId: "bouldering",
    name: "Climbing Shoes",
    description: "Rent first. Buy after 3-4 sessions once you know your size and fit preference.",
    cost: 95,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=climbing+shoes+bouldering&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "bouldering",
    name: "Chalk Bag & Chalk",
    description: "Keeps hands dry for better grip. Block chalk is cheapest, liquid chalk is least messy.",
    cost: 25,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1601224780065-43e743e1e06b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=climbing+chalk+bag&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "bouldering",
    name: "Bouldering Gym Membership",
    description: "Monthly pass at your local boulder hall. Most offer day passes (CHF 20-25) to try first.",
    cost: 55,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1564769625905-50e93615e769?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=bouldering+training+board&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "bouldering",
    name: "Finger Tape",
    description: "Protects skin during long sessions. Essential once you start climbing 3+ times a week.",
    cost: 8,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=climbing+finger+tape&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Yoga
  {
    hobbyId: "yoga",
    name: "Yoga Mat",
    description: "A non-slip mat with 5-6mm thickness. This is your main investment — get a good one.",
    cost: 45,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=yoga+mat+non+slip+6mm&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "yoga",
    name: "Yoga Blocks (Pair)",
    description: "Cork or foam blocks for support in poses. Essential for beginners who lack flexibility.",
    cost: 20,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=yoga+blocks+cork&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "yoga",
    name: "Yoga Strap",
    description: "Helps with stretches and binds you can't reach yet. Cotton with D-ring buckle works best.",
    cost: 12,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1575052814086-f385e2e2ad33?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=yoga+strap+cotton&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Swimming
  {
    hobbyId: "swimming",
    name: "Swim Goggles",
    description: "Anti-fog, UV-protected goggles. Try on for seal fit — leaking goggles ruin everything.",
    cost: 25,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=swim+goggles+anti+fog&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "swimming",
    name: "Swim Cap",
    description: "Silicone cap reduces drag and keeps hair manageable. Required at most Swiss pools.",
    cost: 10,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1560089000-7433a4ebbd64?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=silicone+swim+cap&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "swimming",
    name: "Kickboard",
    description: "Isolates leg technique and builds kick strength. Most pools have shared ones.",
    cost: 15,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1575429198097-0414ec08e8cd?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=swim+kickboard&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "swimming",
    name: "Pool Membership",
    description: "Monthly pass at your local Hallenbad. Day passes also available (CHF 8-12).",
    cost: 40,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=waterproof+swim+bag&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Martial Arts
  {
    hobbyId: "martial-arts",
    name: "Gi / Uniform",
    description: "Required for most traditional styles. Your dojo usually sells them or has specific requirements.",
    cost: 60,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=martial+arts+gi+uniform&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "martial-arts",
    name: "Mouth Guard",
    description: "Boil-and-bite style for sparring protection. Essential once you start partner drills.",
    cost: 15,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1615117972428-28de7dc60a3f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=mouth+guard+martial+arts&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "martial-arts",
    name: "Sparring Gloves",
    description: "Light gloves for controlled partner work. Your gym may provide these initially.",
    cost: 40,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1583473848882-f9a5bc1e151f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sparring+gloves+martial+arts&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Dance
  {
    hobbyId: "dance",
    name: "Dance Shoes",
    description: "Depends on style — jazz shoes, ballroom shoes, or clean indoor sneakers for hip-hop.",
    cost: 50,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=dance+shoes+jazz&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "dance",
    name: "Comfortable Activewear",
    description: "Stretchy, breathable clothing that lets you move freely. You probably own something suitable.",
    cost: 40,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1518459031867-a89b944bffe4?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=dance+activewear+women&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "dance",
    name: "Water Bottle",
    description: "Dance is surprisingly sweaty. A good insulated bottle keeps water cold through class.",
    cost: 20,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=insulated+water+bottle+sport&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // CrossFit
  {
    hobbyId: "crossfit",
    name: "Cross-Training Shoes",
    description: "Flat, stable sole for lifting with enough cushion for running. Nike Metcon or Reebok Nano.",
    cost: 130,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=crossfit+training+shoes&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "crossfit",
    name: "Wrist Wraps",
    description: "Stabilize wrists during overhead lifts and handstands. Essential for heavy days.",
    cost: 20,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=crossfit+wrist+wraps&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "crossfit",
    name: "Skipping Rope (Speed)",
    description: "Thin cable rope for double-unders. Get an adjustable length model.",
    cost: 25,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1434596922112-19b563067271?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=speed+rope+crossfit&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "crossfit",
    name: "Lifting Belt",
    description: "Supports your core during heavy squats and deadlifts. Not needed until you lift heavier loads.",
    cost: 55,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=weightlifting+belt&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Boxing
  {
    hobbyId: "boxing",
    name: "Boxing Gloves (12-16 oz)",
    description: "Heavier gloves protect both you and your partner. 14oz is standard for beginners.",
    cost: 60,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=boxing+gloves+14oz&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "boxing",
    name: "Hand Wraps (Pair)",
    description: "180-inch wraps protect knuckles and wrists. Mexican-style wraps offer the best support.",
    cost: 12,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1517438322307-e67111335449?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=boxing+hand+wraps+180&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "boxing",
    name: "Mouth Guard",
    description: "Boil-and-bite mouth guard for sparring. Needed once you advance past bag work.",
    cost: 15,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1615117972428-28de7dc60a3f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=boxing+mouth+guard&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Pilates
  {
    hobbyId: "pilates",
    name: "Pilates Mat (Extra Thick)",
    description: "Thicker than yoga mats (10-15mm) for spine comfort during roll-downs and supine work.",
    cost: 40,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pilates+mat+thick+15mm&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pilates",
    name: "Resistance Band Loop",
    description: "Adds challenge to leg and glute exercises. Get a set of 3 resistance levels.",
    cost: 15,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=resistance+bands+set+pilates&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pilates",
    name: "Pilates Ring (Magic Circle)",
    description: "Adds resistance to inner/outer thigh and arm exercises. Great for home practice.",
    cost: 20,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pilates+ring+magic+circle&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Cycling
  {
    hobbyId: "cycling",
    name: "Road or Hybrid Bike",
    description: "Start with a quality used bike. Test ride before buying. Proper frame size is crucial.",
    cost: 500,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=hybrid+bike&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "cycling",
    name: "Helmet",
    description: "Non-negotiable. MIPS technology offers better protection. Replace after any crash.",
    cost: 60,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1557803175-2f6e289e581f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cycling+helmet+MIPS&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "cycling",
    name: "Cycling Shorts (Padded)",
    description: "The chamois pad prevents saddle soreness. Trust everyone who says these are essential.",
    cost: 45,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=padded+cycling+shorts&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "cycling",
    name: "Bike Lights (Front & Rear)",
    description: "USB-rechargeable. Required by Swiss law for night riding. Visibility saves lives.",
    cost: 30,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=bike+lights+usb+rechargeable+set&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Skateboarding
  {
    hobbyId: "skateboarding",
    name: "Complete Skateboard",
    description: "Start with a pre-built complete (8.0-8.25 inch deck). Custom setups come later.",
    cost: 80,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1564982752979-3f7bc974d29a?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=complete+skateboard+8+inch&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "skateboarding",
    name: "Helmet",
    description: "Skate-certified helmet (CPSC or dual-certified). Protects during inevitable falls.",
    cost: 40,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1557803175-2f6e289e581f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=skate+helmet&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "skateboarding",
    name: "Wrist Guards & Knee Pads",
    description: "Wrist injuries are the most common beginner injury. Pads give confidence to try tricks.",
    cost: 35,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1555375771-14b2a78b8345?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=skateboard+protective+gear+set&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Parkour
  {
    hobbyId: "parkour",
    name: "Parkour Shoes",
    description: "Lightweight, flexible shoes with good grip. Feiyue or similar minimalist trainers work well.",
    cost: 50,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1564769610726-59cead6a6f38?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=parkour+shoes+lightweight&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "parkour",
    name: "Workout Gloves",
    description: "Protect palms during wall climbs and bar work. Fingerless for better grip control.",
    cost: 20,
    isOptional: true,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fingerless+workout+gloves&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "parkour",
    name: "Resistance Bands",
    description: "For warm-up and conditioning exercises. Essential for building the strength parkour demands.",
    cost: 18,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=resistance+bands+set+pull+up&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Fencing
  {
    hobbyId: "fencing",
    name: "Fencing Mask",
    description: "FIE-rated mask for safety. Most clubs loan equipment for beginners — ask first.",
    cost: 80,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1515586838455-8f8f940d6853?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fencing+mask+FIE&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "fencing",
    name: "Practice Foil",
    description: "Start with foil — it teaches right of way and point control. Electric comes later.",
    cost: 45,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fencing+foil+practice&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "fencing",
    name: "Fencing Glove",
    description: "Padded glove for your weapon hand. Essential for protection during drills and bouts.",
    cost: 25,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1590239926044-4131f5d0654d?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fencing+glove&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Archery
  {
    hobbyId: "archery",
    name: "Recurve Bow (Beginner)",
    description: "Start with a 20-25lb draw weight takedown recurve. Club bows are available to try first.",
    cost: 80,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1510925758641-869d353cecc7?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=recurve+bow+beginner+25lb&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "archery",
    name: "Arrows (6-pack)",
    description: "Carbon or aluminum arrows matched to your bow weight. Club arrows work for starting.",
    cost: 35,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1545406253-f3e09e205e1a?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=carbon+arrows+recurve+bow&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "archery",
    name: "Arm Guard",
    description: "Protects your forearm from string slap. Simple but essential for comfortable shooting.",
    cost: 12,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=archery+arm+guard&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "archery",
    name: "Finger Tab",
    description: "Leather tab protects your drawing fingers from the string. Gloves are an alternative.",
    cost: 10,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=archery+finger+tab+leather&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Rowing
  {
    hobbyId: "rowing",
    name: "Club Membership",
    description: "Includes boat access and coaching. Most Swiss rowing clubs offer beginner programs.",
    cost: 80,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1543333995-a78aea2eee50?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=rowing+gloves+fitness&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "rowing",
    name: "Rowing Gloves",
    description: "Prevent blisters during long sessions. Fingerless for better oar feel.",
    cost: 20,
    isOptional: true,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=rowing+gloves&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "rowing",
    name: "Performance Base Layer",
    description: "Moisture-wicking, form-fitting top. Loose clothing catches on oar handles.",
    cost: 35,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=compression+base+layer+sport&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Jump Rope
  {
    hobbyId: "jump-rope",
    name: "Adjustable Jump Rope",
    description: "PVC or beaded rope with adjustable length. Beaded ropes are best for beginners — easier to control.",
    cost: 15,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1434596922112-19b563067271?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=adjustable+jump+rope+beaded&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "jump-rope",
    name: "Cross-Training Shoes",
    description: "Cushioned forefoot for impact absorption. Running shoes work but cross-trainers are better.",
    cost: 80,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cross+training+shoes&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "jump-rope",
    name: "Exercise Mat",
    description: "Cushions your joints when jumping on hard surfaces. Any basic fitness mat works.",
    cost: 20,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=exercise+mat+thick&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Aerial Silks
  {
    hobbyId: "aerial-silks",
    name: "Aerial Class Package",
    description: "Studio classes with rigged silks and crash mats. Don't DIY this — safety first.",
    cost: 50,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1596377554080-751080dcf1ff?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=aerial+silks+fabric&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "aerial-silks",
    name: "Grip Strengthener",
    description: "Build hand and forearm strength for climbing. Train 3x/week for noticeable improvement.",
    cost: 15,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=grip+strengthener+hand&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "aerial-silks",
    name: "Full-Length Leggings",
    description: "Fitted, full coverage to protect skin from fabric burns. No shorts or capris.",
    cost: 35,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=high+waist+leggings+full+length&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Ice Skating
  {
    hobbyId: "ice-skating",
    name: "Ice Skates",
    description: "Rent first at the rink. Buy recreational figure skates once you commit — better ankle support.",
    cost: 90,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=ice+skates+recreational&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "ice-skating",
    name: "Thick Socks",
    description: "One pair of warm, moisture-wicking socks. Not two pairs — that reduces control.",
    cost: 12,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=ice+skating+socks+warm&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "ice-skating",
    name: "Waterproof Gloves",
    description: "Your hands will touch ice repeatedly. Waterproof, warm gloves are non-negotiable.",
    cost: 20,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1545170299-1c0de1bfed28?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=waterproof+gloves+winter&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Tai Chi
  {
    hobbyId: "tai-chi",
    name: "Tai Chi Shoes",
    description: "Flat, flexible shoes with thin soles for ground feel. Martial arts slippers work perfectly.",
    cost: 30,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1524863479829-916d8e77f67b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=tai+chi+shoes+flexible&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "tai-chi",
    name: "Loose Comfortable Clothing",
    description: "Traditional Tai Chi uniform or any loose, breathable pants and top. Cotton works best.",
    cost: 35,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=tai+chi+uniform+cotton&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "tai-chi",
    name: "Tai Chi Fan",
    description: "Traditional prop for fan form practice. Beautiful and functional. Optional for beginners.",
    cost: 20,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=tai+chi+fan+martial+arts&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
];

export const fitnessRoadmapSteps = [
  // Bouldering
  { id: "bouldering-1", hobbyId: "bouldering", title: "First Gym Visit", description: "Go to your local bouldering gym, rent shoes, and try easy routes (V0-V1). Focus on having fun, not sending hard problems.", estimatedMinutes: 90, milestone: null, sortOrder: 0 },
  { id: "bouldering-2", hobbyId: "bouldering", title: "Learn Basic Footwork", description: "Practice placing your feet precisely on footholds. Use your legs to push, not arms to pull. Watch experienced climbers for technique cues.", estimatedMinutes: 90, milestone: "First V0 Sent", sortOrder: 1 },
  { id: "bouldering-3", hobbyId: "bouldering", title: "Climb 3x per Week", description: "Build a regular schedule with rest days between sessions. Start tracking routes you complete. Try every V0-V1 in the gym.", estimatedMinutes: 90, milestone: null, sortOrder: 2 },
  { id: "bouldering-4", hobbyId: "bouldering", title: "Project a V2", description: "Pick a V2 problem and work it across multiple sessions. Learn to read sequences before climbing. Practice falling safely.", estimatedMinutes: 90, milestone: "First V2 Sent", sortOrder: 3 },
  { id: "bouldering-5", hobbyId: "bouldering", title: "Try Outdoor Bouldering", description: "Join a group for an outdoor bouldering session on real rock. Bring a crash pad or go with experienced climbers who have one.", estimatedMinutes: 180, milestone: "Outdoor Boulder", sortOrder: 4 },

  // Yoga
  { id: "yoga-1", hobbyId: "yoga", title: "First Class or Video", description: "Attend a beginner Hatha or Vinyasa class. Don't worry about flexibility — modifications exist for every pose. Focus on breathing.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "yoga-2", hobbyId: "yoga", title: "Learn Sun Salutations", description: "Practice Sun Salutation A and B until the sequence feels natural. This flow is the foundation of most yoga classes.", estimatedMinutes: 45, milestone: "Sun Salutation Flow", sortOrder: 1 },
  { id: "yoga-3", hobbyId: "yoga", title: "Build a Home Practice", description: "Do 15-20 minutes of yoga at home 3 mornings a week. Start with Sun Salutations and add standing poses you remember from class.", estimatedMinutes: 20, milestone: null, sortOrder: 2 },
  { id: "yoga-4", hobbyId: "yoga", title: "Hold Challenging Poses", description: "Work toward holding Warrior III, Crow Pose, or Headstand prep for 5 breaths. Use blocks and walls as support.", estimatedMinutes: 45, milestone: "First Arm Balance", sortOrder: 3 },
  { id: "yoga-5", hobbyId: "yoga", title: "Try a New Style", description: "Explore Yin, Ashtanga, or Hot Yoga to find what resonates. Each style offers different benefits and challenges.", estimatedMinutes: 75, milestone: null, sortOrder: 4 },

  // Swimming
  { id: "swimming-1", hobbyId: "swimming", title: "Swim 500m Continuously", description: "Go to your local pool and swim 500 meters using any stroke. Rest at the wall when needed. Just get comfortable in the water.", estimatedMinutes: 45, milestone: null, sortOrder: 0 },
  { id: "swimming-2", hobbyId: "swimming", title: "Fix Your Freestyle Breathing", description: "Learn bilateral breathing (both sides). Practice exhaling underwater and turning your head, not lifting it. This changes everything.", estimatedMinutes: 45, milestone: "Bilateral Breathing", sortOrder: 1 },
  { id: "swimming-3", hobbyId: "swimming", title: "Swim 1km Without Stopping", description: "Build endurance with 3 sessions per week. Mix freestyle with backstroke for variety. Time yourself for a baseline.", estimatedMinutes: 45, milestone: "1km Swim", sortOrder: 2 },
  { id: "swimming-4", hobbyId: "swimming", title: "Add Interval Training", description: "Swim sets like 10x50m with 15 seconds rest. This builds speed and cardiovascular fitness faster than steady laps.", estimatedMinutes: 50, milestone: null, sortOrder: 3 },
  { id: "swimming-5", hobbyId: "swimming", title: "Swim in Open Water", description: "Try a lake swim in summer. Wear a bright swim cap, bring a swim buoy, and go with a buddy. Swiss lakes are spectacular.", estimatedMinutes: 60, milestone: "Lake Swim", sortOrder: 4 },

  // Martial Arts
  { id: "martial-arts-1", hobbyId: "martial-arts", title: "Try 3 Different Styles", description: "Visit intro classes at a karate, judo, and kickboxing school. Most offer a free trial. Find the style that excites you.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "martial-arts-2", hobbyId: "martial-arts", title: "Commit to One Dojo", description: "Sign up for a beginner program. Learn the basic stance, blocks, and first strike combinations. Practice at home between classes.", estimatedMinutes: 60, milestone: "White Belt", sortOrder: 1 },
  { id: "martial-arts-3", hobbyId: "martial-arts", title: "Learn Your First Form", description: "Memorize the first kata/form of your style. Practice it until you can perform it without thinking about the next move.", estimatedMinutes: 60, milestone: "First Form", sortOrder: 2 },
  { id: "martial-arts-4", hobbyId: "martial-arts", title: "Start Light Sparring", description: "With coach supervision, begin controlled partner work. Focus on applying techniques rather than winning.", estimatedMinutes: 60, milestone: null, sortOrder: 3 },
  { id: "martial-arts-5", hobbyId: "martial-arts", title: "Grade for Next Belt", description: "Prepare for your first belt examination. Review all techniques, forms, and any required theory or terminology.", estimatedMinutes: 90, milestone: "Belt Promotion", sortOrder: 4 },

  // Dance
  { id: "dance-1", hobbyId: "dance", title: "Take a Beginner Class", description: "Pick a style (salsa, hip-hop, contemporary) and attend a beginner class. Everyone feels awkward the first time — just move.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "dance-2", hobbyId: "dance", title: "Learn Basic Steps", description: "Practice the fundamental steps of your chosen style at home. Play music and repeat until the rhythm feels natural.", estimatedMinutes: 30, milestone: "Basic Rhythm", sortOrder: 1 },
  { id: "dance-3", hobbyId: "dance", title: "Attend Weekly for a Month", description: "Commit to weekly classes for 4 weeks. You'll notice massive improvement in body awareness and confidence.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "dance-4", hobbyId: "dance", title: "Learn a Short Routine", description: "Learn and memorize a 1-minute choreography. Perform it confidently from memory. Record yourself to track progress.", estimatedMinutes: 60, milestone: "First Routine", sortOrder: 3 },
  { id: "dance-5", hobbyId: "dance", title: "Attend a Social Dance Event", description: "Go to a social (milonga, bachata night, dance jam). Dancing with different partners accelerates learning dramatically.", estimatedMinutes: 120, milestone: "Social Debut", sortOrder: 4 },

  // CrossFit
  { id: "crossfit-1", hobbyId: "crossfit", title: "Complete Fundamentals Course", description: "Every box offers an intro course (usually 3-6 sessions) teaching proper squat, deadlift, press, and Olympic lift technique.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "crossfit-2", hobbyId: "crossfit", title: "Do Your First WOD", description: "Join a regular class and complete the Workout of the Day fully scaled. Write down your score — you'll look back on this.", estimatedMinutes: 60, milestone: "First WOD", sortOrder: 1 },
  { id: "crossfit-3", hobbyId: "crossfit", title: "Attend 3x per Week for a Month", description: "Build consistency. Learn to read the whiteboard, understand scaling options, and find your pace during metcons.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "crossfit-4", hobbyId: "crossfit", title: "Hit a Strength PR", description: "Focus on one lift (back squat, deadlift, or clean) and track progression. Hit a personal record you're proud of.", estimatedMinutes: 60, milestone: "First PR", sortOrder: 3 },
  { id: "crossfit-5", hobbyId: "crossfit", title: "Try a Benchmark WOD", description: "Attempt a classic benchmark like Fran, Grace, or Cindy. These are community touchstones you'll re-test over time.", estimatedMinutes: 60, milestone: "Benchmark Complete", sortOrder: 4 },

  // Boxing
  { id: "boxing-1", hobbyId: "boxing", title: "First Bag Session", description: "Learn proper stance, jab, and cross from a coach. Practice wrapping your hands correctly. Hit the heavy bag for 3 rounds.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "boxing-2", hobbyId: "boxing", title: "Master the Basic Combos", description: "Drill jab-cross (1-2), jab-cross-hook (1-2-3), and jab-cross-hook-cross (1-2-3-2) until they flow automatically.", estimatedMinutes: 60, milestone: "Basic Combos", sortOrder: 1 },
  { id: "boxing-3", hobbyId: "boxing", title: "Add Defensive Techniques", description: "Learn slipping, bobbing, and basic blocking. Practice defensive drills with a partner or in front of a mirror.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "boxing-4", hobbyId: "boxing", title: "Do Pad Work with a Partner", description: "Hold pads for someone and have them hold for you. Pad work develops timing, accuracy, and combination flow.", estimatedMinutes: 60, milestone: "Pad Work Flow", sortOrder: 3 },
  { id: "boxing-5", hobbyId: "boxing", title: "Spar a Light Round", description: "With coach approval, do controlled technical sparring. Light contact only. Focus on applying what you've drilled.", estimatedMinutes: 60, milestone: "First Spar", sortOrder: 4 },

  // Pilates
  { id: "pilates-1", hobbyId: "pilates", title: "First Mat Class", description: "Attend a beginner mat Pilates class. Focus on learning the 'powerhouse' — the deep core engagement that drives every movement.", estimatedMinutes: 50, milestone: null, sortOrder: 0 },
  { id: "pilates-2", hobbyId: "pilates", title: "Master the Fundamentals", description: "Learn the Pilates Hundred, Roll-Up, Single Leg Stretch, and Bridge with proper form and breathing pattern.", estimatedMinutes: 50, milestone: "Core Connection", sortOrder: 1 },
  { id: "pilates-3", hobbyId: "pilates", title: "Build a Home Routine", description: "Practice a 20-minute flow at home 3x per week. Focus on slow, controlled movements with full breath cycles.", estimatedMinutes: 20, milestone: null, sortOrder: 2 },
  { id: "pilates-4", hobbyId: "pilates", title: "Try Reformer Pilates", description: "Take a reformer class to experience spring resistance. It adds new dimensions to familiar exercises.", estimatedMinutes: 50, milestone: "Reformer Session", sortOrder: 3 },
  { id: "pilates-5", hobbyId: "pilates", title: "Progress to Intermediate", description: "Attempt exercises like Teaser, Swan Dive, and Open Leg Rocker. Maintain control throughout the full range of motion.", estimatedMinutes: 50, milestone: "Intermediate Level", sortOrder: 4 },

  // Cycling
  { id: "cycling-1", hobbyId: "cycling", title: "Get Your Bike Fitted", description: "Adjust saddle height (slight bend at bottom of pedal stroke), handlebar position, and tire pressure. Fit prevents pain.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "cycling-2", hobbyId: "cycling", title: "Ride 20km", description: "Complete a 20km ride on a flat route. Practice shifting gears, signaling turns, and riding predictably in traffic.", estimatedMinutes: 75, milestone: "First 20km", sortOrder: 1 },
  { id: "cycling-3", hobbyId: "cycling", title: "Build to 3 Rides per Week", description: "Mix commutes and recreational rides. Track distance and time. Aim for 60-80km total per week.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "cycling-4", hobbyId: "cycling", title: "Tackle a Hill Climb", description: "Find a local climb and ride it. Use lower gears, maintain a steady cadence, and stay seated. Time it for a baseline.", estimatedMinutes: 90, milestone: "First Hill Climb", sortOrder: 3 },
  { id: "cycling-5", hobbyId: "cycling", title: "Complete a 50km Ride", description: "Plan a 50km route with a cafe stop. Bring snacks and water. This is a proper cycling milestone.", estimatedMinutes: 150, milestone: "50km Ride", sortOrder: 4 },

  // Skateboarding
  { id: "skateboarding-1", hobbyId: "skateboarding", title: "Stand and Push", description: "Find smooth pavement, stand on the board, and practice pushing. Determine your stance (regular or goofy). Just cruise.", estimatedMinutes: 45, milestone: null, sortOrder: 0 },
  { id: "skateboarding-2", hobbyId: "skateboarding", title: "Turn and Stop", description: "Learn to turn by leaning (carving) and stop using the tail drag or foot brake. Practice until stopping is instinctive.", estimatedMinutes: 45, milestone: "Confident Cruising", sortOrder: 1 },
  { id: "skateboarding-3", hobbyId: "skateboarding", title: "Visit a Skatepark", description: "Go to a local skatepark during off-peak hours. Ride around the flat areas, try small ramps, and observe others.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "skateboarding-4", hobbyId: "skateboarding", title: "Land Your First Ollie", description: "Practice the ollie on grass first, then move to pavement. Snap the tail, slide your front foot, and jump. This takes weeks.", estimatedMinutes: 45, milestone: "First Ollie", sortOrder: 3 },
  { id: "skateboarding-5", hobbyId: "skateboarding", title: "Learn a Second Trick", description: "Choose a kickturn, manual, or pop shove-it. Having two tricks opens up lines and builds confidence for progression.", estimatedMinutes: 60, milestone: "Second Trick", sortOrder: 4 },

  // Parkour
  { id: "parkour-1", hobbyId: "parkour", title: "Safety Roll & Landings", description: "Learn the parkour roll to absorb impact. Practice landing softly from increasing heights. This is your foundation.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "parkour-2", hobbyId: "parkour", title: "Basic Vaults", description: "Master the safety vault and speed vault on waist-height obstacles. Practice both sides. Smooth beats fast.", estimatedMinutes: 60, milestone: "First Vault", sortOrder: 1 },
  { id: "parkour-3", hobbyId: "parkour", title: "Precision Jumps", description: "Practice standing jumps to specific landing spots. Start close and increase distance. Accuracy matters more than distance.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "parkour-4", hobbyId: "parkour", title: "Wall Runs & Climb-Ups", description: "Learn to run at a wall, plant your foot, and pull yourself up. This combines power, timing, and upper body strength.", estimatedMinutes: 60, milestone: "Wall Climb-Up", sortOrder: 3 },
  { id: "parkour-5", hobbyId: "parkour", title: "Flow a Route", description: "Link 3-4 movements together into a flowing line. Film yourself and refine transitions. This is where parkour becomes art.", estimatedMinutes: 90, milestone: "First Flow Line", sortOrder: 4 },

  // Fencing
  { id: "fencing-1", hobbyId: "fencing", title: "Learn the Stance", description: "Master the en garde position: feet at right angles, knees bent, weapon arm extended. Practice advancing and retreating.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "fencing-2", hobbyId: "fencing", title: "Basic Attacks & Parries", description: "Learn the direct attack (thrust), parry 4 and parry 6. Practice the riposte — parry then immediately counter-attack.", estimatedMinutes: 60, milestone: "First Riposte", sortOrder: 1 },
  { id: "fencing-3", hobbyId: "fencing", title: "Footwork Drills", description: "Advance, retreat, lunge, and recover until footwork is automatic. Good fencers win with feet, not just blade.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "fencing-4", hobbyId: "fencing", title: "First Bout", description: "Fence a practice bout with scoring. Apply your attacks and defenses against a real opponent. Focus on distance management.", estimatedMinutes: 60, milestone: "First Bout", sortOrder: 3 },
  { id: "fencing-5", hobbyId: "fencing", title: "Enter a Club Tournament", description: "Compete in your club's internal competition. Winning isn't the goal — applying training under pressure is.", estimatedMinutes: 120, milestone: "Tournament Debut", sortOrder: 4 },

  // Archery
  { id: "archery-1", hobbyId: "archery", title: "Safety & First Shots", description: "Learn range safety rules, proper stance, and take your first shots at 10 meters. Focus on consistent anchor point.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "archery-2", hobbyId: "archery", title: "Develop Your Form", description: "Practice the shot sequence: stance, nock, draw, anchor, aim, release, follow-through. Consistency is everything.", estimatedMinutes: 60, milestone: "Consistent Anchor", sortOrder: 1 },
  { id: "archery-3", hobbyId: "archery", title: "Tighten Your Grouping", description: "Shoot 3-arrow ends and work on grouping them closer together. Move back to 18 meters once groupings are tight.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "archery-4", hobbyId: "archery", title: "Score a Round", description: "Shoot a scored round (e.g., 30 arrows at 18m on a 40cm target). Record your score as a baseline.", estimatedMinutes: 90, milestone: "First Scored Round", sortOrder: 3 },
  { id: "archery-5", hobbyId: "archery", title: "Shoot at 30 Meters", description: "Extend your range. Adjust your aim and build the back muscle endurance needed for longer distances.", estimatedMinutes: 90, milestone: "30m Grouping", sortOrder: 4 },

  // Rowing
  { id: "rowing-1", hobbyId: "rowing", title: "Learn on the Ergometer", description: "Master the stroke sequence on a rowing machine: legs drive first, then back opens, then arms pull. Reverse on recovery.", estimatedMinutes: 45, milestone: null, sortOrder: 0 },
  { id: "rowing-2", hobbyId: "rowing", title: "First Time on Water", description: "Row in a stable training boat or quad with experienced rowers. Focus on timing with crew, not power.", estimatedMinutes: 60, milestone: "First Water Row", sortOrder: 1 },
  { id: "rowing-3", hobbyId: "rowing", title: "Row 2000m on the Erg", description: "Complete a 2000m erg test at a sustainable pace. Record your split time — this is the universal rowing benchmark.", estimatedMinutes: 30, milestone: "2km Erg Time", sortOrder: 2 },
  { id: "rowing-4", hobbyId: "rowing", title: "Row a Full Lake Session", description: "Complete a 45-minute on-water session. Practice starts, turns, and maintaining steady stroke rate.", estimatedMinutes: 60, milestone: null, sortOrder: 3 },
  { id: "rowing-5", hobbyId: "rowing", title: "Join a Crew Race", description: "Participate in a club regatta or friendly race. Racing with a crew is the ultimate rowing experience.", estimatedMinutes: 120, milestone: "First Race", sortOrder: 4 },

  // Jump Rope
  { id: "jump-rope-1", hobbyId: "jump-rope", title: "30 Consecutive Jumps", description: "Size your rope correctly and practice basic bounce. Stay on the balls of your feet with small jumps. Count to 30.", estimatedMinutes: 15, milestone: null, sortOrder: 0 },
  { id: "jump-rope-2", hobbyId: "jump-rope", title: "3 Minutes Non-Stop", description: "Build up to jumping continuously for 3 minutes. Use a timer. Rest 1 minute and repeat for 3 rounds.", estimatedMinutes: 15, milestone: "3-Min Endurance", sortOrder: 1 },
  { id: "jump-rope-3", hobbyId: "jump-rope", title: "Learn Alternate Foot Step", description: "Jump from foot to foot like running in place. This is faster and less tiring than the basic bounce.", estimatedMinutes: 15, milestone: null, sortOrder: 2 },
  { id: "jump-rope-4", hobbyId: "jump-rope", title: "First Trick: Criss-Cross", description: "Cross your arms in front of your body and jump through the loop. Start slow and build speed.", estimatedMinutes: 20, milestone: "First Trick", sortOrder: 3 },
  { id: "jump-rope-5", hobbyId: "jump-rope", title: "Complete a 10-Minute Workout", description: "Combine basic bounce, alternate step, and criss-cross into a flowing 10-minute workout. You're officially a jump roper.", estimatedMinutes: 15, milestone: "10-Min Flow", sortOrder: 4 },

  // Aerial Silks
  { id: "aerial-silks-1", hobbyId: "aerial-silks", title: "First Class: Basic Wraps", description: "Learn to climb a few feet, wrap the silk around one foot, and stand in a basic foot lock. Build trust with the fabric.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "aerial-silks-2", hobbyId: "aerial-silks", title: "Climb to the Top", description: "Build enough grip and technique to climb the full length of the silks. This might take 3-4 weeks of classes.", estimatedMinutes: 60, milestone: "Full Climb", sortOrder: 1 },
  { id: "aerial-silks-3", hobbyId: "aerial-silks", title: "Hold 3 Basic Poses", description: "Learn and hold poses like the cross-back straddle, hip key, and angel. Practice transitions between them.", estimatedMinutes: 60, milestone: "Pose Trio", sortOrder: 2 },
  { id: "aerial-silks-4", hobbyId: "aerial-silks", title: "First Drop", description: "With coach spotting, perform a controlled drop (like a star drop). The rush of dropping and catching is unforgettable.", estimatedMinutes: 60, milestone: "First Drop", sortOrder: 3 },
  { id: "aerial-silks-5", hobbyId: "aerial-silks", title: "Perform a Short Sequence", description: "String together a climb, 3 poses, and a drop into a choreographed sequence set to music. Film it.", estimatedMinutes: 60, milestone: "First Sequence", sortOrder: 4 },

  // Ice Skating
  { id: "ice-skating-1", hobbyId: "ice-skating", title: "Stand and Glide", description: "Get on the ice, hold the wall, then push off and glide. Practice falling safely (bend knees, fall sideways). Wear gloves.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "ice-skating-2", hobbyId: "ice-skating", title: "Learn to Stop", description: "Master the snowplow stop (turn toes inward). Being able to stop confidently unlocks everything else.", estimatedMinutes: 60, milestone: "Safe Stop", sortOrder: 1 },
  { id: "ice-skating-3", hobbyId: "ice-skating", title: "Forward Skating & Turns", description: "Practice forward stroking, two-foot turns, and crossovers around corners. Skate without holding the wall.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "ice-skating-4", hobbyId: "ice-skating", title: "Skate Backward", description: "Learn backward swizzles and one-foot backward skating. This opens up figure skating and hockey skills.", estimatedMinutes: 60, milestone: "Backward Skating", sortOrder: 3 },
  { id: "ice-skating-5", hobbyId: "ice-skating", title: "Skate on a Frozen Lake", description: "When conditions allow, skate on a verified-safe Swiss lake. Bring a friend and hot chocolate. Pure winter magic.", estimatedMinutes: 90, milestone: "Lake Skating", sortOrder: 4 },

  // Tai Chi
  { id: "tai-chi-1", hobbyId: "tai-chi", title: "Learn the Basic Stance", description: "Master wuji standing: feet shoulder-width, knees soft, spine tall, weight centered. Hold for 2-5 minutes to build awareness.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "tai-chi-2", hobbyId: "tai-chi", title: "First 8 Movements", description: "Learn the opening movements of the Yang 24 form. Practice them slowly, connecting breath to movement.", estimatedMinutes: 45, milestone: "Opening Form", sortOrder: 1 },
  { id: "tai-chi-3", hobbyId: "tai-chi", title: "Daily 10-Minute Practice", description: "Practice your known movements every morning for 2 weeks. Consistency matters more than duration.", estimatedMinutes: 10, milestone: null, sortOrder: 2 },
  { id: "tai-chi-4", hobbyId: "tai-chi", title: "Complete the Short Form", description: "Learn all 24 movements of the Yang short form. Perform the complete sequence from memory.", estimatedMinutes: 45, milestone: "24-Form Complete", sortOrder: 3 },
  { id: "tai-chi-5", hobbyId: "tai-chi", title: "Practice Push Hands", description: "With a partner, practice the push hands exercise to feel and redirect incoming force. This is Tai Chi's martial application.", estimatedMinutes: 45, milestone: "Push Hands", sortOrder: 4 },
];

export const fitnessFaqItems = [
  // Bouldering
  { hobbyId: "bouldering", question: "Do I need to be strong to start bouldering?", answer: "Not at all. Beginners succeed more through technique and balance than raw strength. Your body adapts quickly — most people notice huge gains in the first month. Start on easy routes and the strength will come." },
  { hobbyId: "bouldering", question: "What's the difference between bouldering and rock climbing?", answer: "Bouldering is climbing short routes (4-5 meters) without ropes, over thick crash pads. Rock climbing uses ropes and harnesses on taller walls. Bouldering needs less gear, is more social, and is easier to start." },

  // Yoga
  { hobbyId: "yoga", question: "I'm not flexible at all — can I still do yoga?", answer: "Flexibility is a result of yoga, not a prerequisite. Every pose has modifications. If you can breathe, you can do yoga. The stiffest people often benefit the most." },
  { hobbyId: "yoga", question: "What style of yoga should a beginner try first?", answer: "Start with Hatha (slower, more holds) or beginner Vinyasa (flowing movement). Avoid Ashtanga or Hot Yoga until you know the basic poses. Look for classes labeled 'beginner' or 'level 1'." },

  // Swimming
  { hobbyId: "swimming", question: "How do I get faster at swimming?", answer: "Technique improvement beats fitness gains for beginners. Focus on streamlining, proper catch, and reducing drag. A few lessons from a coach can shave minutes off your pace. Drills matter more than distance." },
  { hobbyId: "swimming", question: "Is swimming enough exercise on its own?", answer: "Swimming is excellent cardiovascular exercise that builds lean muscle. For complete fitness, add some weight-bearing exercise since swimming is low-impact. But for heart health and overall fitness, swimming alone is outstanding." },

  // Martial Arts
  { hobbyId: "martial-arts", question: "Which martial art is best for self-defense?", answer: "Brazilian Jiu-Jitsu and Krav Maga are considered most practical for self-defense. But the best martial art is the one you'll actually train consistently. Any style builds awareness, confidence, and functional fitness." },
  { hobbyId: "martial-arts", question: "Am I too old to start martial arts?", answer: "Many people begin in their 30s, 40s, and beyond. A good dojo adapts training to your fitness level. Tai Chi and Aikido are especially welcoming to older beginners, but any style works with the right school." },
  { hobbyId: "martial-arts", question: "Do I have to spar?", answer: "Most schools don't require sparring for beginners. Many practitioners train for years focusing on forms, drills, and fitness. Talk to the instructor about your comfort level — good coaches respect boundaries." },

  // Dance
  { hobbyId: "dance", question: "I have no rhythm — can I learn to dance?", answer: "Rhythm is a skill, not a gift. Start by simply walking to music. Within a few classes, your body learns to find the beat naturally. Every great dancer was once a beginner who couldn't find the downbeat." },
  { hobbyId: "dance", question: "What dance style is easiest to start with?", answer: "Salsa and swing have structured lead-follow patterns that beginners pick up quickly. For solo dance, hip-hop fundamentals are accessible. Contemporary is great if you want expressive, less structured movement." },

  // CrossFit
  { hobbyId: "crossfit", question: "Is CrossFit dangerous?", answer: "Not when done properly. Quality boxes emphasize technique in fundamentals courses before heavy loads. Every workout scales to your ability. Injuries come from ego, not the methodology. Choose a box with certified coaches." },
  { hobbyId: "crossfit", question: "I'm completely out of shape — can I do CrossFit?", answer: "Absolutely. Every workout has scaled options. Your first sessions will be lighter and simpler. The community is incredibly supportive of beginners. Show up consistently and you'll see dramatic fitness changes within weeks." },

  // Boxing
  { hobbyId: "boxing", question: "Do I have to fight someone?", answer: "No. Many boxers never spar. You can train on bags, mitts, and shadow boxing for excellent fitness and technique. Sparring is optional and only happens when both you and your coach agree you're ready." },
  { hobbyId: "boxing", question: "Will boxing hurt my hands?", answer: "Not with proper hand wraps and gloves. Wrapping correctly supports your wrists and protects knuckles. Ask your coach to show you the first day — it's the most important skill before throwing any punch." },

  // Pilates
  { hobbyId: "pilates", question: "What's the difference between Pilates and yoga?", answer: "Pilates focuses on core stability and controlled, repetitive movements. Yoga emphasizes flexibility, balance, and mindfulness through held poses. Pilates is more structured; yoga is more fluid. Many people do both." },
  { hobbyId: "pilates", question: "Mat Pilates vs. Reformer — which should I start with?", answer: "Start with mat Pilates to learn the fundamental principles and exercises. Mat work requires no equipment and builds body awareness. Move to reformer after 4-6 mat sessions for added variety and resistance." },
];

export const fitnessCostBreakdowns = [
  { hobbyId: "bouldering", starter: 80, threeMonth: 245, oneYear: 820, tips: ["Rent shoes for the first month (CHF 5/visit)", "Buy a 10-visit punch card before committing to a monthly pass", "Chalk lasts months — a single block is CHF 5"] },
  { hobbyId: "yoga", starter: 77, threeMonth: 120, oneYear: 200, tips: ["Free YouTube classes (Yoga With Adriene) are excellent for beginners", "Community classes at studios are often pay-what-you-can", "A good mat lasts 3-5 years — it's worth investing upfront"] },
  { hobbyId: "swimming", starter: 90, threeMonth: 170, oneYear: 530, tips: ["Annual pool passes save 20-30% over monthly", "Goggles last 6-12 months with proper care (rinse after each swim)", "Swiss lake swimming in summer is completely free"] },
  { hobbyId: "martial-arts", starter: 175, threeMonth: 415, oneYear: 1300, tips: ["Many dojos offer the first month at a discount or free trial week", "Buy your gi through the school — they often get wholesale pricing", "Grading fees are typically CHF 30-60 per test"] },
  { hobbyId: "dance", starter: 110, threeMonth: 290, oneYear: 1000, tips: ["Many studios offer unlimited monthly passes for CHF 80-120", "Social dance events are often CHF 10-15 including a beginner lesson", "YouTube tutorials supplement but don't replace class instruction"] },
  { hobbyId: "crossfit", starter: 175, threeMonth: 625, oneYear: 2200, tips: ["Most boxes offer a free trial class — use it before committing", "Buy shoes first, wraps second — skip other gear until needed", "Off-peak memberships can save CHF 30-50/month"] },
  { hobbyId: "boxing", starter: 87, threeMonth: 275, oneYear: 900, tips: ["Gyms usually provide gloves for beginners — buy your own for hygiene once committed", "Hand wraps are cheap — buy 3 pairs and rotate to keep them fresh", "Group classes are much cheaper than 1-on-1 coaching"] },
  { hobbyId: "pilates", starter: 75, threeMonth: 325, oneYear: 1200, tips: ["Online platforms like Pilates Anytime offer CHF 20/month unlimited classes", "Mat classes are significantly cheaper than reformer sessions", "A home mat practice 3x/week reduces studio class frequency needed"] },
  { hobbyId: "cycling", starter: 635, threeMonth: 680, oneYear: 800, tips: ["Buy a quality used bike — depreciation on new bikes is steep", "Learn basic maintenance (tire change, chain lube) to avoid shop costs", "Cycling to work replaces transport costs — it can pay for itself"] },
  { hobbyId: "skateboarding", starter: 155, threeMonth: 175, oneYear: 250, tips: ["Complete skateboards are cheaper and fine for learning", "Skateparks are free — no membership needed", "Shoes wear out fastest — budget for a new pair every 2-3 months of heavy use"] },
  { hobbyId: "parkour", starter: 88, threeMonth: 150, oneYear: 350, tips: ["Parkour is nearly free — the city is your gym", "Indoor gym sessions help during bad weather (CHF 15-25/session)", "Bodyweight exercises at home build the strength parkour requires"] },
  { hobbyId: "fencing", starter: 150, threeMonth: 270, oneYear: 700, tips: ["Most clubs lend all equipment to beginners for the first term", "Buy your own glove first — shared gloves are the least hygienic item", "Club membership fees usually include coaching and open practice time"] },
  { hobbyId: "archery", starter: 137, threeMonth: 220, oneYear: 480, tips: ["Club bows and arrows are included in most beginner courses", "Carbon arrows are pricier but last much longer than aluminum", "Join a club rather than buying equipment first — access to range is essential"] },
  { hobbyId: "rowing", starter: 135, threeMonth: 295, oneYear: 1060, tips: ["Club membership includes boat access — no need to buy a boat", "Indoor rowing at a regular gym is a cheap way to build technique", "Summer rowing camps offer intensive learning at good value"] },
  { hobbyId: "jump-rope", starter: 115, threeMonth: 120, oneYear: 135, tips: ["One good rope lasts years — this is the cheapest cardio hobby", "Jump anywhere with a flat surface — no gym membership needed", "Free YouTube tutorials cover every trick and workout structure"] },
  { hobbyId: "aerial-silks", starter: 100, threeMonth: 310, oneYear: 1100, tips: ["Never rig silks at home without professional installation — studio classes are the safe path", "Class packages (10-packs) are cheaper per session than drop-ins", "Grip strengtheners at home accelerate your climbing progress between classes"] },
  { hobbyId: "ice-skating", starter: 122, threeMonth: 200, oneYear: 500, tips: ["Rent skates for the first few sessions (CHF 8-10/visit)", "Outdoor rinks are cheaper than indoor — and more atmospheric", "Blade sharpening every 20-30 hours of skating keeps edges performing well"] },
  { hobbyId: "tai-chi", starter: 85, threeMonth: 185, oneYear: 600, tips: ["Many parks host free Tai Chi groups — check your local community board", "YouTube has complete Yang 24-form tutorials for home practice", "Tai Chi shoes are optional — any flat, flexible shoe works to start"] },
];
