// =============================================================================
//  Food Category — 18 Hobbies Seed Data
//  Sourdough, Fermentation, Coffee Roasting, Pasta Making, Sushi, Smoking/BBQ,
//  Bread Baking, Cocktails, Cheese Making, Chocolate, Pickling, Hot Sauce,
//  Korean Cooking, Indian Curry, Pizza, Pastry, Tea Ceremony, Kombucha
// =============================================================================

export const foodHobbies = [
  {
    id: "sourdough",
    title: "Sourdough Baking",
    hook: "Flour, water, patience. Insanely rewarding.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=600&h=800&fit=crop",
    tags: ["creative", "relaxing", "home-based", "slow"],
    costText: "CHF 15-50",
    timeText: "3h/week",
    difficultyText: "Moderate",
    whyLove:
      "There's nothing like pulling a crackly, golden loaf from the oven that you made with just flour and water. The daily ritual of feeding your starter becomes meditative, and the smell of fresh sourdough filling your kitchen is genuinely addictive.",
    difficultyExplain:
      "Getting a starter going takes about a week of daily feeding. After that, the baking itself is forgiving once you learn to read the dough.",
    pitfalls: [
      "Killing your starter by forgetting to feed it for too long",
      "Under-proofing the dough because you're impatient",
      "Using a dull blade for scoring, which tears instead of cuts",
    ],
    sortOrder: 0,
  },
  {
    id: "fermentation",
    title: "Fermentation",
    hook: "Turn cabbage into kimchi. Basically kitchen alchemy.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&h=800&fit=crop",
    tags: ["science", "healthy", "home-based", "creative"],
    costText: "CHF 20-60",
    timeText: "1h/week",
    difficultyText: "Easy",
    whyLove:
      "Fermentation is living science on your countertop. You watch salt and time transform ordinary vegetables into tangy, probiotic-rich foods. The flavour complexity you can achieve with just a jar and patience is extraordinary.",
    difficultyExplain:
      "Most ferments are extremely forgiving. Salt, clean jars, and a bit of patience are all you need to start. The bacteria do the hard work.",
    pitfalls: [
      "Not using enough salt, leading to mould instead of fermentation",
      "Opening jars too often and disrupting the anaerobic environment",
      "Fermenting near direct sunlight or heat sources",
    ],
    sortOrder: 1,
  },
  {
    id: "coffee-roasting",
    title: "Coffee Roasting",
    hook: "Roast your own beans. Morning coffee, transformed.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1447933601403-56dc2df6e3f5?w=600&h=800&fit=crop",
    tags: ["craft", "aromatic", "home-based", "morning-routine"],
    costText: "CHF 40-150",
    timeText: "1h/week",
    difficultyText: "Moderate",
    whyLove:
      "Once you taste coffee roasted hours ago instead of months ago, there's no going back. You control the roast profile, bringing out fruity, chocolatey, or nutty notes. It transforms your morning ritual into something deeply personal.",
    difficultyExplain:
      "You can start with a simple popcorn popper or pan, but learning to hit consistent roast levels takes practice. Listening for first and second crack becomes second nature.",
    pitfalls: [
      "Roasting indoors without proper ventilation (it's very smoky)",
      "Not letting beans degas for 12-24 hours before brewing",
      "Buying stale green beans from unreliable suppliers",
    ],
    sortOrder: 2,
  },
  {
    id: "pasta-making",
    title: "Pasta Making",
    hook: "Eggs, flour, rolling pin. Restaurant-quality at home.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=600&h=800&fit=crop",
    tags: ["creative", "social", "hands-on", "italian"],
    costText: "CHF 20-80",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove:
      "Handmade pasta has a texture and flavour that no store-bought brand can match. Rolling and cutting dough is deeply satisfying, and feeding people fresh tagliatelle or ravioli makes you feel like an Italian grandmother.",
    difficultyExplain:
      "Basic egg pasta is just flour and eggs. The technique is simple to learn but takes a few batches to master the right thickness and drying time.",
    pitfalls: [
      "Adding too much flour, making the dough dry and tough",
      "Rolling pasta too thick so it's chewy instead of silky",
      "Not salting the cooking water generously enough",
    ],
    sortOrder: 3,
  },
  {
    id: "sushi",
    title: "Sushi Making",
    hook: "Master the roll. Impress literally everyone.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&h=800&fit=crop",
    tags: ["precision", "social", "japanese", "creative"],
    costText: "CHF 40-100",
    timeText: "2h/week",
    difficultyText: "Moderate",
    whyLove:
      "Sushi making is where precision meets artistry. The satisfaction of producing a tight, beautiful maki roll or a glossy piece of nigiri at home is unmatched. Plus, sushi nights become legendary dinner parties.",
    difficultyExplain:
      "Seasoning rice properly is the real skill. Rolling takes a few tries to get tight. Nigiri and sashimi require sharper knife skills but basic rolls are very approachable.",
    pitfalls: [
      "Using regular rice instead of proper sushi rice",
      "Overfilling rolls so they burst when cutting",
      "Skipping the rice vinegar seasoning step",
    ],
    sortOrder: 4,
  },
  {
    id: "smoking-bbq",
    title: "Smoking & BBQ",
    hook: "Low, slow, smoky. Weekend ritual perfected.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=800&fit=crop",
    tags: ["outdoor", "social", "patience", "weekend"],
    costText: "CHF 80-300",
    timeText: "4h/week",
    difficultyText: "Moderate",
    whyLove:
      "There's a primal satisfaction in tending a fire for hours and producing fall-off-the-bone meat with a perfect smoke ring. BBQ turns cooking into an event, drawing friends and neighbours with irresistible aromas.",
    difficultyExplain:
      "Temperature control is the main skill. Start with a kettle grill and indirect heat. Once you can hold a steady 110 C for a few hours, you're ready for brisket.",
    pitfalls: [
      "Opening the lid too often and losing heat and smoke",
      "Not using a meat thermometer and guessing doneness",
      "Choosing the wrong wood chips for the protein",
    ],
    sortOrder: 5,
  },
  {
    id: "bread-baking",
    title: "Bread Baking",
    hook: "Warm loaves, zero preservatives. Pure comfort.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&h=800&fit=crop",
    tags: ["comforting", "home-based", "creative", "family"],
    costText: "CHF 15-50",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove:
      "Bread baking fills your home with warmth, both literally and figuratively. From simple sandwich loaves to crusty boules, each bake teaches you something new. Sharing homemade bread is one of life's simplest pleasures.",
    difficultyExplain:
      "Basic yeast bread is extremely forgiving. Mix, knead, wait, bake. Even imperfect loaves taste amazing fresh from the oven.",
    pitfalls: [
      "Killing yeast with water that's too hot",
      "Not kneading long enough, resulting in dense bread",
      "Slicing into the loaf before it has cooled and letting steam escape",
    ],
    sortOrder: 6,
  },
  {
    id: "cocktails",
    title: "Cocktail Crafting",
    hook: "Shake, stir, pour. Be your own bartender.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&h=800&fit=crop",
    tags: ["social", "creative", "evening", "classy"],
    costText: "CHF 60-200",
    timeText: "2h/week",
    difficultyText: "Moderate",
    whyLove:
      "Mixing cocktails is equal parts chemistry and showmanship. Mastering a handful of classic recipes lets you host memorable evenings, and the creative possibilities with syrups, bitters, and garnishes are endless.",
    difficultyExplain:
      "Start with five classic cocktails and proper technique (shaking, stirring, straining). Balancing sweet, sour, and spirit takes practice but the feedback loop is immediate and delicious.",
    pitfalls: [
      "Using cheap mixers that overpower good spirits",
      "Skipping fresh citrus in favour of bottled juice",
      "Over-diluting drinks by shaking too long with ice",
    ],
    sortOrder: 7,
  },
  {
    id: "cheese-making",
    title: "Cheese Making",
    hook: "Milk becomes mozzarella in thirty minutes flat.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&h=800&fit=crop",
    tags: ["science", "hands-on", "home-based", "rewarding"],
    costText: "CHF 30-80",
    timeText: "2h/week",
    difficultyText: "Moderate",
    whyLove:
      "Watching liquid milk transform into stretchy mozzarella or creamy ricotta feels like magic every single time. Cheese making connects you to one of humanity's oldest food traditions, and homemade cheese tastes incomparably fresh.",
    difficultyExplain:
      "Fresh cheeses like ricotta and mozzarella are weekend-afternoon easy. Aged cheeses require temperature-controlled environments and months of patience.",
    pitfalls: [
      "Using ultra-pasteurised milk, which won't form proper curds",
      "Not maintaining precise temperatures during curd formation",
      "Squeezing curds too hard and losing moisture for soft cheeses",
    ],
    sortOrder: 8,
  },
  {
    id: "chocolate",
    title: "Chocolate Making",
    hook: "Bean to bar. Edible art you actually eat.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=600&h=800&fit=crop",
    tags: ["creative", "precision", "gift-worthy", "indulgent"],
    costText: "CHF 40-120",
    timeText: "2h/week",
    difficultyText: "Hard",
    whyLove:
      "Crafting chocolate from cacao nibs to a polished bar is one of the most rewarding food hobbies. The tempering process is mesmerising, and the truffles and bonbons you produce make extraordinary gifts.",
    difficultyExplain:
      "Tempering chocolate requires precise temperature control and practice. Start with simple truffles before attempting moulded bars. Bean-to-bar is an advanced progression.",
    pitfalls: [
      "Getting even a drop of water in melted chocolate, causing it to seize",
      "Not tempering properly so chocolate blooms with white streaks",
      "Overheating chocolate in the microwave instead of using a double boiler",
    ],
    sortOrder: 9,
  },
  {
    id: "pickling",
    title: "Pickling",
    hook: "Preserve the harvest. Jars of crunchy goodness.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1534483509719-8b078da3e3da?w=600&h=800&fit=crop",
    tags: ["preserving", "seasonal", "home-based", "practical"],
    costText: "CHF 15-40",
    timeText: "1h/week",
    difficultyText: "Easy",
    whyLove:
      "Pickling turns seasonal abundance into year-round pantry treasures. The satisfying pop of a vacuum-sealed lid, the rainbow of jars on your shelf, and the crunch of a perfectly pickled cucumber are deeply gratifying.",
    difficultyExplain:
      "Quick refrigerator pickles are nearly foolproof. Water-bath canning for shelf stability requires following tested recipes exactly, but the process is straightforward.",
    pitfalls: [
      "Not sterilising jars properly, risking spoilage",
      "Using table salt instead of pickling salt, which can cloud brine",
      "Packing jars too tightly so brine can't circulate",
    ],
    sortOrder: 10,
  },
  {
    id: "hot-sauce",
    title: "Hot Sauce Making",
    hook: "Grow peppers, blend heat. Your signature sauce.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600&h=800&fit=crop",
    tags: ["spicy", "creative", "home-based", "gift-worthy"],
    costText: "CHF 20-50",
    timeText: "1h/week",
    difficultyText: "Easy",
    whyLove:
      "Creating your own hot sauce lets you dial in exactly the heat, tang, and flavour you want. From smoky chipotle to fruity habanero, every batch is unique. Bottling your own sauce with a custom label makes you feel like a proper artisan.",
    difficultyExplain:
      "Blend peppers with vinegar and salt, simmer, bottle. That's genuinely it for a basic sauce. Fermented hot sauces add complexity but just need a few extra days.",
    pitfalls: [
      "Not wearing gloves when handling hot peppers and touching your eyes",
      "Blending without ventilation and getting capsaicin steam in your lungs",
      "Not adding enough vinegar for proper preservation",
    ],
    sortOrder: 11,
  },
  {
    id: "korean-cooking",
    title: "Korean Cooking",
    hook: "Bibimbap to bulgogi. Bold, balanced, beautiful.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=600&h=800&fit=crop",
    tags: ["cultural", "flavourful", "social", "home-based"],
    costText: "CHF 30-80",
    timeText: "3h/week",
    difficultyText: "Moderate",
    whyLove:
      "Korean cuisine is an explosion of textures and flavours: spicy, sweet, sour, umami, crunchy, and silky all in one meal. Mastering the banchan (side dishes) transforms your table into a colourful feast that feels celebratory every time.",
    difficultyExplain:
      "Many Korean dishes are surprisingly simple once you stock a few key ingredients like gochugaru, doenjang, and sesame oil. Kimchi is the gateway and gets easier each batch.",
    pitfalls: [
      "Substituting gochugaru with generic chilli flakes and losing the flavour",
      "Not letting bibimbap rice form a crispy bottom layer",
      "Skipping the marination time for bulgogi",
    ],
    sortOrder: 12,
  },
  {
    id: "indian-curry",
    title: "Indian Curry",
    hook: "Spice blending mastery. Your kitchen, your rules.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=800&fit=crop",
    tags: ["spicy", "aromatic", "cultural", "home-based"],
    costText: "CHF 25-60",
    timeText: "2h/week",
    difficultyText: "Moderate",
    whyLove:
      "Indian curry is the art of layering spices to build depth. Once you learn to bloom cumin, toast coriander, and balance turmeric with heat, you unlock hundreds of regional dishes. The aromas alone are worth the effort.",
    difficultyExplain:
      "Start with a basic dal or butter chicken. The key technique is blooming whole spices in oil before adding other ingredients. Most curries follow a predictable template.",
    pitfalls: [
      "Burning spices by using heat that's too high during tempering",
      "Using pre-ground spices that have lost their potency",
      "Not cooking onions down enough before adding tomatoes",
    ],
    sortOrder: 13,
  },
  {
    id: "pizza",
    title: "Pizza Making",
    hook: "Crispy, bubbly, yours. Better than delivery.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&h=800&fit=crop",
    tags: ["social", "family", "creative", "italian"],
    costText: "CHF 25-120",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove:
      "Homemade pizza is the ultimate crowd-pleaser. Mastering a good dough gives you the foundation for endless creativity, from classic Margherita to wild experiments. Pizza night becomes the highlight of the week.",
    difficultyExplain:
      "A basic dough is just flour, water, yeast, and salt. The real skill is stretching it thin and managing oven heat. A pizza steel or stone makes a massive difference.",
    pitfalls: [
      "Overloading toppings so the centre gets soggy",
      "Not preheating your oven and stone long enough",
      "Using cold dough straight from the fridge without letting it warm up",
    ],
    sortOrder: 14,
  },
  {
    id: "pastry",
    title: "Pastry & Baking",
    hook: "Croissants, tarts, eclairs. Flour power unleashed.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1483695028939-5bb13f8648b0?w=600&h=800&fit=crop",
    tags: ["precision", "creative", "impressive", "gift-worthy"],
    costText: "CHF 30-100",
    timeText: "3h/week",
    difficultyText: "Hard",
    whyLove:
      "Pastry is where baking becomes art. The flaky layers of a homemade croissant, the crack of a perfect creme brulee, the geometry of a fruit tart. Every piece you produce looks and tastes like it came from a patisserie.",
    difficultyExplain:
      "Pastry demands precision with temperatures, measurements, and timing. Start with tart dough and simple cream fillings before attempting laminated doughs like croissants.",
    pitfalls: [
      "Using warm butter in pastry dough, ruining the flaky layers",
      "Overworking dough and developing too much gluten",
      "Not chilling pastry between steps as recipes instruct",
    ],
    sortOrder: 15,
  },
  {
    id: "tea-ceremony",
    title: "Tea Ceremony",
    hook: "Mindful brewing. Every cup tells a story.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&h=800&fit=crop",
    tags: ["mindful", "cultural", "relaxing", "daily-ritual"],
    costText: "CHF 30-150",
    timeText: "1h/week",
    difficultyText: "Easy",
    whyLove:
      "A tea ceremony slows you down in the best way. Learning about different tea types, proper water temperatures, and steeping times turns a simple drink into a meditative practice. The ritual becomes a daily anchor of calm.",
    difficultyExplain:
      "Brewing good tea is immediately accessible. Understanding the nuances of different teas and ceremony traditions deepens over time but the basics are simple.",
    pitfalls: [
      "Using boiling water for green or white tea, which scalds the leaves",
      "Steeping too long and extracting bitter tannins",
      "Storing tea near strong odours, which it readily absorbs",
    ],
    sortOrder: 16,
  },
  {
    id: "kombucha",
    title: "Kombucha Brewing",
    hook: "Fizzy, tangy, probiotic. Brew your own SCOBY.",
    categoryId: "food",
    imageUrl: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=600&h=800&fit=crop",
    tags: ["science", "healthy", "home-based", "fermented"],
    costText: "CHF 20-50",
    timeText: "1h/week",
    difficultyText: "Easy",
    whyLove:
      "Kombucha brewing is the gateway to home fermentation. Watching a SCOBY grow, flavouring your second ferment with fruit and ginger, and cracking open a naturally fizzy bottle you made yourself is immensely satisfying.",
    difficultyExplain:
      "Make sweet tea, add a SCOBY, wait a week, bottle with flavourings. The process is simple and the SCOBY is very resilient. Second fermentation adds carbonation naturally.",
    pitfalls: [
      "Using antibacterial soap on equipment, which kills the SCOBY culture",
      "Not burping bottles during second ferment, risking explosions",
      "Fermenting too long in warm weather and ending up with vinegar",
    ],
    sortOrder: 17,
  },
];

// =============================================================================
//  Kit Items — 3-5 per hobby (CHF pricing, Amazon.de affiliate links)
// =============================================================================

export const foodKitItems = [
  // --- Sourdough (4 items) ---
  {
    hobbyId: "sourdough",
    name: "Bread flour (1.5 kg)",
    description: "High-protein flour for strong gluten development and open crumb.",
    cost: 5,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=bread+flour+1.5kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "sourdough",
    name: "Banneton proofing basket",
    description: "Rattan basket that shapes dough and creates beautiful flour patterns.",
    cost: 18,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=banneton+proofing+basket&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "sourdough",
    name: "Bread lame scoring tool",
    description: "Razor-sharp blade for clean scoring patterns on your loaf.",
    cost: 12,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1549931319-a545753467c8?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=bread+lame+scoring+tool&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "sourdough",
    name: "Dutch oven (3.5 L)",
    description: "Cast iron pot that traps steam for a crispy, crackly crust.",
    cost: 45,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=dutch+oven+cast+iron+3.5L&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Fermentation (4 items) ---
  {
    hobbyId: "fermentation",
    name: "Wide-mouth mason jars (1 L, 4-pack)",
    description: "Ideal size for sauerkraut, kimchi, and pickled vegetables.",
    cost: 15,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=wide+mouth+mason+jars+1L&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "fermentation",
    name: "Fermentation weights (glass)",
    description: "Keeps vegetables submerged below the brine to prevent mould.",
    cost: 12,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fermentation+glass+weights&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "fermentation",
    name: "Fermentation lids with airlock",
    description: "One-way valve lids that release CO2 without letting air in.",
    cost: 14,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1595981234058-a9302fb97229?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fermentation+lids+airlock&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "fermentation",
    name: "Sea salt (coarse, 1 kg)",
    description: "Unrefined salt without iodine or anti-caking agents for clean ferments.",
    cost: 6,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1518110925495-5fe2c8f2be85?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=coarse+sea+salt+1kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Coffee Roasting (4 items) ---
  {
    hobbyId: "coffee-roasting",
    name: "Green coffee beans (1 kg, single origin)",
    description: "Unroasted specialty-grade beans, the raw ingredient for your roasts.",
    cost: 18,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefda?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=green+coffee+beans+1kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "coffee-roasting",
    name: "Stovetop popcorn popper (for roasting)",
    description: "Affordable first roaster with hand crank for even heat distribution.",
    cost: 35,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=stovetop+popcorn+popper+coffee+roasting&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "coffee-roasting",
    name: "Digital kitchen thermometer",
    description: "Monitor bean temperature to hit your target roast profile.",
    cost: 15,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=digital+kitchen+thermometer&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "coffee-roasting",
    name: "Airtight storage canister with CO2 valve",
    description: "Lets freshly roasted beans degas without letting air in.",
    cost: 20,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=coffee+storage+canister+CO2+valve&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Pasta Making (4 items) ---
  {
    hobbyId: "pasta-making",
    name: "Pasta machine (manual, stainless steel)",
    description: "Adjustable rollers for consistent, thin sheets of pasta dough.",
    cost: 40,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pasta+machine+manual+stainless+steel&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pasta-making",
    name: "Semolina flour (1 kg)",
    description: "Coarse durum wheat flour for shaping and preventing sticking.",
    cost: 5,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=semolina+flour+1kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pasta-making",
    name: "Pasta drying rack",
    description: "Wooden rack for drying fresh pasta before cooking or storing.",
    cost: 18,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1622973536968-3ead9e780960?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pasta+drying+rack+wood&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pasta-making",
    name: "Ravioli mould tray",
    description: "Aluminium mould for making 12 perfectly shaped ravioli at once.",
    cost: 15,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1587131782738-de30ea91a542?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=ravioli+mould+tray&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Sushi (5 items) ---
  {
    hobbyId: "sushi",
    name: "Sushi rice (2 kg)",
    description: "Short-grain Japanese rice that becomes sticky when cooked.",
    cost: 10,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1536304993881-460e2c0f1e4b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sushi+rice+2kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "sushi",
    name: "Bamboo rolling mat",
    description: "Essential tool for rolling tight, even maki rolls.",
    cost: 6,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=bamboo+sushi+rolling+mat&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "sushi",
    name: "Nori seaweed sheets (50 pack)",
    description: "Toasted nori sheets for wrapping maki and temaki rolls.",
    cost: 12,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=nori+seaweed+sheets+50&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "sushi",
    name: "Rice vinegar (500 ml)",
    description: "For seasoning sushi rice with the classic sweet-tangy flavour.",
    cost: 6,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=rice+vinegar+500ml&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "sushi",
    name: "Sharp sushi knife (yanagiba)",
    description: "Long, thin blade for clean cuts through rolls and fish.",
    cost: 45,
    isOptional: true,
    sortOrder: 4,
    imageUrl: "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sushi+knife+yanagiba&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Smoking/BBQ (4 items) ---
  {
    hobbyId: "smoking-bbq",
    name: "Kettle grill (47 cm)",
    description: "Versatile charcoal grill for both direct and indirect cooking.",
    cost: 120,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=kettle+grill+47cm+charcoal&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "smoking-bbq",
    name: "Digital meat thermometer (dual probe)",
    description: "Monitors both meat and grill temperature simultaneously.",
    cost: 35,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=digital+meat+thermometer+dual+probe&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "smoking-bbq",
    name: "Smoking wood chips (hickory + apple, 2 kg)",
    description: "Two classic wood flavours for poultry, pork, and beef.",
    cost: 14,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1558030006-450675393462?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=smoking+wood+chips+hickory+apple&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "smoking-bbq",
    name: "Heat-resistant BBQ gloves",
    description: "Silicone-lined gloves for handling hot grates and pulling meat.",
    cost: 20,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=heat+resistant+BBQ+gloves&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Bread Baking (3 items) ---
  {
    hobbyId: "bread-baking",
    name: "Digital kitchen scale",
    description: "Accurate to 1 g for consistent, repeatable bread recipes.",
    cost: 18,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=digital+kitchen+scale+bread+baking&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "bread-baking",
    name: "Instant yeast (500 g)",
    description: "Reliable active yeast that mixes directly into flour.",
    cost: 7,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=instant+yeast+500g&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "bread-baking",
    name: "Loaf tin (non-stick, 1 kg)",
    description: "Standard tin for sandwich loaves and enriched breads.",
    cost: 14,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1549931319-a545753467c8?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=loaf+tin+non+stick+1kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Cocktails (5 items) ---
  {
    hobbyId: "cocktails",
    name: "Cocktail shaker set (stainless steel)",
    description: "Boston shaker with strainer, jigger, and bar spoon.",
    cost: 30,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cocktail+shaker+set+stainless+steel&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "cocktails",
    name: "Jigger (double-sided, 25/50 ml)",
    description: "Precision measuring for balanced cocktail ratios.",
    cost: 10,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cocktail+jigger+25+50ml&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "cocktails",
    name: "Angostura bitters (200 ml)",
    description: "Essential cocktail ingredient for Old Fashioneds and Manhattans.",
    cost: 12,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1582056615449-3a8e744ed618?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=angostura+bitters+200ml&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "cocktails",
    name: "Citrus press (manual)",
    description: "Fresh lemon and lime juice is non-negotiable for great cocktails.",
    cost: 15,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1587015566802-6cc2b7e50837?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=citrus+press+manual+lemon&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "cocktails",
    name: "Muddler (wooden)",
    description: "For crushing herbs and fruit in mojitos and smashes.",
    cost: 8,
    isOptional: true,
    sortOrder: 4,
    imageUrl: "https://images.unsplash.com/photo-1560512823-829485b8bf24?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cocktail+muddler+wooden&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Cheese Making (4 items) ---
  {
    hobbyId: "cheese-making",
    name: "Cheese making kit (beginner)",
    description: "Includes rennet, citric acid, thermometer, and cheesecloth.",
    cost: 30,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cheese+making+kit+beginner&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "cheese-making",
    name: "Cheesecloth (muslin, 2 m)",
    description: "Fine weave cloth for draining whey from curds.",
    cost: 8,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cheesecloth+muslin+2m&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "cheese-making",
    name: "Dairy thermometer",
    description: "Precise temperature readings for curd formation (30-40 C range).",
    cost: 12,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=dairy+thermometer&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "cheese-making",
    name: "Cheese mould with press",
    description: "For making hard cheeses like cheddar and gouda.",
    cost: 25,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cheese+mould+press&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Chocolate (4 items) ---
  {
    hobbyId: "chocolate",
    name: "Couverture chocolate (dark, 1 kg)",
    description: "High cocoa-butter chocolate for smooth tempering and moulding.",
    cost: 20,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=couverture+chocolate+dark+1kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "chocolate",
    name: "Chocolate thermometer",
    description: "Essential for hitting precise tempering curves (27-32 C).",
    cost: 15,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=chocolate+thermometer&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "chocolate",
    name: "Polycarbonate chocolate moulds",
    description: "Professional moulds for glossy, perfectly shaped bonbons.",
    cost: 22,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=polycarbonate+chocolate+moulds&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "chocolate",
    name: "Double boiler pot",
    description: "Gentle, even heat for melting chocolate without scorching.",
    cost: 25,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1587132137056-bfbf0166836e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=double+boiler+pot+chocolate&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Pickling (3 items) ---
  {
    hobbyId: "pickling",
    name: "Canning jars with lids (500 ml, 6-pack)",
    description: "Heat-safe jars for water-bath canning and refrigerator pickles.",
    cost: 14,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1534483509719-8b078da3e3da?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=canning+jars+500ml+6+pack&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pickling",
    name: "Pickling salt (1 kg)",
    description: "Pure salt without iodine or additives that cloud brine.",
    cost: 5,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1518110925495-5fe2c8f2be85?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pickling+salt+1kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pickling",
    name: "White wine vinegar (1 L)",
    description: "Clean, mild acidity perfect for most pickling recipes.",
    cost: 6,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=white+wine+vinegar+1L&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Hot Sauce (3 items) ---
  {
    hobbyId: "hot-sauce",
    name: "Hot pepper seed variety pack",
    description: "Grow habanero, jalapeno, and cayenne from seed.",
    cost: 10,
    isOptional: true,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=hot+pepper+seed+variety+pack&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "hot-sauce",
    name: "Immersion blender",
    description: "Blends cooked peppers into smooth sauce directly in the pot.",
    cost: 25,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=immersion+blender&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "hot-sauce",
    name: "Swing-top glass bottles (150 ml, 6-pack)",
    description: "Reusable bottles for storing and gifting your hot sauce.",
    cost: 14,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=swing+top+glass+bottles+150ml&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Korean Cooking (4 items) ---
  {
    hobbyId: "korean-cooking",
    name: "Gochugaru (Korean red pepper flakes, 500 g)",
    description: "Smoky, fruity chilli flakes essential for kimchi and stews.",
    cost: 12,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=gochugaru+korean+red+pepper+flakes+500g&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "korean-cooking",
    name: "Gochujang paste (500 g)",
    description: "Fermented red chilli paste used in bibimbap, tteokbokki, and marinades.",
    cost: 8,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1583224964978-2257b960c3d3?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=gochujang+paste+500g&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "korean-cooking",
    name: "Doenjang (Korean soybean paste, 500 g)",
    description: "Deep umami base for soups, stews, and dipping sauces.",
    cost: 8,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1607301405390-d831c242f59b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=doenjang+korean+soybean+paste&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "korean-cooking",
    name: "Korean stone bowl (dolsot)",
    description: "Heats to sizzling for authentic bibimbap with crispy rice.",
    cost: 30,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=korean+stone+bowl+dolsot&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Indian Curry (4 items) ---
  {
    hobbyId: "indian-curry",
    name: "Whole spice starter set (10 spices)",
    description: "Cumin, coriander, turmeric, cardamom, cloves, and more.",
    cost: 22,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=indian+whole+spice+set+10&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "indian-curry",
    name: "Spice grinder (electric)",
    description: "Grinds whole spices fresh for maximum flavour and aroma.",
    cost: 25,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=electric+spice+grinder&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "indian-curry",
    name: "Stainless steel masala dabba (spice box)",
    description: "Traditional round box with 7 compartments for daily-use spices.",
    cost: 18,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=masala+dabba+stainless+steel&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "indian-curry",
    name: "Basmati rice (2 kg)",
    description: "Long-grain aromatic rice, the perfect accompaniment to any curry.",
    cost: 8,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1536304993881-460e2c0f1e4b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=basmati+rice+2kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Pizza (4 items) ---
  {
    hobbyId: "pizza",
    name: "Pizza stone (38 cm, cordierite)",
    description: "Absorbs moisture and delivers crispy, evenly baked crust.",
    cost: 35,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pizza+stone+38cm+cordierite&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pizza",
    name: "Pizza peel (wooden)",
    description: "Slides pizza on and off the hot stone without sticking.",
    cost: 18,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pizza+peel+wooden&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pizza",
    name: "Tipo 00 flour (1 kg)",
    description: "Fine Italian flour for authentic Neapolitan-style pizza dough.",
    cost: 6,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=tipo+00+flour+1kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pizza",
    name: "San Marzano tinned tomatoes (6-pack)",
    description: "Sweet, low-acid Italian tomatoes for the perfect pizza sauce.",
    cost: 18,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1597289124948-688c1a35cb48?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=san+marzano+tomatoes+6+pack&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Pastry (4 items) ---
  {
    hobbyId: "pastry",
    name: "Digital kitchen scale (0.1 g precision)",
    description: "Pastry demands exact measurements for consistent results.",
    cost: 25,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=precision+kitchen+scale+0.1g&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pastry",
    name: "Rolling pin (French, tapered)",
    description: "Tapered design gives better control for thin, even pastry sheets.",
    cost: 15,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1483695028939-5bb13f8648b0?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=french+tapered+rolling+pin&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pastry",
    name: "Tart tins with removable base (set of 4)",
    description: "Non-stick tins for clean unmoulding of quiches and fruit tarts.",
    cost: 20,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1587132137056-bfbf0166836e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=tart+tins+removable+base+set&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pastry",
    name: "Piping bag set with tips",
    description: "For decorating eclairs, choux, and cream-topped desserts.",
    cost: 14,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=piping+bag+set+tips&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Tea Ceremony (4 items) ---
  {
    hobbyId: "tea-ceremony",
    name: "Cast iron teapot (tetsubin, 0.8 L)",
    description: "Retains heat beautifully and adds a subtle mineral quality.",
    cost: 40,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cast+iron+teapot+tetsubin+0.8L&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "tea-ceremony",
    name: "Loose-leaf tea sampler (6 varieties)",
    description: "Green, oolong, black, white, pu-erh, and herbal to explore.",
    cost: 25,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=loose+leaf+tea+sampler+6+varieties&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "tea-ceremony",
    name: "Gaiwan (porcelain, 150 ml)",
    description: "Traditional Chinese lidded bowl for gongfu-style brewing.",
    cost: 18,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=gaiwan+porcelain+150ml&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "tea-ceremony",
    name: "Variable temperature kettle",
    description: "Preset temperatures for different tea types (70-100 C).",
    cost: 45,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=variable+temperature+kettle+tea&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Kombucha (4 items) ---
  {
    hobbyId: "kombucha",
    name: "SCOBY starter with liquid",
    description: "Live symbiotic culture of bacteria and yeast to begin brewing.",
    cost: 12,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=kombucha+SCOBY+starter&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "kombucha",
    name: "Glass fermentation jar (3.5 L)",
    description: "Wide-mouth jar for first fermentation with cloth cover.",
    cost: 15,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=glass+fermentation+jar+3.5L&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "kombucha",
    name: "Swing-top bottles (500 ml, 6-pack)",
    description: "Airtight bottles for second fermentation and carbonation.",
    cost: 16,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=swing+top+bottles+500ml+6+pack&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "kombucha",
    name: "pH test strips (100 pack)",
    description: "Check acidity levels to ensure safe, tasty kombucha.",
    cost: 8,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pH+test+strips+100&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
];

// =============================================================================
//  Roadmap Steps — 5 per hobby
// =============================================================================

export const foodRoadmapSteps = [
  // --- Sourdough ---
  { id: "sourdough-step-1", hobbyId: "sourdough", title: "Create your starter", description: "Mix equal parts flour and water in a jar. Feed daily for 5-7 days until it doubles in size and smells yeasty.", estimatedMinutes: 15, milestone: "Starter is alive!", sortOrder: 0 },
  { id: "sourdough-step-2", hobbyId: "sourdough", title: "Mix your first dough", description: "Combine active starter, flour, water, and salt. Stretch and fold every 30 minutes for 2 hours.", estimatedMinutes: 30, milestone: null, sortOrder: 1 },
  { id: "sourdough-step-3", hobbyId: "sourdough", title: "Bulk ferment & shape", description: "Let dough rise at room temperature for 4-6 hours. Shape into a boule and place in a floured banneton.", estimatedMinutes: 20, milestone: null, sortOrder: 2 },
  { id: "sourdough-step-4", hobbyId: "sourdough", title: "Cold proof overnight", description: "Refrigerate the shaped dough for 12-18 hours. This develops flavour and makes scoring easier.", estimatedMinutes: 5, milestone: null, sortOrder: 3 },
  { id: "sourdough-step-5", hobbyId: "sourdough", title: "Score and bake", description: "Score the top with a lame, bake in a preheated Dutch oven at 240 C for 20 min covered, then 25 min uncovered.", estimatedMinutes: 50, milestone: "First loaf baked!", sortOrder: 4 },

  // --- Fermentation ---
  { id: "fermentation-step-1", hobbyId: "fermentation", title: "Make a simple sauerkraut", description: "Shred cabbage, massage with 2% salt by weight, pack into a jar, and weigh down. Ferment 7-14 days.", estimatedMinutes: 30, milestone: "First ferment started!", sortOrder: 0 },
  { id: "fermentation-step-2", hobbyId: "fermentation", title: "Taste-test and adjust", description: "Start tasting at day 5. Learn to recognise the tangy, complex flavour of proper lacto-fermentation.", estimatedMinutes: 10, milestone: null, sortOrder: 1 },
  { id: "fermentation-step-3", hobbyId: "fermentation", title: "Try a brine ferment", description: "Make pickled cucumbers or carrots in a 3-5% salt brine. Different technique, different textures.", estimatedMinutes: 25, milestone: null, sortOrder: 2 },
  { id: "fermentation-step-4", hobbyId: "fermentation", title: "Make your first kimchi", description: "Salt napa cabbage, make a paste with gochugaru, garlic, ginger, and fish sauce. Pack and ferment 3-5 days.", estimatedMinutes: 60, milestone: "Kimchi master!", sortOrder: 3 },
  { id: "fermentation-step-5", hobbyId: "fermentation", title: "Experiment with flavours", description: "Try adding garlic, chilli, or herbs to your ferments. Start a fermentation journal to track what works.", estimatedMinutes: 30, milestone: null, sortOrder: 4 },

  // --- Coffee Roasting ---
  { id: "coffee-roasting-step-1", hobbyId: "coffee-roasting", title: "Source green beans", description: "Order a sampler of 3-4 single-origin green coffees. Look for specialty-grade beans with tasting notes.", estimatedMinutes: 20, milestone: null, sortOrder: 0 },
  { id: "coffee-roasting-step-2", hobbyId: "coffee-roasting", title: "First roast on stovetop", description: "Heat your popper or pan, add beans, and stir constantly. Listen for first crack around 200 C. Stop for a light roast.", estimatedMinutes: 15, milestone: "First roast complete!", sortOrder: 1 },
  { id: "coffee-roasting-step-3", hobbyId: "coffee-roasting", title: "Learn the roast levels", description: "Roast three batches to light, medium, and dark. Compare flavours after 24 hours of degassing.", estimatedMinutes: 45, milestone: null, sortOrder: 2 },
  { id: "coffee-roasting-step-4", hobbyId: "coffee-roasting", title: "Dial in your favourite profile", description: "Adjust heat and timing to bring out specific tasting notes. Record time, temperature, and crack points.", estimatedMinutes: 30, milestone: null, sortOrder: 3 },
  { id: "coffee-roasting-step-5", hobbyId: "coffee-roasting", title: "Brew and compare", description: "Use the same brewing method for each roast level. Develop your palate by noting acidity, body, and sweetness.", estimatedMinutes: 20, milestone: "Roast profile mastered!", sortOrder: 4 },

  // --- Pasta Making ---
  { id: "pasta-making-step-1", hobbyId: "pasta-making", title: "Make basic egg dough", description: "100 g flour per egg. Knead for 10 minutes until smooth and elastic. Rest for 30 minutes.", estimatedMinutes: 45, milestone: null, sortOrder: 0 },
  { id: "pasta-making-step-2", hobbyId: "pasta-making", title: "Roll and cut tagliatelle", description: "Roll dough through the machine from thickest to setting 5. Fold and cut into ribbons.", estimatedMinutes: 30, milestone: "First pasta cut!", sortOrder: 1 },
  { id: "pasta-making-step-3", hobbyId: "pasta-making", title: "Cook fresh pasta", description: "Boil heavily salted water. Fresh pasta cooks in 2-3 minutes. Toss with butter and Parmesan.", estimatedMinutes: 15, milestone: null, sortOrder: 2 },
  { id: "pasta-making-step-4", hobbyId: "pasta-making", title: "Try filled pasta", description: "Make simple ricotta ravioli. Roll thin, fill, seal edges with a fork, and cook gently.", estimatedMinutes: 60, milestone: "Ravioli master!", sortOrder: 3 },
  { id: "pasta-making-step-5", hobbyId: "pasta-making", title: "Experiment with shapes", description: "Try orecchiette by hand, pappardelle, or garganelli. Each shape pairs with different sauces.", estimatedMinutes: 45, milestone: null, sortOrder: 4 },

  // --- Sushi ---
  { id: "sushi-step-1", hobbyId: "sushi", title: "Perfect your sushi rice", description: "Rinse rice until water runs clear. Cook, then season with rice vinegar, sugar, and salt while fanning.", estimatedMinutes: 40, milestone: null, sortOrder: 0 },
  { id: "sushi-step-2", hobbyId: "sushi", title: "Roll a basic maki", description: "Place nori on bamboo mat, spread rice, add cucumber or avocado, and roll tightly. Cut with a wet knife.", estimatedMinutes: 30, milestone: "First roll!", sortOrder: 1 },
  { id: "sushi-step-3", hobbyId: "sushi", title: "Try an inside-out roll", description: "Flip the nori so rice is on the outside. Add sesame seeds. Requires plastic wrap on the mat.", estimatedMinutes: 30, milestone: null, sortOrder: 2 },
  { id: "sushi-step-4", hobbyId: "sushi", title: "Practice nigiri", description: "Form small rice oblongs, add a dab of wasabi, and drape a slice of fish or omelette on top.", estimatedMinutes: 30, milestone: null, sortOrder: 3 },
  { id: "sushi-step-5", hobbyId: "sushi", title: "Host a sushi night", description: "Prepare a spread with 3-4 roll varieties, pickled ginger, soy sauce, and miso soup. Impress your friends.", estimatedMinutes: 90, milestone: "Sushi chef!", sortOrder: 4 },

  // --- Smoking/BBQ ---
  { id: "smoking-bbq-step-1", hobbyId: "smoking-bbq", title: "Set up indirect heat", description: "Arrange charcoal on one side of the grill. Place a drip pan on the other. This is your smoking zone.", estimatedMinutes: 20, milestone: null, sortOrder: 0 },
  { id: "smoking-bbq-step-2", hobbyId: "smoking-bbq", title: "Smoke chicken thighs", description: "Season with a simple rub. Smoke at 120 C for 1.5 hours with apple wood. Internal temp: 75 C.", estimatedMinutes: 100, milestone: "First smoke!", sortOrder: 1 },
  { id: "smoking-bbq-step-3", hobbyId: "smoking-bbq", title: "Master temperature control", description: "Practice holding your grill at 110 C for 3 hours using vent adjustments. This is the key BBQ skill.", estimatedMinutes: 180, milestone: null, sortOrder: 2 },
  { id: "smoking-bbq-step-4", hobbyId: "smoking-bbq", title: "Try pulled pork", description: "Smoke a pork shoulder at 110 C for 8-10 hours. Wrap in foil at the stall (70 C). Pull at 95 C internal.", estimatedMinutes: 60, milestone: "Pitmaster level!", sortOrder: 3 },
  { id: "smoking-bbq-step-5", hobbyId: "smoking-bbq", title: "Build your signature rub", description: "Experiment with paprika, brown sugar, garlic powder, and spices. Develop a rub that's uniquely yours.", estimatedMinutes: 30, milestone: null, sortOrder: 4 },

  // --- Bread Baking ---
  { id: "bread-baking-step-1", hobbyId: "bread-baking", title: "Bake a no-knead loaf", description: "Mix flour, water, yeast, and salt. Let rise 12-18 hours. Bake in a hot Dutch oven. Zero technique needed.", estimatedMinutes: 20, milestone: "First loaf!", sortOrder: 0 },
  { id: "bread-baking-step-2", hobbyId: "bread-baking", title: "Learn basic kneading", description: "Make a standard white loaf with 10 minutes of kneading. Learn the windowpane test for gluten development.", estimatedMinutes: 30, milestone: null, sortOrder: 1 },
  { id: "bread-baking-step-3", hobbyId: "bread-baking", title: "Bake a sandwich loaf", description: "Use a loaf tin to make soft, even slices. Add milk and butter for enriched dough.", estimatedMinutes: 30, milestone: null, sortOrder: 2 },
  { id: "bread-baking-step-4", hobbyId: "bread-baking", title: "Try a braided challah", description: "Enrich dough with eggs and honey. Learn a 3-strand braid. Brush with egg wash for golden shine.", estimatedMinutes: 45, milestone: "Braiding skill!", sortOrder: 3 },
  { id: "bread-baking-step-5", hobbyId: "bread-baking", title: "Experiment with whole grains", description: "Incorporate rye, spelt, or wholemeal flour. Adjust hydration and expect denser, more flavourful loaves.", estimatedMinutes: 30, milestone: null, sortOrder: 4 },

  // --- Cocktails ---
  { id: "cocktails-step-1", hobbyId: "cocktails", title: "Master the Old Fashioned", description: "Whiskey, sugar, bitters, orange peel. Learn to stir over ice for proper dilution without bruising.", estimatedMinutes: 15, milestone: null, sortOrder: 0 },
  { id: "cocktails-step-2", hobbyId: "cocktails", title: "Learn the Daiquiri", description: "Rum, fresh lime, simple syrup. Practice shaking technique: 10-12 seconds with ice for perfect chill.", estimatedMinutes: 15, milestone: "Shaking mastered!", sortOrder: 1 },
  { id: "cocktails-step-3", hobbyId: "cocktails", title: "Make simple syrup and infusions", description: "1:1 sugar to water for simple syrup. Try rosemary, lavender, or ginger infusions for unique twists.", estimatedMinutes: 20, milestone: null, sortOrder: 2 },
  { id: "cocktails-step-4", hobbyId: "cocktails", title: "Build a Negroni and Margarita", description: "Two more essential recipes. Learn the difference between shaken (Margarita) and stirred (Negroni) drinks.", estimatedMinutes: 20, milestone: null, sortOrder: 3 },
  { id: "cocktails-step-5", hobbyId: "cocktails", title: "Host a cocktail evening", description: "Choose a 3-drink menu, prep garnishes, batch one cocktail for the group. Serve with confidence.", estimatedMinutes: 60, milestone: "Home bartender!", sortOrder: 4 },

  // --- Cheese Making ---
  { id: "cheese-making-step-1", hobbyId: "cheese-making", title: "Make fresh ricotta", description: "Heat whole milk with citric acid. Watch curds form in minutes. Strain through cheesecloth.", estimatedMinutes: 30, milestone: "First cheese!", sortOrder: 0 },
  { id: "cheese-making-step-2", hobbyId: "cheese-making", title: "Try 30-minute mozzarella", description: "Use rennet and citric acid. Stretch the hot curds until smooth and shiny. Best eaten within hours.", estimatedMinutes: 45, milestone: null, sortOrder: 1 },
  { id: "cheese-making-step-3", hobbyId: "cheese-making", title: "Make paneer", description: "Acid-set Indian cheese. Curdle milk with lemon juice, press into a block, and cube for cooking.", estimatedMinutes: 30, milestone: null, sortOrder: 2 },
  { id: "cheese-making-step-4", hobbyId: "cheese-making", title: "Attempt a simple feta", description: "Use rennet to set curds, cut, drain, and brine. Requires a few days of patience but the result is spectacular.", estimatedMinutes: 60, milestone: "Aged cheese!", sortOrder: 3 },
  { id: "cheese-making-step-5", hobbyId: "cheese-making", title: "Age your first hard cheese", description: "Make a basic farmhouse cheddar. Press, wax, and age for 2-3 months. The ultimate cheese making challenge.", estimatedMinutes: 120, milestone: "Cheese artisan!", sortOrder: 4 },

  // --- Chocolate ---
  { id: "chocolate-step-1", hobbyId: "chocolate", title: "Make simple truffles", description: "Melt chocolate into warm cream to make ganache. Chill, roll into balls, dust with cocoa powder.", estimatedMinutes: 45, milestone: "First truffles!", sortOrder: 0 },
  { id: "chocolate-step-2", hobbyId: "chocolate", title: "Learn to temper chocolate", description: "Melt to 50 C, cool to 27 C on marble, reheat to 31 C. Test on parchment for a clean snap.", estimatedMinutes: 40, milestone: null, sortOrder: 1 },
  { id: "chocolate-step-3", hobbyId: "chocolate", title: "Make chocolate-dipped fruits", description: "Dip strawberries, orange slices, and dried apricots in tempered chocolate. Let set on parchment.", estimatedMinutes: 30, milestone: null, sortOrder: 2 },
  { id: "chocolate-step-4", hobbyId: "chocolate", title: "Mould chocolate bars", description: "Pour tempered chocolate into polycarbonate moulds. Tap to release air bubbles. Chill until set.", estimatedMinutes: 45, milestone: "Bar maker!", sortOrder: 3 },
  { id: "chocolate-step-5", hobbyId: "chocolate", title: "Create filled bonbons", description: "Coat moulds with tempered chocolate, fill with ganache or caramel, seal with more chocolate.", estimatedMinutes: 90, milestone: "Chocolatier!", sortOrder: 4 },

  // --- Pickling ---
  { id: "pickling-step-1", hobbyId: "pickling", title: "Quick refrigerator pickles", description: "Slice cucumbers, make a vinegar-water-sugar brine with dill and garlic. Jar and refrigerate. Ready in 24 hours.", estimatedMinutes: 20, milestone: "First pickles!", sortOrder: 0 },
  { id: "pickling-step-2", hobbyId: "pickling", title: "Pickle different vegetables", description: "Try carrots, radishes, red onions, and green beans. Each vegetable brings a different texture and flavour.", estimatedMinutes: 30, milestone: null, sortOrder: 1 },
  { id: "pickling-step-3", hobbyId: "pickling", title: "Experiment with spice blends", description: "Add mustard seeds, coriander, chilli flakes, or turmeric to your brine for unique flavour profiles.", estimatedMinutes: 25, milestone: null, sortOrder: 2 },
  { id: "pickling-step-4", hobbyId: "pickling", title: "Learn water-bath canning", description: "Sterilise jars, fill with hot brine and vegetables, process in boiling water. Creates shelf-stable pickles.", estimatedMinutes: 60, milestone: "Shelf-stable!", sortOrder: 3 },
  { id: "pickling-step-5", hobbyId: "pickling", title: "Create a pickle gift set", description: "Make 3-4 varieties, label jars beautifully, and gift them. Nothing impresses like homemade pickles.", estimatedMinutes: 45, milestone: "Pickling pro!", sortOrder: 4 },

  // --- Hot Sauce ---
  { id: "hot-sauce-step-1", hobbyId: "hot-sauce", title: "Make a simple vinegar hot sauce", description: "Simmer jalapenos, garlic, and vinegar. Blend until smooth. Bottle and refrigerate. Ready immediately.", estimatedMinutes: 30, milestone: "First bottle!", sortOrder: 0 },
  { id: "hot-sauce-step-2", hobbyId: "hot-sauce", title: "Try a fermented hot sauce", description: "Blend peppers with salt (3%), jar with an airlock, ferment 5-7 days. Add vinegar after fermenting.", estimatedMinutes: 25, milestone: null, sortOrder: 1 },
  { id: "hot-sauce-step-3", hobbyId: "hot-sauce", title: "Experiment with fruit and peppers", description: "Combine mango-habanero or pineapple-scotch bonnet for sweet heat. Fruit adds body and complexity.", estimatedMinutes: 30, milestone: null, sortOrder: 2 },
  { id: "hot-sauce-step-4", hobbyId: "hot-sauce", title: "Create a smoky chipotle sauce", description: "Use dried chipotle peppers, roasted garlic, and smoked paprika for deep, smoky heat.", estimatedMinutes: 30, milestone: "Smoky perfection!", sortOrder: 3 },
  { id: "hot-sauce-step-5", hobbyId: "hot-sauce", title: "Design your label and brand", description: "Name your sauce, design a label, and bottle a batch of your best recipe for friends and family.", estimatedMinutes: 45, milestone: "Sauce brand!", sortOrder: 4 },

  // --- Korean Cooking ---
  { id: "korean-cooking-step-1", hobbyId: "korean-cooking", title: "Make bibimbap", description: "Cook rice, prepare 4-5 vegetable toppings, fry an egg, and top with gochujang. Mix at the table.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "korean-cooking-step-2", hobbyId: "korean-cooking", title: "Marinate and grill bulgogi", description: "Thinly slice beef, marinate in soy, sesame, garlic, pear, and sugar for 2 hours. Grill or pan-fry.", estimatedMinutes: 30, milestone: "Bulgogi mastered!", sortOrder: 1 },
  { id: "korean-cooking-step-3", hobbyId: "korean-cooking", title: "Prepare three banchan", description: "Make seasoned spinach (sigeumchi namul), pickled radish, and soy-braised potatoes (gamja jorim).", estimatedMinutes: 45, milestone: null, sortOrder: 2 },
  { id: "korean-cooking-step-4", hobbyId: "korean-cooking", title: "Make kimchi from scratch", description: "Salt napa cabbage, make paste with gochugaru, garlic, ginger, and fish sauce. Pack into jars.", estimatedMinutes: 90, milestone: "Kimchi maker!", sortOrder: 3 },
  { id: "korean-cooking-step-5", hobbyId: "korean-cooking", title: "Cook a Korean stew (jjigae)", description: "Make kimchi jjigae or sundubu jjigae with soft tofu. Perfect cold-weather comfort food.", estimatedMinutes: 40, milestone: null, sortOrder: 4 },

  // --- Indian Curry ---
  { id: "indian-curry-step-1", hobbyId: "indian-curry", title: "Cook a basic dal", description: "Simmer red lentils with turmeric, then temper with cumin, garlic, and chilli in hot oil. Pour over dal.", estimatedMinutes: 30, milestone: "First dal!", sortOrder: 0 },
  { id: "indian-curry-step-2", hobbyId: "indian-curry", title: "Make butter chicken", description: "Marinate chicken in yogurt and spices. Cook in a tomato-cream sauce with garam masala and butter.", estimatedMinutes: 60, milestone: null, sortOrder: 1 },
  { id: "indian-curry-step-3", hobbyId: "indian-curry", title: "Learn the tadka technique", description: "Heat oil, add whole spices (mustard seeds, cumin, curry leaves) until they pop. Pour over cooked dishes.", estimatedMinutes: 15, milestone: "Tadka mastered!", sortOrder: 2 },
  { id: "indian-curry-step-4", hobbyId: "indian-curry", title: "Make chana masala", description: "Cook chickpeas in a spiced tomato-onion gravy. A vegetarian staple with deep, layered flavours.", estimatedMinutes: 45, milestone: null, sortOrder: 3 },
  { id: "indian-curry-step-5", hobbyId: "indian-curry", title: "Prepare a full thali", description: "Serve rice, dal, one dry vegetable, one curry, raita, and pickle on a single plate. A complete Indian meal.", estimatedMinutes: 90, milestone: "Thali master!", sortOrder: 4 },

  // --- Pizza ---
  { id: "pizza-step-1", hobbyId: "pizza", title: "Make a basic pizza dough", description: "Combine flour, water, yeast, salt, and olive oil. Knead 8 minutes. Let rise 2 hours or cold-proof overnight.", estimatedMinutes: 20, milestone: null, sortOrder: 0 },
  { id: "pizza-step-2", hobbyId: "pizza", title: "Shape and stretch by hand", description: "Press dough into a circle, then stretch over your knuckles. Aim for thin centre, puffy cornicione edge.", estimatedMinutes: 15, milestone: "Dough stretching!", sortOrder: 1 },
  { id: "pizza-step-3", hobbyId: "pizza", title: "Bake a Margherita", description: "Sauce, fresh mozzarella, basil. Bake on preheated stone at maximum oven temperature (250+ C) for 8-10 minutes.", estimatedMinutes: 15, milestone: null, sortOrder: 2 },
  { id: "pizza-step-4", hobbyId: "pizza", title: "Try a long cold ferment", description: "Let dough rise in the fridge for 48-72 hours. The slow fermentation develops complex flavours and better texture.", estimatedMinutes: 10, milestone: null, sortOrder: 3 },
  { id: "pizza-step-5", hobbyId: "pizza", title: "Host a pizza party", description: "Prep multiple dough balls and a topping station. Let guests build their own pizzas. Bake in rotation.", estimatedMinutes: 60, milestone: "Pizza night host!", sortOrder: 4 },

  // --- Pastry ---
  { id: "pastry-step-1", hobbyId: "pastry", title: "Make shortcrust pastry", description: "Rub cold butter into flour, add cold water. Chill, roll, line a tart tin. Blind bake with weights.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "pastry-step-2", hobbyId: "pastry", title: "Bake a fruit tart", description: "Fill blind-baked shell with pastry cream, top with arranged fresh fruit. Glaze with apricot jam.", estimatedMinutes: 60, milestone: "First tart!", sortOrder: 1 },
  { id: "pastry-step-3", hobbyId: "pastry", title: "Make choux pastry", description: "Cook butter, water, and flour on the stove, then beat in eggs. Pipe eclairs or profiteroles and bake.", estimatedMinutes: 45, milestone: null, sortOrder: 2 },
  { id: "pastry-step-4", hobbyId: "pastry", title: "Attempt rough puff pastry", description: "Quick method: fold grated frozen butter into flour, roll and fold 4 times. Good enough for palmiers and tarts.", estimatedMinutes: 60, milestone: "Lamination!", sortOrder: 3 },
  { id: "pastry-step-5", hobbyId: "pastry", title: "Bake croissants", description: "Make a yeasted dough, encase a butter block, roll and fold 3 times. Shape, proof, and bake until golden.", estimatedMinutes: 120, milestone: "Croissant baker!", sortOrder: 4 },

  // --- Tea Ceremony ---
  { id: "tea-ceremony-step-1", hobbyId: "tea-ceremony", title: "Learn water temperatures", description: "Green tea: 70-80 C. Oolong: 85-90 C. Black: 95-100 C. Use a thermometer until you can judge by sight.", estimatedMinutes: 15, milestone: null, sortOrder: 0 },
  { id: "tea-ceremony-step-2", hobbyId: "tea-ceremony", title: "Brew your first gongfu session", description: "Use a gaiwan or small teapot. Short steeps (15-30 seconds), multiple infusions. Notice how flavour evolves.", estimatedMinutes: 30, milestone: "First gongfu!", sortOrder: 1 },
  { id: "tea-ceremony-step-3", hobbyId: "tea-ceremony", title: "Explore tea types", description: "Taste green, oolong, black, white, and pu-erh back to back. Take notes on aroma, body, and finish.", estimatedMinutes: 45, milestone: null, sortOrder: 2 },
  { id: "tea-ceremony-step-4", hobbyId: "tea-ceremony", title: "Practice mindful brewing", description: "Slow down. Focus on each step: warming the vessel, measuring leaves, pouring water, waiting. This is meditation.", estimatedMinutes: 20, milestone: "Mindful brewer!", sortOrder: 3 },
  { id: "tea-ceremony-step-5", hobbyId: "tea-ceremony", title: "Host a tea tasting", description: "Prepare 3-4 teas, serve with light snacks. Guide guests through tasting notes and brewing techniques.", estimatedMinutes: 60, milestone: "Tea host!", sortOrder: 4 },

  // --- Kombucha ---
  { id: "kombucha-step-1", hobbyId: "kombucha", title: "Brew sweet tea base", description: "Boil water, steep black tea, dissolve sugar (80 g per litre). Cool to room temperature before adding SCOBY.", estimatedMinutes: 20, milestone: null, sortOrder: 0 },
  { id: "kombucha-step-2", hobbyId: "kombucha", title: "Start first fermentation", description: "Add SCOBY and starter liquid to cooled tea. Cover with cloth. Ferment 7-14 days at room temperature.", estimatedMinutes: 10, milestone: "Brewing started!", sortOrder: 1 },
  { id: "kombucha-step-3", hobbyId: "kombucha", title: "Taste and bottle", description: "Taste at day 7. When it's tangy but slightly sweet, bottle into swing-top bottles, leaving SCOBY for next batch.", estimatedMinutes: 20, milestone: null, sortOrder: 2 },
  { id: "kombucha-step-4", hobbyId: "kombucha", title: "Second ferment with flavours", description: "Add fruit, ginger, or juice to bottles. Seal and leave 2-3 days for natural carbonation. Burp daily.", estimatedMinutes: 15, milestone: "Fizzy kombucha!", sortOrder: 3 },
  { id: "kombucha-step-5", hobbyId: "kombucha", title: "Develop a continuous brew", description: "Keep a large jar going permanently. Draw off kombucha as needed, top up with fresh sweet tea.", estimatedMinutes: 10, milestone: "Continuous brewer!", sortOrder: 4 },
];

// =============================================================================
//  FAQ Items — 2-3 per first 8 hobbies
// =============================================================================

export const foodFaqItems = [
  // --- Sourdough ---
  { hobbyId: "sourdough", question: "How long does it take to get a sourdough starter going?", answer: "About 5-7 days of daily feeding. You'll see bubbles by day 3, but wait until it reliably doubles in 4-6 hours before baking with it." },
  { hobbyId: "sourdough", question: "Can I use regular all-purpose flour?", answer: "Yes, but bread flour with higher protein (12%+) gives better gluten structure and a more open crumb. You can also mix in some wholemeal for extra flavour." },
  { hobbyId: "sourdough", question: "Do I need a Dutch oven?", answer: "It helps enormously by trapping steam for a crispier crust, but you can also bake on a stone with a tray of water in the oven for steam." },

  // --- Fermentation ---
  { hobbyId: "fermentation", question: "Is a white film on my ferment mould?", answer: "A thin white film is usually kahm yeast, which is harmless but tastes bad. Skim it off. Fuzzy, coloured patches are mould and the batch should be discarded." },
  { hobbyId: "fermentation", question: "How do I know when fermentation is done?", answer: "Taste it! When it reaches your preferred level of tanginess, move the jar to the fridge to slow fermentation dramatically." },

  // --- Coffee Roasting ---
  { hobbyId: "coffee-roasting", question: "Can I roast coffee in a regular frying pan?", answer: "Yes, but you'll need to stir constantly for even roasting. A whirley pop or popcorn popper gives more consistent results with less effort." },
  { hobbyId: "coffee-roasting", question: "How soon can I drink freshly roasted coffee?", answer: "Wait at least 12-24 hours for degassing. Most beans peak in flavour 3-7 days after roasting and remain good for 2-3 weeks." },

  // --- Pasta Making ---
  { hobbyId: "pasta-making", question: "Do I need a pasta machine?", answer: "Not for your first batches. A rolling pin works fine for rustic shapes. But a machine makes thin, consistent sheets much easier, especially for ravioli." },
  { hobbyId: "pasta-making", question: "Can I make pasta without eggs?", answer: "Absolutely. Semolina and water makes excellent southern Italian-style pasta for shapes like orecchiette and cavatelli." },

  // --- Sushi ---
  { hobbyId: "sushi", question: "Do I need to use raw fish?", answer: "Not at all. Cooked shrimp, crab, omelette, avocado, cucumber, and smoked salmon all make excellent sushi without any raw fish concerns." },
  { hobbyId: "sushi", question: "Where can I buy sushi-grade fish in Switzerland?", answer: "Asian supermarkets and fish counters at Globus or Manor often stock sushi-grade salmon and tuna. Always ask for fish intended for raw consumption." },
  { hobbyId: "sushi", question: "Why does my sushi rice fall apart?", answer: "You're likely rinsing too little (starch helps it stick) or not seasoning while hot. The vinegar mixture should be folded in while rice is steaming." },

  // --- Smoking/BBQ ---
  { hobbyId: "smoking-bbq", question: "Can I smoke on a regular gas grill?", answer: "Yes, using a smoker box with wood chips on one burner while cooking on the other. It won't match a charcoal setup but produces decent smoke flavour." },
  { hobbyId: "smoking-bbq", question: "What's the best wood for beginners?", answer: "Apple wood is mild and forgiving, good with almost any protein. Hickory is stronger and classic for pork. Avoid mesquite until you're experienced as it can overpower." },

  // --- Bread Baking ---
  { hobbyId: "bread-baking", question: "Why is my bread dense and heavy?", answer: "Most likely under-kneaded dough or yeast that wasn't active. Ensure your water is warm (not hot) and knead until the dough passes the windowpane test." },
  { hobbyId: "bread-baking", question: "Can I bake bread without a Dutch oven?", answer: "Yes. Use a baking stone or sheet and place a pan of boiling water on the lower rack for steam during the first 15 minutes of baking." },

  // --- Cocktails ---
  { hobbyId: "cocktails", question: "What spirits should I buy first?", answer: "A versatile starter bar needs: a London dry gin, a bourbon or rye whiskey, a white rum, and a blanco tequila. These cover 90% of classic cocktails." },
  { hobbyId: "cocktails", question: "Do I really need fresh citrus?", answer: "Yes. The difference between fresh-squeezed lime and bottled lime juice is night and day. It's the single biggest upgrade you can make to your cocktails." },
  { hobbyId: "cocktails", question: "How long does simple syrup last?", answer: "Plain 1:1 simple syrup lasts 2-3 weeks refrigerated. Adding a small amount of vodka extends it to a month. Rich syrup (2:1) lasts longer." },
];

// =============================================================================
//  Cost Breakdowns — 1 per hobby (starter / 3-month / 1-year, in CHF)
// =============================================================================

export const foodCostBreakdowns = [
  {
    hobbyId: "sourdough",
    starter: 35,
    threeMonth: 65,
    oneYear: 150,
    tips: [
      "Flour is your ongoing cost. Buy in bulk from a local mill for savings.",
      "A Dutch oven is optional but a game-changer. Check second-hand listings.",
      "Sourdough starter is free once established. Share discard with neighbours.",
    ],
  },
  {
    hobbyId: "fermentation",
    starter: 35,
    threeMonth: 55,
    oneYear: 100,
    tips: [
      "Buy vegetables in season at farmers' markets for the lowest cost.",
      "Reuse jars from store-bought products to save on containers.",
      "Salt is your main ongoing expense and costs just a few francs per kilo.",
    ],
  },
  {
    hobbyId: "coffee-roasting",
    starter: 70,
    threeMonth: 140,
    oneYear: 350,
    tips: [
      "Green beans cost 50-70% less than roasted specialty coffee.",
      "A popcorn popper is the cheapest entry point before investing in a proper roaster.",
      "Buy green beans in 5 kg batches from online importers for the best price.",
    ],
  },
  {
    hobbyId: "pasta-making",
    starter: 55,
    threeMonth: 75,
    oneYear: 120,
    tips: [
      "Flour and eggs are cheap. The machine is the only real investment.",
      "Look for second-hand Marcato or Imperia machines at flea markets.",
      "A drying rack can be DIY'd from a wooden coat hanger.",
    ],
  },
  {
    hobbyId: "sushi",
    starter: 60,
    threeMonth: 120,
    oneYear: 300,
    tips: [
      "Vegetarian sushi is much cheaper than fish-based rolls.",
      "Buy nori and sushi rice in bulk from Asian supermarkets.",
      "A bamboo mat costs almost nothing and lasts years.",
    ],
  },
  {
    hobbyId: "smoking-bbq",
    starter: 180,
    threeMonth: 280,
    oneYear: 500,
    tips: [
      "A basic kettle grill handles both grilling and smoking brilliantly.",
      "Buy charcoal in bulk during spring sales for significant savings.",
      "Cheaper cuts (pork shoulder, chicken thighs) are actually ideal for smoking.",
    ],
  },
  {
    hobbyId: "bread-baking",
    starter: 30,
    threeMonth: 55,
    oneYear: 120,
    tips: [
      "Flour and yeast are extremely affordable. A loaf costs under CHF 1 in ingredients.",
      "Most tools you likely already own. A scale is the most important investment.",
      "Baking bread replaces buying it, so the hobby practically pays for itself.",
    ],
  },
  {
    hobbyId: "cocktails",
    starter: 80,
    threeMonth: 180,
    oneYear: 400,
    tips: [
      "Buy mid-range spirits. Ultra-premium bottles are wasted in mixed drinks.",
      "Fresh citrus and homemade syrups cost almost nothing and elevate everything.",
      "Build your bar gradually. Start with 4 core spirits and expand over time.",
    ],
  },
  {
    hobbyId: "cheese-making",
    starter: 50,
    threeMonth: 90,
    oneYear: 180,
    tips: [
      "Fresh milk from a local farm produces better cheese than supermarket UHT.",
      "Rennet and citric acid are very cheap and last many batches.",
      "Start with fresh cheeses. Aged cheeses require extra equipment and months of waiting.",
    ],
  },
  {
    hobbyId: "chocolate",
    starter: 60,
    threeMonth: 120,
    oneYear: 280,
    tips: [
      "Buy couverture chocolate in bulk from baking suppliers, not retail bars.",
      "Polycarbonate moulds are reusable indefinitely. One set covers many projects.",
      "Gift your creations. Handmade chocolates have high perceived value.",
    ],
  },
  {
    hobbyId: "pickling",
    starter: 25,
    threeMonth: 40,
    oneYear: 80,
    tips: [
      "Seasonal vegetables at farmers' markets are cheap and perfect for pickling.",
      "Jars are reusable for years. Only lids need occasional replacing.",
      "Pickling extends the life of produce you'd otherwise waste.",
    ],
  },
  {
    hobbyId: "hot-sauce",
    starter: 35,
    threeMonth: 50,
    oneYear: 90,
    tips: [
      "Growing your own peppers from seed is the cheapest source of chillies.",
      "Vinegar and salt are extremely inexpensive base ingredients.",
      "A single batch of hot sauce yields many bottles, making great gifts.",
    ],
  },
  {
    hobbyId: "korean-cooking",
    starter: 50,
    threeMonth: 100,
    oneYear: 250,
    tips: [
      "Korean pantry staples (gochugaru, doenjang, gochujang) last months and cost under CHF 30 total.",
      "Asian supermarkets in Swiss cities have dramatically lower prices than regular shops.",
      "Many banchan use very cheap vegetables like spinach, bean sprouts, and potatoes.",
    ],
  },
  {
    hobbyId: "indian-curry",
    starter: 45,
    threeMonth: 80,
    oneYear: 180,
    tips: [
      "Whole spices bought from Indian shops cost a fraction of supermarket prices.",
      "A spice box (masala dabba) keeps daily-use spices organised and accessible.",
      "Lentil-based dals are among the cheapest, most nutritious meals you can make.",
    ],
  },
  {
    hobbyId: "pizza",
    starter: 60,
    threeMonth: 100,
    oneYear: 200,
    tips: [
      "A pizza stone is the best single investment. Heats evenly and lasts a lifetime.",
      "Dough ingredients (flour, yeast, salt) cost well under CHF 1 per pizza.",
      "San Marzano tins bought in bulk from Italian delis are much cheaper.",
    ],
  },
  {
    hobbyId: "pastry",
    starter: 55,
    threeMonth: 100,
    oneYear: 220,
    tips: [
      "Butter is the main ongoing cost. Buy in bulk when on sale and freeze.",
      "Tart tins and piping tips are one-time investments that last decades.",
      "Start with shortcrust and choux. Puff pastry uses a lot of butter per batch.",
    ],
  },
  {
    hobbyId: "tea-ceremony",
    starter: 65,
    threeMonth: 110,
    oneYear: 250,
    tips: [
      "Good loose-leaf tea costs more upfront but yields many more cups than bags.",
      "A gaiwan is the most versatile and affordable serious tea vessel.",
      "Buy tea directly from online specialty shops rather than retail tea boutiques.",
    ],
  },
  {
    hobbyId: "kombucha",
    starter: 40,
    threeMonth: 60,
    oneYear: 120,
    tips: [
      "A single SCOBY reproduces endlessly. You'll never need to buy another.",
      "Black tea and sugar are the cheapest possible ingredients for a brewing hobby.",
      "Home-brewed kombucha costs about CHF 0.50 per litre vs CHF 4-6 in shops.",
    ],
  },
];
