// ═══════════════════════════════════════════════════════════════
//  MAKER / DIY — 16 Hobbies Seed Data
//  CHF pricing, Swiss market, Amazon.de affiliate links
// ═══════════════════════════════════════════════════════════════

// ─── Hobbies ─────────────────────────────────────────────────

export const makerHobbies = [
  {
    id: "woodworking",
    title: "Woodworking",
    hook: "Build something that outlasts you.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&h=800&fit=crop",
    tags: ["creative", "technical", "hands-on", "functional"],
    costText: "CHF 80\u2013250",
    timeText: "4h/week",
    difficultyText: "Medium",
    whyLove: "There is nothing like pulling a finished piece off the bench and knowing every joint, every curve came from your hands. Woodworking teaches patience, geometry, and problem-solving all at once. The smell of fresh-cut timber is its own reward.",
    difficultyExplain: "Basic joinery and hand-tool work are very approachable. Power tools add speed but require safety awareness.",
    pitfalls: [
      "Buying too many power tools before mastering hand tools",
      "Skipping wood conditioning and ending up with warped projects",
      "Ignoring grain direction when cutting or planing"
    ],
    sortOrder: 0,
  },
  {
    id: "3d-printing",
    title: "3D Printing",
    hook: "Turn ideas into objects overnight.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600&h=800&fit=crop",
    tags: ["technical", "digital", "prototyping", "creative"],
    costText: "CHF 200\u2013400",
    timeText: "3h/week",
    difficultyText: "Medium",
    whyLove: "You sketch something on Monday, slice it Tuesday, and hold a real object Wednesday morning. 3D printing collapses the gap between imagination and reality. The community shares thousands of free designs online.",
    difficultyExplain: "Entry-level FDM printers are plug-and-play. Learning slicer settings and CAD modelling takes a few weeks of practice.",
    pitfalls: [
      "Choosing a cheap printer with no community support",
      "Ignoring bed levelling and first-layer calibration",
      "Printing everything at 100% infill and wasting filament"
    ],
    sortOrder: 1,
  },
  {
    id: "electronics",
    title: "Electronics",
    hook: "Make circuits do your bidding.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=800&fit=crop",
    tags: ["technical", "stem", "creative", "arduino"],
    costText: "CHF 40\u2013150",
    timeText: "3h/week",
    difficultyText: "Medium",
    whyLove: "Blinking your first LED feels trivial, but automating your entire desk setup feels like magic. Electronics bridges the digital and physical worlds in ways no other hobby can. Arduino and Raspberry Pi make the learning curve gentle.",
    difficultyExplain: "Breadboard prototyping requires no soldering. Reading schematics and soldering come with practice.",
    pitfalls: [
      "Skipping resistor calculations and burning out components",
      "Buying random parts without a clear first project",
      "Forgetting to disconnect power before rewiring"
    ],
    sortOrder: 2,
  },
  {
    id: "leathercraft",
    title: "Leathercraft",
    hook: "Shape leather into lasting keepsakes.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1473188588951-5b5f4b511f63?w=600&h=800&fit=crop",
    tags: ["creative", "hands-on", "fashion", "traditional"],
    costText: "CHF 60\u2013180",
    timeText: "3h/week",
    difficultyText: "Medium",
    whyLove: "Leather gets better with age\u2014your wallet or belt develops a unique patina that tells its story. The craft is meditative: cutting, stitching, and burnishing demand focus but reward you with heirloom-quality pieces.",
    difficultyExplain: "Simple card holders and key fobs are beginner-friendly. Bags and shoes require advanced pattern-making.",
    pitfalls: [
      "Using cheap bonded leather that cracks and peels",
      "Cutting without a sharp rotary blade and ruining edges",
      "Over-dyeing and getting blotchy, uneven colour"
    ],
    sortOrder: 3,
  },
  {
    id: "candle-making",
    title: "Candle Making",
    hook: "Pour light into your own designs.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1602607937533-0ba85a47d277?w=600&h=800&fit=crop",
    tags: ["creative", "relaxing", "gifts", "home-decor"],
    costText: "CHF 30\u201380",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove: "Few hobbies deliver finished products as quickly as candle making. Within an hour you can pour, scent, and colour a candle that doubles as a gift or home accent. The fragrance blending alone is endlessly creative.",
    difficultyExplain: "Melt, add fragrance, pour. The basics take an afternoon to learn.",
    pitfalls: [
      "Overheating wax past its flash point\u2014always use a thermometer",
      "Using too much fragrance oil and getting a weak hot throw",
      "Choosing wicks that are too small, causing tunnelling"
    ],
    sortOrder: 4,
  },
  {
    id: "soap-making",
    title: "Soap Making",
    hook: "Chemistry you can shower with.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=600&h=800&fit=crop",
    tags: ["creative", "science", "self-care", "gifts"],
    costText: "CHF 40\u2013100",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove: "Cold-process soap is edible-grade chemistry that smells amazing. You control every ingredient\u2014no mystery additives\u2014and the swirl patterns turn each bar into a small work of art. People will beg you for gifts.",
    difficultyExplain: "Melt-and-pour is effortless. Cold-process requires handling lye safely, but it is straightforward with proper gear.",
    pitfalls: [
      "Not wearing gloves and goggles when handling lye",
      "Adding fragrance at the wrong temperature, causing seizing",
      "Unmoulding too early and denting soft bars"
    ],
    sortOrder: 5,
  },
  {
    id: "metalworking",
    title: "Metalworking",
    hook: "Forge raw metal into real things.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600&h=800&fit=crop",
    tags: ["technical", "hands-on", "industrial", "creative"],
    costText: "CHF 150\u2013400",
    timeText: "4h/week",
    difficultyText: "Hard",
    whyLove: "Heating steel until it glows orange and bending it under a hammer is primal and deeply satisfying. Whether you weld garden furniture or forge a bottle opener, metalworking connects you to one of humanity\u2019s oldest crafts.",
    difficultyExplain: "Welding and forging require safety training and access to a workshop or garage. Start with a community makerspace.",
    pitfalls: [
      "Skipping proper ventilation when welding or grinding",
      "Using the wrong filler rod for the base metal",
      "Not pre-heating thick stock and getting cold cracks"
    ],
    sortOrder: 6,
  },
  {
    id: "model-building",
    title: "Model Building",
    hook: "Shrink the world to your workbench.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=800&fit=crop",
    tags: ["creative", "detail-oriented", "relaxing", "collecting"],
    costText: "CHF 30\u2013120",
    timeText: "3h/week",
    difficultyText: "Easy",
    whyLove: "Model building is meditation with tweezers. Each tiny part demands your full attention, and when you step back, a warship, a classic car, or an entire diorama stares back at you. The sense of scale is mesmerising.",
    difficultyExplain: "Snap-fit kits need no glue. Painting and weathering are optional but rewarding next steps.",
    pitfalls: [
      "Cutting parts off the sprue at an angle and leaving nub marks",
      "Applying thick paint coats that obscure detail",
      "Rushing assembly and misaligning fuselage halves"
    ],
    sortOrder: 7,
  },
  {
    id: "bookbinding",
    title: "Bookbinding",
    hook: "Stitch pages into something permanent.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1639371040157-55b642d03f4f?w=800&h=1066&fit=crop&q=85",
    tags: ["creative", "traditional", "paper-craft", "gifts"],
    costText: "CHF 30\u201390",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove: "In an age of screens, a hand-bound journal or sketchbook feels like a quiet rebellion. The rhythmic sewing of signatures is calming, and every book you make is a one-of-a-kind object that people treasure.",
    difficultyExplain: "Pamphlet and Japanese stab binding can be learned in a single session. Hardcover case binding takes more practice.",
    pitfalls: [
      "Using paper grain in the wrong direction, causing warped covers",
      "Pulling thread too tight and tearing the signatures",
      "Skipping the pressing step and getting a puffy spine"
    ],
    sortOrder: 8,
  },
  {
    id: "furniture-restoration",
    title: "Furniture Restoration",
    hook: "Give old furniture a second life.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&h=800&fit=crop",
    tags: ["creative", "sustainable", "hands-on", "home-decor"],
    costText: "CHF 50\u2013200",
    timeText: "4h/week",
    difficultyText: "Medium",
    whyLove: "Stripping decades of paint off a mid-century sideboard to reveal gorgeous walnut underneath is pure treasure-hunting. Restoration is sustainable, budget-friendly, and your living room becomes a gallery of comeback stories.",
    difficultyExplain: "Sanding and re-staining are straightforward. Re-upholstery and structural repairs require more skill.",
    pitfalls: [
      "Sanding through veneer because you used too coarse a grit",
      "Applying polyurethane in humid conditions and getting bubbles",
      "Stripping paint on pre-1980 pieces without testing for lead"
    ],
    sortOrder: 9,
  },
  {
    id: "knife-making",
    title: "Knife Making",
    hook: "Forge a blade you will carry daily.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=600&h=800&fit=crop",
    tags: ["technical", "forging", "hands-on", "outdoors"],
    costText: "CHF 100\u2013300",
    timeText: "4h/week",
    difficultyText: "Hard",
    whyLove: "A knife you forged yourself carries a primal weight no store-bought blade can match. The process\u2014profiling, heat-treating, grinding, handle-shaping\u2014is a full-spectrum maker journey from raw steel to a tool you use every day.",
    difficultyExplain: "Stock-removal with a file is beginner-accessible. Forge work with an anvil and heat treat require dedicated equipment.",
    pitfalls: [
      "Overheating the blade during grinding and ruining the temper",
      "Skipping a proper quench oil and cracking the steel",
      "Making the handle too thick for comfortable grip"
    ],
    sortOrder: 10,
  },
  {
    id: "pottery-wheel",
    title: "Pottery Wheel",
    hook: "Centre clay and find your centre.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&h=800&fit=crop",
    tags: ["creative", "meditative", "functional", "artistic"],
    costText: "CHF 100\u2013350",
    timeText: "3h/week",
    difficultyText: "Medium",
    whyLove: "Throwing on the wheel is hypnotic\u2014your hands shape spinning clay into bowls, mugs, and vases that you eat and drink from every day. No two pieces are identical, and glazing adds an element of happy surprise.",
    difficultyExplain: "Centring clay takes practice but is achievable in 3\u20135 sessions. Trimming and glazing extend the learning curve.",
    pitfalls: [
      "Using clay that is too wet and collapsing walls",
      "Pulling up too fast and getting uneven thickness",
      "Forgetting to compress the bottom and getting S-cracks"
    ],
    sortOrder: 11,
  },
  {
    id: "glassblowing",
    title: "Glassblowing",
    hook: "Breathe life into molten glass.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1543946602-a0fef17fc1be?w=600&h=800&fit=crop",
    tags: ["creative", "artistic", "advanced", "fire"],
    costText: "CHF 150\u2013400",
    timeText: "3h/week",
    difficultyText: "Hard",
    whyLove: "Working with 1,000\u00b0C molten glass is an adrenaline-art hybrid. Colours bloom and shift inside the gather, and within minutes a glowing blob becomes an ornament, cup, or sculpture. It is performance art you get to keep.",
    difficultyExplain: "Classes at a hot shop are essential\u2014home setups are impractical for beginners. Lampwork (torch) is a more accessible entry point.",
    pitfalls: [
      "Not annealing pieces properly, causing them to crack hours later",
      "Turning the pipe unevenly and getting a lopsided shape",
      "Wearing synthetic clothing near the glory hole\u2014cotton only"
    ],
    sortOrder: 12,
  },
  {
    id: "loom-weaving",
    title: "Loom Weaving",
    hook: "Thread by thread, make fabric yours.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=600&h=800&fit=crop",
    tags: ["creative", "textile", "meditative", "traditional"],
    costText: "CHF 50\u2013200",
    timeText: "3h/week",
    difficultyText: "Medium",
    whyLove: "The rhythmic clack of the shuttle is deeply calming. Loom weaving lets you create scarves, wall hangings, and table runners with textures and colour gradients that are impossible to replicate in a factory.",
    difficultyExplain: "A rigid-heddle loom is straightforward to warp and weave. Multi-shaft looms open up complex patterns but take longer to master.",
    pitfalls: [
      "Uneven warp tension causing wavy selvedges",
      "Beating the weft too hard and getting a stiff, dense fabric",
      "Choosing slippery yarn for your first warp\u2014use cotton"
    ],
    sortOrder: 13,
  },
  {
    id: "clock-repair",
    title: "Clock Repair",
    hook: "Bring forgotten timepieces back to life.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1583198432859-635beb4e8600?w=800&h=1066&fit=crop&q=85",
    tags: ["technical", "precision", "vintage", "mechanical"],
    costText: "CHF 60\u2013200",
    timeText: "2h/week",
    difficultyText: "Hard",
    whyLove: "Opening a clock case is like archaeology\u2014gears, springs, and escapements reveal centuries of engineering elegance. Cleaning and reassembling a movement until it ticks again is one of the most satisfying repair experiences imaginable.",
    difficultyExplain: "Quartz movements are simple to swap. Mechanical movements require fine motor skills, specialised tools, and patience.",
    pitfalls: [
      "Letting the mainspring snap free during disassembly",
      "Using the wrong oil viscosity on pivot points",
      "Losing tiny screws\u2014always work over a parts tray"
    ],
    sortOrder: 14,
  },
  {
    id: "drone-building",
    title: "Drone Building",
    hook: "Assemble your own eye in the sky.",
    categoryId: "maker",
    imageUrl: "https://images.unsplash.com/photo-1508444845599-5c89863b1c44?w=600&h=800&fit=crop",
    tags: ["technical", "electronics", "aerial", "fpv"],
    costText: "CHF 150\u2013400",
    timeText: "4h/week",
    difficultyText: "Hard",
    whyLove: "Building a drone from frame to firmware merges electronics, programming, and aerodynamics into one exhilarating hobby. Your first successful hover is unforgettable, and FPV flying feels like a video game set in the real world.",
    difficultyExplain: "Soldering ESCs and configuring Betaflight require patience. Simulator practice before real flights prevents expensive crashes.",
    pitfalls: [
      "Skipping the simulator and crashing on the first real flight",
      "Mixing up motor rotation directions and flipping on takeoff",
      "Flying without checking local Swiss BAZL drone regulations"
    ],
    sortOrder: 15,
  },
];

// ─── Kit Items ───────────────────────────────────────────────

export const makerKitItems = [
  // Woodworking (5 items)
  {
    hobbyId: "woodworking",
    name: "Japanese pull saw",
    description: "Ryoba-style double-edge saw for cross and rip cuts. Clean, effortless cuts.",
    cost: 25,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=japanese+pull+saw+ryoba&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "woodworking",
    name: "Combination square",
    description: "12-inch combo square for marking 90\u00b0 and 45\u00b0 angles accurately.",
    cost: 20,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=combination+square+300mm&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "woodworking",
    name: "Wood chisels (set of 4)",
    description: "Bevel-edge chisels in 6, 12, 18, 25 mm. Essential for joinery.",
    cost: 35,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=wood+chisel+set+4+piece&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "woodworking",
    name: "Smoothing hand plane",
    description: "No. 4 bench plane for flattening and finishing surfaces.",
    cost: 45,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1616400619175-5beda3a17896?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=smoothing+hand+plane+no+4&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "woodworking",
    name: "Sharpening stone (1000/6000 grit)",
    description: "Dual-sided whetstone for keeping chisels and planes razor-sharp.",
    cost: 22,
    isOptional: true,
    sortOrder: 4,
    imageUrl: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sharpening+stone+1000+6000&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // 3D Printing (4 items)
  {
    hobbyId: "3d-printing",
    name: "FDM 3D printer (entry-level)",
    description: "Creality Ender 3 or similar \u2014 reliable, huge community, easy to mod.",
    cost: 200,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=creality+ender+3+3d+printer&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "3d-printing",
    name: "PLA filament (1 kg spool)",
    description: "Standard 1.75 mm PLA \u2014 easy to print, no heated enclosure needed.",
    cost: 20,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pla+filament+1.75mm+1kg&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "3d-printing",
    name: "Deburring tool kit",
    description: "Flush cutters, scrapers, and needle files for cleaning printed parts.",
    cost: 15,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=3d+print+deburring+tool+kit&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "3d-printing",
    name: "Digital caliper",
    description: "150 mm digital caliper for measuring tolerances and checking dimensions.",
    cost: 15,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1635405074683-96d6921a2a68?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=digital+caliper+150mm&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Electronics (4 items)
  {
    hobbyId: "electronics",
    name: "Arduino Uno starter kit",
    description: "Microcontroller board, breadboard, jumper wires, LEDs, resistors, and sensors.",
    cost: 35,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=arduino+uno+starter+kit&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "electronics",
    name: "Soldering iron station",
    description: "Temperature-controlled 60 W station with fine tip. Essential for permanent circuits.",
    cost: 40,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1588508065123-287b28e013da?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=soldering+iron+station+60w&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "electronics",
    name: "Digital multimeter",
    description: "Measures voltage, current, and resistance. Indispensable for debugging.",
    cost: 20,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1555664424-778a1e5e1b48?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=digital+multimeter&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "electronics",
    name: "Wire stripper and cutter",
    description: "Self-adjusting wire stripper for 0.2\u20136 mm\u00b2 wires.",
    cost: 12,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1590959651373-a3db0f38a961?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=wire+stripper+self+adjusting&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Leathercraft (4 items)
  {
    hobbyId: "leathercraft",
    name: "Vegetable-tanned leather (A4 sheets x3)",
    description: "2 mm thick veg-tan cowhide. Takes dye and tooling beautifully.",
    cost: 25,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1473188588951-5b5f4b511f63?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=vegetable+tanned+leather+sheet&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "leathercraft",
    name: "Rotary cutter + cutting mat",
    description: "45 mm rotary cutter and A3 self-healing mat for precise cuts.",
    cost: 20,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=rotary+cutter+cutting+mat+a3&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "leathercraft",
    name: "Stitching groover and pricking irons",
    description: "Groover for stitch lines, 4 mm pricking irons for even hole spacing.",
    cost: 18,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1605379399642-870262d3d051?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=leather+stitching+groover+pricking+iron&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "leathercraft",
    name: "Waxed thread and needles",
    description: "0.8 mm waxed polyester thread and blunt harness needles for saddle stitching.",
    cost: 10,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=waxed+leather+thread+needles&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Candle Making (4 items)
  {
    hobbyId: "candle-making",
    name: "Soy wax flakes (1 kg)",
    description: "Natural soy wax with excellent scent throw. Clean-burning and vegan.",
    cost: 12,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1602607937533-0ba85a47d277?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=soy+wax+flakes+candle+making&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "candle-making",
    name: "Fragrance oil set (6 scents)",
    description: "Candle-safe fragrance oils: vanilla, lavender, sandalwood, citrus, cinnamon, ocean.",
    cost: 18,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1599751449128-eb7249c3d6b1?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=candle+fragrance+oil+set&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "candle-making",
    name: "Cotton wicks (100 pcs) + centering tools",
    description: "Pre-tabbed cotton wicks with metal centering clips for even burns.",
    cost: 8,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1608181831718-2501c44c0e07?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=candle+cotton+wicks+centering+tool&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "candle-making",
    name: "Glass jars with lids (6 pcs)",
    description: "200 ml clear glass tumblers with bamboo lids. Reusable and giftable.",
    cost: 15,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=candle+glass+jars+lids+200ml&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Soap Making (4 items)
  {
    hobbyId: "soap-making",
    name: "Melt-and-pour soap base (1 kg)",
    description: "Glycerin-based soap base. No lye handling needed \u2014 microwave and pour.",
    cost: 12,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1607006344380-b6775a0824a7?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=melt+and+pour+soap+base&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "soap-making",
    name: "Silicone soap moulds (set of 2)",
    description: "6-cavity rectangular moulds. Flexible, easy release, dishwasher safe.",
    cost: 14,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=silicone+soap+mould+rectangular&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "soap-making",
    name: "Essential oil set (6 bottles)",
    description: "Lavender, tea tree, peppermint, eucalyptus, lemon, rosemary. Skin-safe.",
    cost: 18,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=essential+oil+set+soap+making&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "soap-making",
    name: "Mica powder colours (12 jars)",
    description: "Cosmetic-grade mica pigments for vibrant swirls and layers.",
    cost: 10,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=mica+powder+soap+making+set&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Metalworking (4 items)
  {
    hobbyId: "metalworking",
    name: "MIG welder (130 A)",
    description: "Gasless flux-core MIG welder. Runs on a standard 230 V outlet.",
    cost: 180,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=mig+welder+130a+gasless&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "metalworking",
    name: "Auto-darkening welding helmet",
    description: "Solar-powered auto-darkening helmet. Protects eyes from UV/IR flash.",
    cost: 40,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=auto+darkening+welding+helmet&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "metalworking",
    name: "Angle grinder (115 mm)",
    description: "Compact grinder for cutting, grinding, and deburring metal.",
    cost: 35,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1580901368919-7738efb0f87e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=angle+grinder+115mm&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "metalworking",
    name: "Welding gloves and apron",
    description: "Heat-resistant cowhide gloves and split-leather apron for splatter protection.",
    cost: 25,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1611117775350-ac3950990b70?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=welding+gloves+leather+apron&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Model Building (4 items)
  {
    hobbyId: "model-building",
    name: "Plastic model kit (1:48 aircraft)",
    description: "Tamiya or Revell beginner kit with clear instructions and snap-fit parts.",
    cost: 25,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=tamiya+model+kit+1+48+beginner&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "model-building",
    name: "Sprue cutters",
    description: "Flush-cut nippers for cleanly removing parts from the sprue.",
    cost: 10,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sprue+cutters+model+building&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "model-building",
    name: "Acrylic paint set (12 colours)",
    description: "Vallejo or Tamiya acrylics for brush and airbrush use.",
    cost: 22,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=vallejo+acrylic+paint+set+model&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "model-building",
    name: "Fine detail brush set",
    description: "Sable-hair brushes in 0, 1, and 2 sizes for cockpits and decals.",
    cost: 12,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fine+detail+paint+brush+model&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Bookbinding (4 items)
  {
    hobbyId: "bookbinding",
    name: "Bookbinding linen thread (waxed)",
    description: "Pre-waxed linen thread for strong, long-lasting stitches.",
    cost: 8,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=bookbinding+waxed+linen+thread&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "bookbinding",
    name: "Bone folder",
    description: "Smooth bone tool for scoring, folding, and creasing paper cleanly.",
    cost: 6,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1568667256549-094345857637?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=bone+folder+bookbinding&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "bookbinding",
    name: "Bookboard (greyboard A4 x10)",
    description: "2 mm greyboard sheets for hardcover book boards.",
    cost: 10,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=bookbinding+greyboard+2mm&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "bookbinding",
    name: "PVA bookbinding glue (250 ml)",
    description: "Acid-free, flexible PVA adhesive. Dries clear and stays supple.",
    cost: 8,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pva+bookbinding+glue&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Furniture Restoration (4 items)
  {
    hobbyId: "furniture-restoration",
    name: "Orbital sander",
    description: "Random-orbit sander with dust collection. Strips finish without gouging.",
    cost: 50,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=random+orbit+sander&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "furniture-restoration",
    name: "Sandpaper assortment (80\u2013400 grit)",
    description: "Hook-and-loop discs in 80, 120, 180, 240, and 400 grit.",
    cost: 12,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sandpaper+disc+assortment+orbital+sander&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "furniture-restoration",
    name: "Wood stain (walnut, 250 ml)",
    description: "Water-based walnut stain. Low odour, easy cleanup, rich colour.",
    cost: 14,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=wood+stain+walnut+water+based&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "furniture-restoration",
    name: "Paint stripper (gel, 500 ml)",
    description: "Low-VOC gel stripper for removing old paint and varnish safely.",
    cost: 16,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1616627547584-bf28cee262db?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=paint+stripper+gel+low+voc&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Knife Making (4 items)
  {
    hobbyId: "knife-making",
    name: "1095 carbon steel blank",
    description: "Pre-cut 1095 high-carbon steel bar, 4 mm thick. Great for stock-removal.",
    cost: 20,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1581783898377-1c85bf937427?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=1095+carbon+steel+knife+blank&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "knife-making",
    name: "Metal file set (3-piece)",
    description: "Flat, half-round, and round bastard files for profiling your blade.",
    cost: 18,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=metal+file+set+bastard+3+piece&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "knife-making",
    name: "Epoxy and handle scales (wood)",
    description: "2-part epoxy adhesive plus stabilised wood scales for the handle.",
    cost: 22,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1616400619175-5beda3a17896?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=knife+handle+scales+wood+epoxy&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "knife-making",
    name: "Sandpaper set (120\u20132000 grit)",
    description: "Wet/dry sandpaper for progressive blade finishing to a mirror polish.",
    cost: 10,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sandpaper+wet+dry+120+2000+grit&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Pottery Wheel (4 items)
  {
    hobbyId: "pottery-wheel",
    name: "Tabletop pottery wheel",
    description: "25 cm wheel head, variable speed. Compact enough for a kitchen table.",
    cost: 120,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=tabletop+pottery+wheel+25cm&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pottery-wheel",
    name: "Stoneware clay (10 kg)",
    description: "Mid-fire stoneware clay. Smooth, forgiving, food-safe after glazing.",
    cost: 18,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1603344204980-4edb0ea63148?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=stoneware+clay+10kg+pottery&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pottery-wheel",
    name: "Potter\u2019s tool set (8 pieces)",
    description: "Wire cutter, rib, needle tool, sponge, trimming tools. All essentials.",
    cost: 15,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1493106641515-6b5631de4bb9?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pottery+tool+set+8+piece&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "pottery-wheel",
    name: "Glaze set (6 colours, food-safe)",
    description: "Dipping glazes for mid-fire stoneware. Dishwasher and food safe.",
    cost: 35,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=pottery+glaze+set+food+safe&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Glassblowing (3 items)
  {
    hobbyId: "glassblowing",
    name: "Introductory workshop voucher",
    description: "Half-day hot-shop session with an instructor. Includes materials and kiln time.",
    cost: 120,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1543946602-a0fef17fc1be?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=glassblowing+workshop+voucher&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "glassblowing",
    name: "Safety glasses (IR-rated)",
    description: "Didymium lenses that filter sodium flare so you can see the glass shape.",
    cost: 45,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1574258495973-f7977603b4b2?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=didymium+safety+glasses+glassblowing&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "glassblowing",
    name: "Cotton clothing set",
    description: "100% cotton long-sleeve shirt and apron. Synthetic melts near heat.",
    cost: 30,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1611117775350-ac3950990b70?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cotton+workshop+apron+long+sleeve&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Loom Weaving (4 items)
  {
    hobbyId: "loom-weaving",
    name: "Rigid-heddle loom (40 cm)",
    description: "Compact tabletop loom with 40 cm weaving width. Includes heddle and shuttle.",
    cost: 80,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=rigid+heddle+loom+40cm&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "loom-weaving",
    name: "Cotton warp yarn (200 g cone)",
    description: "Strong, smooth 8/2 cotton yarn for sturdy warps.",
    cost: 12,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=cotton+warp+yarn+cone+weaving&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "loom-weaving",
    name: "Weft yarn assortment (5 colours)",
    description: "Soft wool/cotton blend weft yarns in complementary colours.",
    cost: 20,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1601379329542-31a252e32bc4?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=weaving+weft+yarn+assorted+colours&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "loom-weaving",
    name: "Tapestry needle set",
    description: "Large-eye blunt needles for weaving in ends and finishing edges.",
    cost: 5,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=tapestry+needle+set+weaving&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Clock Repair (4 items)
  {
    hobbyId: "clock-repair",
    name: "Watchmaker\u2019s screwdriver set",
    description: "Precision screwdrivers in 0.6\u20132.0 mm for tiny clock screws.",
    cost: 18,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1509048191080-d2984bad6ae5?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=watchmaker+screwdriver+set+precision&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "clock-repair",
    name: "Loupe (10x magnification)",
    description: "Clip-on or headband loupe for inspecting pivots and escapements.",
    cost: 15,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=watchmaker+loupe+10x+headband&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "clock-repair",
    name: "Clock oil and oiler set",
    description: "Synthetic clock oil with fine-tip oiler for pivot lubrication.",
    cost: 12,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=clock+oil+oiler+set+synthetic&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "clock-repair",
    name: "Parts tray and tweezers",
    description: "Magnetic parts tray and anti-magnetic tweezers to keep tiny screws safe.",
    cost: 10,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1590959651373-a3db0f38a961?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=magnetic+parts+tray+tweezers+precision&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // Drone Building (4 items)
  {
    hobbyId: "drone-building",
    name: "FPV drone frame kit (5-inch)",
    description: "Carbon fibre frame with hardware for a 5-inch freestyle quad.",
    cost: 35,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1508444845599-5c89863b1c44?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fpv+drone+frame+5+inch+carbon&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "drone-building",
    name: "Flight controller + ESC stack",
    description: "F4 flight controller with 4-in-1 ESC. Betaflight compatible.",
    cost: 55,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fpv+flight+controller+f4+esc+stack&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "drone-building",
    name: "Brushless motors (set of 4)",
    description: "2306 1700 KV motors for 5-inch props. Smooth, efficient, durable.",
    cost: 50,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fpv+brushless+motor+2306+set+4&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "drone-building",
    name: "FPV goggles (entry-level)",
    description: "Box-style FPV goggles with built-in receiver. See what your drone sees.",
    cost: 80,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1508444845599-5c89863b1c44?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fpv+goggles+entry+level+box&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
];

// ─── Roadmap Steps ───────────────────────────────────────────

export const makerRoadmapSteps = [
  // Woodworking
  { id: "woodworking-r1", hobbyId: "woodworking", title: "Learn safe hand-tool use", description: "Watch tutorials on saw, chisel, and plane technique. Practice on scrap wood.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "woodworking-r2", hobbyId: "woodworking", title: "Build a simple cutting board", description: "Glue up strips, plane flat, sand, and apply food-safe oil finish.", estimatedMinutes: 120, milestone: "First Finished Piece", sortOrder: 1 },
  { id: "woodworking-r3", hobbyId: "woodworking", title: "Master basic joinery", description: "Practice butt joints, dado joints, and pocket-hole screws.", estimatedMinutes: 90, milestone: null, sortOrder: 2 },
  { id: "woodworking-r4", hobbyId: "woodworking", title: "Build a small shelf", description: "Design, cut, and assemble a wall shelf using your joinery skills.", estimatedMinutes: 180, milestone: "Functional Furniture", sortOrder: 3 },
  { id: "woodworking-r5", hobbyId: "woodworking", title: "Add finishing techniques", description: "Experiment with stains, oils, and polyurethane on sample boards.", estimatedMinutes: 60, milestone: null, sortOrder: 4 },

  // 3D Printing
  { id: "3d-printing-r1", hobbyId: "3d-printing", title: "Assemble and calibrate your printer", description: "Build the printer, level the bed, and run a test cube.", estimatedMinutes: 120, milestone: null, sortOrder: 0 },
  { id: "3d-printing-r2", hobbyId: "3d-printing", title: "Print your first download", description: "Download a model from Thingiverse, slice it in Cura, and print.", estimatedMinutes: 60, milestone: "First Print", sortOrder: 1 },
  { id: "3d-printing-r3", hobbyId: "3d-printing", title: "Learn slicer settings", description: "Experiment with layer height, infill, supports, and print speed.", estimatedMinutes: 90, milestone: null, sortOrder: 2 },
  { id: "3d-printing-r4", hobbyId: "3d-printing", title: "Design a custom object", description: "Use TinkerCAD or Fusion 360 to model a phone stand or organiser.", estimatedMinutes: 120, milestone: "First Original Design", sortOrder: 3 },
  { id: "3d-printing-r5", hobbyId: "3d-printing", title: "Try a multi-part assembly", description: "Design and print interlocking parts that snap or screw together.", estimatedMinutes: 150, milestone: null, sortOrder: 4 },

  // Electronics
  { id: "electronics-r1", hobbyId: "electronics", title: "Blink an LED", description: "Wire an LED, resistor, and Arduino on a breadboard. Upload the Blink sketch.", estimatedMinutes: 30, milestone: "Hello World", sortOrder: 0 },
  { id: "electronics-r2", hobbyId: "electronics", title: "Read a sensor", description: "Connect a temperature or light sensor and print values to the serial monitor.", estimatedMinutes: 45, milestone: null, sortOrder: 1 },
  { id: "electronics-r3", hobbyId: "electronics", title: "Control a motor or servo", description: "Use PWM to drive a small servo and a DC motor with a transistor.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "electronics-r4", hobbyId: "electronics", title: "Build a useful gadget", description: "Combine sensors and outputs into a desk thermometer, plant monitor, or timer.", estimatedMinutes: 120, milestone: "First Gadget", sortOrder: 3 },
  { id: "electronics-r5", hobbyId: "electronics", title: "Solder a permanent board", description: "Transfer your breadboard prototype to a perfboard and solder all connections.", estimatedMinutes: 90, milestone: null, sortOrder: 4 },

  // Leathercraft
  { id: "leathercraft-r1", hobbyId: "leathercraft", title: "Cut and edge a leather piece", description: "Practice cutting straight lines and burnishing edges with a slicker.", estimatedMinutes: 45, milestone: null, sortOrder: 0 },
  { id: "leathercraft-r2", hobbyId: "leathercraft", title: "Saddle-stitch a card holder", description: "Mark stitch lines, punch holes, and hand-stitch a 2-pocket cardholder.", estimatedMinutes: 90, milestone: "First Leather Piece", sortOrder: 1 },
  { id: "leathercraft-r3", hobbyId: "leathercraft", title: "Dye and condition leather", description: "Apply dye evenly, let dry, and seal with leather conditioner.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "leathercraft-r4", hobbyId: "leathercraft", title: "Make a belt or key fob", description: "Cut a strap, set a buckle or snap, and finish edges.", estimatedMinutes: 120, milestone: "Wearable Craft", sortOrder: 3 },
  { id: "leathercraft-r5", hobbyId: "leathercraft", title: "Tooling and stamping", description: "Wet the leather and use stamps and a swivel knife for decorative patterns.", estimatedMinutes: 90, milestone: null, sortOrder: 4 },

  // Candle Making
  { id: "candle-making-r1", hobbyId: "candle-making", title: "Melt and pour your first candle", description: "Melt soy wax, add fragrance at the right temperature, pour into a jar.", estimatedMinutes: 45, milestone: "First Candle", sortOrder: 0 },
  { id: "candle-making-r2", hobbyId: "candle-making", title: "Test wick sizes", description: "Pour three candles with different wick sizes and burn-test each for 4 hours.", estimatedMinutes: 30, milestone: null, sortOrder: 1 },
  { id: "candle-making-r3", hobbyId: "candle-making", title: "Blend custom fragrances", description: "Combine 2\u20133 fragrance oils to create a signature scent.", estimatedMinutes: 45, milestone: "Signature Scent", sortOrder: 2 },
  { id: "candle-making-r4", hobbyId: "candle-making", title: "Add colour and texture", description: "Use dye chips and experiment with layered pours or embed dried flowers.", estimatedMinutes: 60, milestone: null, sortOrder: 3 },
  { id: "candle-making-r5", hobbyId: "candle-making", title: "Label and gift a set", description: "Design labels, package a 3-candle gift set for friends or family.", estimatedMinutes: 30, milestone: "Gift-Ready", sortOrder: 4 },

  // Soap Making
  { id: "soap-making-r1", hobbyId: "soap-making", title: "Melt-and-pour basics", description: "Cut soap base, melt, add colour and scent, pour into moulds.", estimatedMinutes: 30, milestone: "First Bar", sortOrder: 0 },
  { id: "soap-making-r2", hobbyId: "soap-making", title: "Create layered and swirl designs", description: "Pour at different temperatures to create distinct colour layers and swirls.", estimatedMinutes: 45, milestone: null, sortOrder: 1 },
  { id: "soap-making-r3", hobbyId: "soap-making", title: "Add exfoliants and botanicals", description: "Embed oatmeal, coffee grounds, or dried lavender buds.", estimatedMinutes: 30, milestone: null, sortOrder: 2 },
  { id: "soap-making-r4", hobbyId: "soap-making", title: "Try cold-process soap", description: "Mix oils, lye solution, and fragrance. Pour into a loaf mould and cure 4 weeks.", estimatedMinutes: 90, milestone: "Cold Process", sortOrder: 3 },
  { id: "soap-making-r5", hobbyId: "soap-making", title: "Package and share", description: "Wrap bars in wax paper, add labels, and gift or sell at a local market.", estimatedMinutes: 30, milestone: null, sortOrder: 4 },

  // Metalworking
  { id: "metalworking-r1", hobbyId: "metalworking", title: "Learn safety and setup", description: "Study workshop safety, set up ventilation, and practise striking with a hammer.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "metalworking-r2", hobbyId: "metalworking", title: "Run your first weld bead", description: "Set up the MIG welder and practise straight beads on scrap steel.", estimatedMinutes: 60, milestone: "First Weld", sortOrder: 1 },
  { id: "metalworking-r3", hobbyId: "metalworking", title: "Weld a simple bracket", description: "Cut two pieces of angle iron and weld them into an L-bracket.", estimatedMinutes: 90, milestone: null, sortOrder: 2 },
  { id: "metalworking-r4", hobbyId: "metalworking", title: "Grind and finish a project", description: "Grind welds smooth, sand, and apply rust-preventive primer.", estimatedMinutes: 60, milestone: null, sortOrder: 3 },
  { id: "metalworking-r5", hobbyId: "metalworking", title: "Build a functional piece", description: "Design and fabricate a towel rack, plant stand, or fire pit ring.", estimatedMinutes: 180, milestone: "First Fabrication", sortOrder: 4 },

  // Model Building
  { id: "model-building-r1", hobbyId: "model-building", title: "Unbox and organise parts", description: "Inspect sprues, read instructions, and organise parts by assembly step.", estimatedMinutes: 20, milestone: null, sortOrder: 0 },
  { id: "model-building-r2", hobbyId: "model-building", title: "Assemble the airframe or hull", description: "Cut parts from sprues, clean nubs, dry-fit, then glue major sections.", estimatedMinutes: 90, milestone: "Structure Complete", sortOrder: 1 },
  { id: "model-building-r3", hobbyId: "model-building", title: "Prime and base-coat", description: "Apply thin primer, then a base colour coat with a brush or rattle can.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "model-building-r4", hobbyId: "model-building", title: "Detail paint and decals", description: "Paint cockpit details, apply water-slide decals, and seal with varnish.", estimatedMinutes: 90, milestone: null, sortOrder: 3 },
  { id: "model-building-r5", hobbyId: "model-building", title: "Weathering and display", description: "Add washes, dry-brushing, and pigments. Mount on a display stand.", estimatedMinutes: 60, milestone: "Display Ready", sortOrder: 4 },

  // Bookbinding
  { id: "bookbinding-r1", hobbyId: "bookbinding", title: "Fold and nest signatures", description: "Cut paper to size, fold into folios, and nest into 4\u20135 sheet signatures.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "bookbinding-r2", hobbyId: "bookbinding", title: "Sew a pamphlet stitch booklet", description: "Pierce 3 holes and sew a simple pamphlet. Your first bound book.", estimatedMinutes: 30, milestone: "First Bound Book", sortOrder: 1 },
  { id: "bookbinding-r3", hobbyId: "bookbinding", title: "Multi-signature Coptic stitch", description: "Link multiple signatures with exposed Coptic chain stitch.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "bookbinding-r4", hobbyId: "bookbinding", title: "Case binding (hardcover)", description: "Make boards, glue spine, attach cover cloth, and case-in the text block.", estimatedMinutes: 120, milestone: "Hardcover Book", sortOrder: 3 },
  { id: "bookbinding-r5", hobbyId: "bookbinding", title: "Decorate and finish", description: "Add endpapers, ribbon markers, and a title label or foil stamp.", estimatedMinutes: 45, milestone: null, sortOrder: 4 },

  // Furniture Restoration
  { id: "furniture-restoration-r1", hobbyId: "furniture-restoration", title: "Assess and plan", description: "Inspect the piece for damage, test for lead paint, and plan your approach.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "furniture-restoration-r2", hobbyId: "furniture-restoration", title: "Strip old finish", description: "Apply stripper, scrape off old paint or varnish, and clean the surface.", estimatedMinutes: 90, milestone: null, sortOrder: 1 },
  { id: "furniture-restoration-r3", hobbyId: "furniture-restoration", title: "Sand progressively", description: "Sand from 80 grit to 240 grit, following the wood grain.", estimatedMinutes: 60, milestone: "Bare Wood", sortOrder: 2 },
  { id: "furniture-restoration-r4", hobbyId: "furniture-restoration", title: "Apply stain and topcoat", description: "Brush on stain, wipe excess, then apply 2\u20133 coats of polyurethane.", estimatedMinutes: 90, milestone: null, sortOrder: 3 },
  { id: "furniture-restoration-r5", hobbyId: "furniture-restoration", title: "Reassemble and enjoy", description: "Reattach hardware, tighten joints, and place your restored piece.", estimatedMinutes: 30, milestone: "Restored", sortOrder: 4 },

  // Knife Making
  { id: "knife-making-r1", hobbyId: "knife-making", title: "Design your blade profile", description: "Sketch the blade shape on paper and transfer to the steel blank with a marker.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "knife-making-r2", hobbyId: "knife-making", title: "Cut and file the profile", description: "Hacksaw the rough shape, then file to your line.", estimatedMinutes: 120, milestone: "Blade Profile", sortOrder: 1 },
  { id: "knife-making-r3", hobbyId: "knife-making", title: "Grind the bevel", description: "File or grind the cutting bevel at a consistent angle on both sides.", estimatedMinutes: 90, milestone: null, sortOrder: 2 },
  { id: "knife-making-r4", hobbyId: "knife-making", title: "Heat treat the blade", description: "Harden in oil quench, then temper in the oven at 200\u00b0C for 1 hour.", estimatedMinutes: 60, milestone: "Heat Treated", sortOrder: 3 },
  { id: "knife-making-r5", hobbyId: "knife-making", title: "Attach handle and sharpen", description: "Epoxy the scales, shape and sand, then sharpen to a working edge.", estimatedMinutes: 90, milestone: "Finished Knife", sortOrder: 4 },

  // Pottery Wheel
  { id: "pottery-wheel-r1", hobbyId: "pottery-wheel", title: "Wedge and centre clay", description: "Knead clay to remove air bubbles, then centre a ball on the spinning wheel.", estimatedMinutes: 45, milestone: null, sortOrder: 0 },
  { id: "pottery-wheel-r2", hobbyId: "pottery-wheel", title: "Throw a cylinder", description: "Open the centred clay and pull up walls into an even cylinder.", estimatedMinutes: 60, milestone: "First Cylinder", sortOrder: 1 },
  { id: "pottery-wheel-r3", hobbyId: "pottery-wheel", title: "Shape a bowl", description: "Open wider and shape a bowl with even walls and a foot ring.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "pottery-wheel-r4", hobbyId: "pottery-wheel", title: "Trim and dry", description: "Flip the leather-hard piece, trim the foot, and let dry slowly.", estimatedMinutes: 30, milestone: null, sortOrder: 3 },
  { id: "pottery-wheel-r5", hobbyId: "pottery-wheel", title: "Glaze and fire", description: "Apply glaze by dipping or brushing, then fire in a kiln.", estimatedMinutes: 45, milestone: "Finished Vessel", sortOrder: 4 },

  // Glassblowing
  { id: "glassblowing-r1", hobbyId: "glassblowing", title: "Safety orientation", description: "Learn shop rules, heat zones, and safe movement around furnaces.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "glassblowing-r2", hobbyId: "glassblowing", title: "Gather and shape a paperweight", description: "Gather molten glass on the pipe, shape with blocks and jacks.", estimatedMinutes: 60, milestone: "First Gather", sortOrder: 1 },
  { id: "glassblowing-r3", hobbyId: "glassblowing", title: "Blow a small bubble", description: "Inflate a small bubble inside the gather and shape it round.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "glassblowing-r4", hobbyId: "glassblowing", title: "Make a cup or ornament", description: "Combine gathering, blowing, and shaping into a functional piece.", estimatedMinutes: 90, milestone: "First Blown Piece", sortOrder: 3 },
  { id: "glassblowing-r5", hobbyId: "glassblowing", title: "Add colour and pattern", description: "Pick up colour frits or cane and roll into the gather before blowing.", estimatedMinutes: 90, milestone: null, sortOrder: 4 },

  // Loom Weaving
  { id: "loom-weaving-r1", hobbyId: "loom-weaving", title: "Warp the loom", description: "Measure, thread, and tension the warp on your rigid-heddle loom.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "loom-weaving-r2", hobbyId: "loom-weaving", title: "Weave plain tabby", description: "Pass the shuttle back and forth to create a simple over-under weave.", estimatedMinutes: 45, milestone: "First Fabric", sortOrder: 1 },
  { id: "loom-weaving-r3", hobbyId: "loom-weaving", title: "Add colour stripes", description: "Change weft colours to create horizontal stripe patterns.", estimatedMinutes: 45, milestone: null, sortOrder: 2 },
  { id: "loom-weaving-r4", hobbyId: "loom-weaving", title: "Finish and hem a scarf", description: "Cut off the loom, tie fringe or hem, and wash to full the fabric.", estimatedMinutes: 30, milestone: "First Scarf", sortOrder: 3 },
  { id: "loom-weaving-r5", hobbyId: "loom-weaving", title: "Explore twill patterns", description: "Use a pick-up stick to create diagonal twill patterns.", estimatedMinutes: 60, milestone: null, sortOrder: 4 },

  // Clock Repair
  { id: "clock-repair-r1", hobbyId: "clock-repair", title: "Study clock anatomy", description: "Learn the names and functions of gears, springs, escapement, and hands.", estimatedMinutes: 45, milestone: null, sortOrder: 0 },
  { id: "clock-repair-r2", hobbyId: "clock-repair", title: "Replace a quartz movement", description: "Remove the old quartz unit, measure the shaft, and install a new one.", estimatedMinutes: 30, milestone: "First Repair", sortOrder: 1 },
  { id: "clock-repair-r3", hobbyId: "clock-repair", title: "Disassemble a mechanical movement", description: "Carefully remove the mainspring, gear train, and escapement. Photograph each step.", estimatedMinutes: 60, milestone: null, sortOrder: 2 },
  { id: "clock-repair-r4", hobbyId: "clock-repair", title: "Clean and oil the movement", description: "Ultrasonic-clean or hand-clean parts, then oil each pivot point.", estimatedMinutes: 90, milestone: "Movement Serviced", sortOrder: 3 },
  { id: "clock-repair-r5", hobbyId: "clock-repair", title: "Reassemble and regulate", description: "Put everything back together, hang the pendulum, and adjust the beat.", estimatedMinutes: 60, milestone: null, sortOrder: 4 },

  // Drone Building
  { id: "drone-building-r1", hobbyId: "drone-building", title: "Practise on a simulator", description: "Install Liftoff or VelociDrone and log 5+ hours of sim time.", estimatedMinutes: 300, milestone: null, sortOrder: 0 },
  { id: "drone-building-r2", hobbyId: "drone-building", title: "Solder the electronics stack", description: "Solder ESC, flight controller, and motor wires. Double-check polarity.", estimatedMinutes: 120, milestone: "Stack Built", sortOrder: 1 },
  { id: "drone-building-r3", hobbyId: "drone-building", title: "Assemble the frame", description: "Mount motors, install the stack, route wires, and attach the camera.", estimatedMinutes: 90, milestone: null, sortOrder: 2 },
  { id: "drone-building-r4", hobbyId: "drone-building", title: "Flash firmware and configure", description: "Flash Betaflight, set up receiver, calibrate gyro and accelerometer.", estimatedMinutes: 60, milestone: "Flight Ready", sortOrder: 3 },
  { id: "drone-building-r5", hobbyId: "drone-building", title: "First hover and tune", description: "Maiden hover in a safe open field. Adjust PID rates for smooth flight.", estimatedMinutes: 60, milestone: "First Flight", sortOrder: 4 },
];

// ─── FAQ Items (2-3 per hobby, first 8 hobbies) ─────────────

export const makerFaqItems = [
  // Woodworking
  { hobbyId: "woodworking", question: "Do I need a garage or workshop?", answer: "Not at the start. Hand tools are quiet enough for a balcony or spare room. A sturdy table and a clamp-on vice are enough for small projects." },
  { hobbyId: "woodworking", question: "Hand tools or power tools first?", answer: "Start with hand tools. They teach you how wood behaves\u2014grain, hardness, moisture\u2014before power tools speed everything up." },
  { hobbyId: "woodworking", question: "What wood should a beginner use?", answer: "Pine and poplar are affordable, easy to work, and widely available. Move to hardwoods like oak or walnut once you are comfortable." },

  // 3D Printing
  { hobbyId: "3d-printing", question: "Is a 3D printer hard to set up?", answer: "Most entry-level printers ship partially assembled and take 30\u201360 minutes to set up. Bed levelling is the trickiest part but well-documented online." },
  { hobbyId: "3d-printing", question: "Is PLA safe to print indoors?", answer: "PLA is made from corn starch and produces minimal fumes. A ventilated room is still recommended, but no special filtration is needed." },

  // Electronics
  { hobbyId: "electronics", question: "Do I need to know programming?", answer: "Arduino sketches are simple C/C++ and thousands of copy-paste examples exist. You will learn as you go\u2014no prior coding experience needed." },
  { hobbyId: "electronics", question: "Can I electrocute myself?", answer: "Arduino runs on 5 V which is completely safe. Avoid mains-voltage projects until you have solid experience. Always unplug before rewiring." },

  // Leathercraft
  { hobbyId: "leathercraft", question: "Where do I buy leather in Switzerland?", answer: "Online shops like Lederhaus.ch or Amazon.de carry veg-tan hides. Locally, ask tanneries in the Emmental region for offcuts." },
  { hobbyId: "leathercraft", question: "Is leathercraft smelly?", answer: "Vegetable-tanned leather has a mild, pleasant smell. Dyes and finishes have some odour but dissipate quickly in a ventilated room." },

  // Candle Making
  { hobbyId: "candle-making", question: "Is soy wax better than paraffin?", answer: "Soy burns cleaner and slower, and it holds fragrance well. Paraffin gives a stronger hot throw but produces more soot. Most beginners prefer soy." },
  { hobbyId: "candle-making", question: "Why does my candle tunnel?", answer: "The wick is too small for the jar diameter. Size up one wick and always burn until the melt pool reaches the edges on the first burn." },
  { hobbyId: "candle-making", question: "How long until my candle is ready to burn?", answer: "Let soy candles cure for 1\u20132 weeks after pouring. This lets the fragrance bind fully to the wax for a stronger scent throw." },

  // Soap Making
  { hobbyId: "soap-making", question: "Is lye dangerous?", answer: "Lye (sodium hydroxide) is caustic and must be handled with gloves and goggles. Once saponification is complete, the finished soap contains no free lye and is perfectly safe." },
  { hobbyId: "soap-making", question: "How long does cold-process soap take to cure?", answer: "Four to six weeks. The bars need time for water to evaporate, which makes them harder, longer-lasting, and milder on skin." },

  // Metalworking
  { hobbyId: "metalworking", question: "Can I weld in an apartment?", answer: "Welding produces UV light, sparks, and fumes\u2014it needs a garage or outdoor space. A makerspace with welding bays is the best option for apartment dwellers." },
  { hobbyId: "metalworking", question: "MIG, TIG, or stick welding for beginners?", answer: "MIG (wire feed) is the easiest to learn. It is forgiving, fast, and handles most mild steel projects. TIG gives cleaner welds but has a steeper learning curve." },

  // Model Building
  { hobbyId: "model-building", question: "What scale should I start with?", answer: "1:48 or 1:72 for aircraft, 1:35 for vehicles. These scales have the widest kit selection and parts that are not too small to handle." },
  { hobbyId: "model-building", question: "Do I need an airbrush?", answer: "Not at first. Rattle cans and fine brushes produce great results. An airbrush is a worthwhile upgrade once you want smoother gradients." },
];

// ─── Cost Breakdowns (1 per hobby) ───────────────────────────

export const makerCostBreakdowns = [
  {
    hobbyId: "woodworking",
    starter: 150,
    threeMonth: 250,
    oneYear: 500,
    tips: ["Buy used hand planes on local classifieds", "Reclaim pallet wood for practice projects", "Share workshop space with a friend to split rent"],
  },
  {
    hobbyId: "3d-printing",
    starter: 250,
    threeMonth: 300,
    oneYear: 450,
    tips: ["A single 1 kg spool prints dozens of small objects", "Download free models before investing in CAD software", "Buy filament in bulk during Black Friday sales"],
  },
  {
    hobbyId: "electronics",
    starter: 110,
    threeMonth: 150,
    oneYear: 250,
    tips: ["Arduino clones cost a fraction of official boards", "Salvage components from old electronics", "Aliexpress sensor packs are 80% cheaper than local shops"],
  },
  {
    hobbyId: "leathercraft",
    starter: 75,
    threeMonth: 120,
    oneYear: 220,
    tips: ["Buy offcuts and remnants instead of full hides", "A stitching pony can be DIYed from scrap wood", "Vegetable-tanned leather from tannery seconds saves 40%"],
  },
  {
    hobbyId: "candle-making",
    starter: 55,
    threeMonth: 80,
    oneYear: 150,
    tips: ["Buy wax in 5 kg bulk bags for 30% savings", "Reuse glass jars from jam and pasta sauce", "Fragrance oil sampler packs let you test before committing"],
  },
  {
    hobbyId: "soap-making",
    starter: 55,
    threeMonth: 80,
    oneYear: 140,
    tips: ["Melt-and-pour base is cheaper in 5 kg blocks", "Essential oils double as aromatherapy supplies", "Sell bars at local markets to offset material costs"],
  },
  {
    hobbyId: "metalworking",
    starter: 280,
    threeMonth: 350,
    oneYear: 550,
    tips: ["Makerspace memberships give tool access for CHF 50\u2013100/month", "Scrap metal yards sell practice steel by the kilo", "Buy a used welder\u2014they are nearly indestructible"],
  },
  {
    hobbyId: "model-building",
    starter: 70,
    threeMonth: 120,
    oneYear: 250,
    tips: ["Revell and Airfix kits are budget-friendly", "Tamiya spray cans are cheaper than an airbrush setup", "Join a club to share paints and decals"],
  },
  {
    hobbyId: "bookbinding",
    starter: 35,
    threeMonth: 60,
    oneYear: 120,
    tips: ["Printer paper works for practice signatures", "Fabric scraps from a textile shop make great cover cloth", "PVA glue is cheaper in 1-litre bottles from art suppliers"],
  },
  {
    hobbyId: "furniture-restoration",
    starter: 95,
    threeMonth: 140,
    oneYear: 250,
    tips: ["Source furniture for free on local buy-nothing groups", "Generic sandpaper discs cost half the brand-name price", "One can of stain covers 4\u20136 small pieces"],
  },
  {
    hobbyId: "knife-making",
    starter: 70,
    threeMonth: 120,
    oneYear: 250,
    tips: ["Old files make excellent blade steel for free", "A charcoal forge can be built from brake drums for under CHF 30", "Share a belt grinder with a fellow maker"],
  },
  {
    hobbyId: "pottery-wheel",
    starter: 190,
    threeMonth: 250,
    oneYear: 400,
    tips: ["Community studio memberships include kiln access", "Reclaim clay from failed pieces by rehydrating and wedging", "Buy glaze in powder form and mix your own\u201450% cheaper"],
  },
  {
    hobbyId: "glassblowing",
    starter: 170,
    threeMonth: 350,
    oneYear: 800,
    tips: ["Workshop packages often include 4 sessions at a bulk discount", "Lampwork (torch) at home costs a fraction of hot-shop time", "Share studio time with another student to halve costs"],
  },
  {
    hobbyId: "loom-weaving",
    starter: 120,
    threeMonth: 160,
    oneYear: 280,
    tips: ["Rigid-heddle looms hold their value well on the second-hand market", "Yarn mill ends and cones are 60% cheaper than retail skeins", "Weave dish towels as gifts\u2014practical and inexpensive"],
  },
  {
    hobbyId: "clock-repair",
    starter: 55,
    threeMonth: 90,
    oneYear: 180,
    tips: ["Flea markets and estate sales are goldmines for practice clocks", "Quartz movements cost under CHF 5 each in bulk", "Watch YouTube teardowns before touching a real movement"],
  },
  {
    hobbyId: "drone-building",
    starter: 220,
    threeMonth: 350,
    oneYear: 600,
    tips: ["Simulator time prevents expensive real-world crashes", "Buy motors and ESCs as a bundle for 20% savings", "3D-print replacement parts like camera mounts and antenna holders"],
  },
];
