// =============================================================================
// Outdoors Category — 18 Hobbies Seed Data
// All prices in CHF (Swiss Francs)
// =============================================================================

export const outdoorsHobbies = [
  {
    id: "hiking",
    title: "Hiking",
    hook: "Step outside. The trail is calling.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "relaxing", "solo"],
    costText: "CHF 0–150",
    timeText: "4h/week",
    difficultyText: "Easy",
    whyLove: "There's nothing quite like reaching a viewpoint you earned with your own two feet. Hiking clears your head, strengthens your body, and gives you stories that don't involve a screen. Every trail is different — and the Swiss ones are spectacular.",
    difficultyExplain: "Most trails are well-marked and graded by difficulty. Start with flat valley paths and work up to steeper terrain.",
    pitfalls: [
      "Wearing brand-new boots on a long hike without breaking them in first",
      "Underestimating water needs — carry at least 1L per 2 hours",
      "Skipping weather checks before heading out in the Alps"
    ],
    sortOrder: 0,
  },
  {
    id: "birdwatching",
    title: "Birdwatching",
    hook: "Slow down. Look up. A whole world appears.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1621631187532-d4b9e6b5e5e2?w=600&h=800&fit=crop",
    tags: ["relaxing", "outdoors", "solo", "meditative"],
    costText: "CHF 50–200",
    timeText: "3h/week",
    difficultyText: "Easy",
    whyLove: "Birdwatching teaches patience and presence. You start noticing things you've walked past a thousand times — a goldfinch in the hedge, a buzzard riding thermals overhead. It's meditation with a purpose, and each new species spotted is a tiny thrill.",
    difficultyExplain: "No physical demands beyond walking. The learning curve is in identification, which builds naturally over time.",
    pitfalls: [
      "Buying cheap binoculars with poor optics — spend a little more for 8x42 or 10x42",
      "Wearing bright colours that scare birds away before you spot them",
      "Trying to identify birds only by colour instead of learning shape and behaviour"
    ],
    sortOrder: 1,
  },
  {
    id: "kayaking",
    title: "Kayaking",
    hook: "Glide across glass-still water at sunrise.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1472745433479-4556f22e32c2?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "relaxing"],
    costText: "CHF 40–600",
    timeText: "3h/week",
    difficultyText: "Moderate",
    whyLove: "Kayaking gives you access to places you can't reach on foot — quiet coves, riverbanks, the middle of a Swiss lake at dawn. It's a full-body workout that doesn't feel like one, and the rhythm of paddling becomes deeply meditative.",
    difficultyExplain: "Flatwater kayaking is beginner-friendly. Rivers and open water require technique and safety knowledge.",
    pitfalls: [
      "Skipping a proper paddle technique lesson and developing shoulder strain",
      "Forgetting to check wind forecasts on lakes — headwinds can exhaust you fast",
      "Not wearing a life jacket on calm water because it 'seems safe'"
    ],
    sortOrder: 2,
  },
  {
    id: "gardening",
    title: "Gardening",
    hook: "Plant something today. Watch it grow tomorrow.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=800&fit=crop",
    tags: ["relaxing", "outdoors", "meditative", "creative"],
    costText: "CHF 30–150",
    timeText: "4h/week",
    difficultyText: "Easy",
    whyLove: "Gardening connects you to the oldest human activity. Watching a seed you planted become a tomato you eat is profoundly satisfying. It teaches patience, rewards consistency, and gives you an excuse to get your hands dirty every single day.",
    difficultyExplain: "Start with hardy herbs and salad greens. Even a balcony pot garden counts. No experience needed.",
    pitfalls: [
      "Overwatering seedlings — more plants die from drowning than drought",
      "Planting too many varieties at once instead of mastering a few",
      "Ignoring your local climate zone when choosing what to grow"
    ],
    sortOrder: 3,
  },
  {
    id: "stargazing",
    title: "Stargazing",
    hook: "The universe is right there. Just look up.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&h=800&fit=crop",
    tags: ["relaxing", "outdoors", "meditative", "solo"],
    costText: "CHF 0–300",
    timeText: "2h/week",
    difficultyText: "Easy",
    whyLove: "Stargazing puts everything in perspective — literally. Learning the constellations is like getting the cheat codes for the night sky. When you first see Saturn's rings through a telescope, or catch a meteor shower from a dark Swiss mountain pass, it rewires something in your brain.",
    difficultyExplain: "You can start with just your eyes and a free star chart app. Telescopes add complexity but aren't required.",
    pitfalls: [
      "Trying to stargaze from a city with heavy light pollution",
      "Buying a cheap department-store telescope with flimsy mount — save up or use binoculars",
      "Not giving your eyes 20+ minutes to adapt to the dark"
    ],
    sortOrder: 4,
  },
  {
    id: "geocaching",
    title: "Geocaching",
    hook: "Real treasure hunts. Millions of them. Worldwide.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&h=800&fit=crop",
    tags: ["outdoors", "physical", "social"],
    costText: "CHF 0–30",
    timeText: "3h/week",
    difficultyText: "Easy",
    whyLove: "Geocaching turns every walk into an adventure. There are hidden caches everywhere — in your neighbourhood, along hiking trails, even in city centres. The thrill of finding a cleverly hidden container never gets old, and it takes you to places you'd never otherwise discover.",
    difficultyExplain: "Download the free app, follow GPS coordinates, find the container. That's it. Some puzzle caches are harder.",
    pitfalls: [
      "Looking only at the GPS and not your surroundings — caches are hidden cleverly",
      "Forgetting to bring a pen to sign the logbook",
      "Getting discouraged after your first DNF (Did Not Find) — even veterans miss caches"
    ],
    sortOrder: 5,
  },
  {
    id: "trail-running",
    title: "Trail Running",
    hook: "Forget the treadmill. The forest floor awaits.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "solo"],
    costText: "CHF 100–250",
    timeText: "4h/week",
    difficultyText: "Moderate",
    whyLove: "Trail running combines the runner's high with the beauty of nature. Every root, rock, and incline demands your attention — there's no zoning out, which is exactly the point. You'll discover fitness you didn't know you had and trails you never knew existed.",
    difficultyExplain: "Requires baseline running fitness. Technical terrain and elevation make it harder than road running.",
    pitfalls: [
      "Starting on technical rocky trails instead of smooth forest paths",
      "Running downhill too fast and wrecking your knees",
      "Not carrying enough water or food for longer runs in remote areas"
    ],
    sortOrder: 6,
  },
  {
    id: "rock-climbing",
    title: "Rock Climbing",
    hook: "Solve vertical puzzles with your whole body.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "technical", "social"],
    costText: "CHF 80–400",
    timeText: "4h/week",
    difficultyText: "Moderate",
    whyLove: "Climbing is chess played with your body. Every route is a puzzle — where to place your feet, when to commit, how to rest. The sense of achievement when you top out a route that scared you is unmatched. The community is warm, supportive, and addictive.",
    difficultyExplain: "Indoor bouldering is beginner-friendly. Outdoor climbing and lead climbing require instruction and gear knowledge.",
    pitfalls: [
      "Over-gripping holds and burning out your forearms in minutes",
      "Neglecting footwork — climbing is 70% legs, not arms",
      "Skipping warm-ups and straining finger tendons (a slow-healing injury)"
    ],
    sortOrder: 7,
  },
  {
    id: "surfing",
    title: "Surfing",
    hook: "Catch one wave and you'll chase them forever.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1502680390548-bdbac40cef78?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "social"],
    costText: "CHF 100–500",
    timeText: "4h/week",
    difficultyText: "Hard",
    whyLove: "Surfing is pure, unfiltered joy. The feeling of catching a wave — even a small one — is unlike anything else. It humbles you, teaches patience, and connects you to the ocean's rhythm. Plus, the surf community worldwide is one of the most welcoming you'll find.",
    difficultyExplain: "Paddling out is exhausting. Standing up takes practice. Reading waves takes experience. Allow 10+ sessions before it clicks.",
    pitfalls: [
      "Starting on a short board instead of a big foam longboard",
      "Surfing alone at an unfamiliar beach without checking conditions",
      "Getting frustrated after session 3 — the pop-up takes most people 5-10 sessions to nail"
    ],
    sortOrder: 8,
  },
  {
    id: "camping",
    title: "Camping",
    hook: "Sleep under stars. Wake with the birds.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&h=800&fit=crop",
    tags: ["outdoors", "relaxing", "social"],
    costText: "CHF 100–400",
    timeText: "Weekend trips",
    difficultyText: "Easy",
    whyLove: "Camping strips life back to essentials — shelter, food, warmth, good company. A night under canvas resets your brain in ways no app can. Cooking over a fire, falling asleep to crickets, waking to mist on a lake — these memories outlast any holiday resort.",
    difficultyExplain: "Car camping is straightforward. Wild camping and winter camping require more knowledge and gear.",
    pitfalls: [
      "Not practising tent setup at home and struggling in the dark at the campsite",
      "Packing too much — you need less than you think",
      "Forgetting a sleeping pad and freezing on cold ground despite a warm sleeping bag"
    ],
    sortOrder: 9,
  },
  {
    id: "fishing",
    title: "Fishing",
    hook: "Patience on a line. Peace on the shore.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1532015421997-7bf740e0dcca?w=600&h=800&fit=crop",
    tags: ["relaxing", "outdoors", "solo", "meditative"],
    costText: "CHF 80–300",
    timeText: "4h/week",
    difficultyText: "Moderate",
    whyLove: "Fishing is the world's best excuse to sit by water and think about nothing. But beneath that calm surface is deep skill — reading water, choosing lures, playing a fish. The tug on the line sends a jolt of adrenaline every single time, whether it's your first catch or your hundredth.",
    difficultyExplain: "Basic float fishing is easy. Fly fishing and targeting specific species require technique and local knowledge.",
    pitfalls: [
      "Not getting a Swiss fishing licence (SaNa) before heading out — it's legally required",
      "Using the wrong bait or lure for the target species and lake type",
      "Tangling your line repeatedly because you didn't learn to cast properly first"
    ],
    sortOrder: 10,
  },
  {
    id: "mountain-biking",
    title: "Mountain Biking",
    hook: "Dirt trails, fresh air, pure adrenaline.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "competitive"],
    costText: "CHF 300–1500",
    timeText: "4h/week",
    difficultyText: "Moderate",
    whyLove: "Mountain biking is freedom on two wheels. You climb through forests, descend singletrack, and cover ground you'd never see on foot. The flow state on a good descent is addictive. Switzerland's trail network is world-class, and every ride ends with a new favourite route.",
    difficultyExplain: "Requires balance and fitness. Technical descents need practice, but fire roads and flow trails are beginner-accessible.",
    pitfalls: [
      "Buying too much bike too soon — rent first to find your style",
      "Riding trails above your skill level and panicking on steep descents",
      "Neglecting bike maintenance — a squealing brake or flat tyre ruins a ride"
    ],
    sortOrder: 11,
  },
  {
    id: "foraging",
    title: "Foraging",
    hook: "Your dinner is growing wild. Go find it.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1504387828636-abeb50778c0c?w=600&h=800&fit=crop",
    tags: ["outdoors", "relaxing", "solo", "meditative"],
    costText: "CHF 20–80",
    timeText: "3h/week",
    difficultyText: "Moderate",
    whyLove: "Foraging reconnects you to the landscape in the most primal way — you learn to see food everywhere. Wild garlic in spring, chanterelles in summer, chestnuts in autumn. Cooking with ingredients you found yourself is deeply satisfying, and it makes every walk feel like a treasure hunt.",
    difficultyExplain: "Safe foraging requires confident plant identification. Start with unmistakable species and join a guided walk first.",
    pitfalls: [
      "Eating anything you're not 100% certain about — some toxic plants look like edible ones",
      "Over-harvesting from one spot instead of taking small amounts across a wider area",
      "Foraging in protected areas or private land without permission"
    ],
    sortOrder: 12,
  },
  {
    id: "nature-photography",
    title: "Nature Photography",
    hook: "Frame the wild. Share what others miss.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=800&fit=crop",
    tags: ["creative", "outdoors", "solo", "meditative"],
    costText: "CHF 0–800",
    timeText: "4h/week",
    difficultyText: "Moderate",
    whyLove: "Nature photography sharpens your eye for beauty in everything — light through leaves, a fox at dusk, morning frost on a spider web. It gives purpose to every outdoor outing and creates a visual diary of the natural world you inhabit. Your phone is enough to start.",
    difficultyExplain: "Anyone can start with a phone camera. Mastering composition, light, and wildlife behaviour takes dedicated practice.",
    pitfalls: [
      "Buying expensive gear before learning composition basics with your phone",
      "Only shooting in bright midday sun — golden hour (dawn/dusk) is where the magic is",
      "Disturbing wildlife to get closer instead of using patience and a longer lens"
    ],
    sortOrder: 13,
  },
  {
    id: "sailing",
    title: "Sailing",
    hook: "Harness the wind. Go anywhere it blows.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1500930287596-c1ecaa210571?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "technical", "social"],
    costText: "CHF 200–800",
    timeText: "4h/week",
    difficultyText: "Hard",
    whyLove: "Sailing is the closest thing to flying while staying on earth. You read the wind, trim the sails, and feel the boat respond — no engine, no fuel, just physics and skill. Swiss lakes are ideal for learning, and the international sailing community opens doors worldwide.",
    difficultyExplain: "Requires understanding wind, right-of-way rules, and boat handling. A course is strongly recommended before solo sailing.",
    pitfalls: [
      "Skipping a certified sailing course and trying to learn by YouTube alone",
      "Underestimating how quickly weather changes on Swiss lakes",
      "Forgetting that capsizing is normal when learning — dress for immersion"
    ],
    sortOrder: 14,
  },
  {
    id: "skiing",
    title: "Skiing",
    hook: "Cold air, warm thighs, pure mountain bliss.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "social", "competitive"],
    costText: "CHF 200–600",
    timeText: "Full day trips",
    difficultyText: "Moderate",
    whyLove: "Skiing is Switzerland's national pastime for good reason. The sensation of carving turns on fresh snow, the crisp mountain air, the après-ski camaraderie — it's a full sensory experience. Once you link your first turns, you'll understand why people plan entire winters around it.",
    difficultyExplain: "Group lessons get most beginners on blue runs in 2-3 days. Steeper terrain and off-piste require progressive skill building.",
    pitfalls: [
      "Skipping lessons to 'figure it out' and developing bad habits that are hard to fix",
      "Renting poorly fitted boots — spend extra time getting the right boot size",
      "Skiing when exhausted in the afternoon, when most injuries happen"
    ],
    sortOrder: 15,
  },
  {
    id: "horseback-riding",
    title: "Horseback Riding",
    hook: "Two heartbeats. One trail. Total trust.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "social"],
    costText: "CHF 50–120/lesson",
    timeText: "2h/week",
    difficultyText: "Moderate",
    whyLove: "Riding a horse is a conversation without words. You learn to communicate through your seat, hands, and legs — and the horse responds. It builds core strength, confidence, and an extraordinary bond with an animal. Trail rides through Swiss countryside are unforgettable.",
    difficultyExplain: "Walking and basic trotting come quickly. Cantering, jumping, and independent riding take months of consistent lessons.",
    pitfalls: [
      "Tensing up and gripping with your knees instead of sitting deep and relaxed",
      "Approaching horses from behind without warning — always approach from the front/side",
      "Wearing trainers instead of boots with a heel that prevents your foot slipping through the stirrup"
    ],
    sortOrder: 16,
  },
  {
    id: "beach-volleyball",
    title: "Beach Volleyball",
    hook: "Sand, sun, and spikes. Summer in a sport.",
    categoryId: "outdoors",
    imageUrl: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=600&h=800&fit=crop",
    tags: ["physical", "outdoors", "social", "competitive"],
    costText: "CHF 20–60",
    timeText: "3h/week",
    difficultyText: "Moderate",
    whyLove: "Beach volleyball is the most social sport you'll find. Two-on-two means you're always involved, and playing on sand makes every rally feel playful, not pressured. City beach bars across Switzerland run open play nights — show up alone, leave with friends.",
    difficultyExplain: "Basic rallying is easy. Consistent serving, setting, and spiking in sand (which saps your legs) takes regular practice.",
    pitfalls: [
      "Playing without sunscreen and getting burned during a long session",
      "Jumping and landing wrong on soft sand — warm up your ankles first",
      "Trying to spike on every hit instead of placing the ball strategically"
    ],
    sortOrder: 17,
  },
];

// =============================================================================
// Kit Items — 3-5 per hobby
// =============================================================================

export const outdoorsKitItems = [
  // --- Hiking ---
  {
    hobbyId: "hiking",
    name: "Trail hiking shoes",
    description: "Good grip and ankle support for varied terrain.",
    cost: 120,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=hiking+trail+shoes&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "hiking",
    name: "Daypack (20-30L)",
    description: "Comfortable backpack with hip belt and water bladder sleeve.",
    cost: 60,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=hiking+daypack+30L&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "hiking",
    name: "Water bottle (1L)",
    description: "Insulated stainless steel keeps drinks cold or hot for hours.",
    cost: 25,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=insulated+water+bottle+1L&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "hiking",
    name: "Trekking poles",
    description: "Reduce knee impact on descents. Collapsible for easy packing.",
    cost: 45,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=trekking+poles+collapsible&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Birdwatching ---
  {
    hobbyId: "birdwatching",
    name: "Binoculars (8x42)",
    description: "Bright optics with wide field of view. The single most important purchase.",
    cost: 150,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1502982899975-893c9cf39028?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=binoculars+8x42+birdwatching&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "birdwatching",
    name: "Field guide book",
    description: "Regional bird identification guide with illustrations and range maps.",
    cost: 30,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=bird+identification+guide+europe&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "birdwatching",
    name: "Notebook and pencil",
    description: "Waterproof field notebook for logging sightings and sketches.",
    cost: 12,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=waterproof+field+notebook&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Kayaking ---
  {
    hobbyId: "kayaking",
    name: "Kayak rental (first sessions)",
    description: "Rent before you buy. Most Swiss lakes have hourly rentals.",
    cost: 40,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1472745433479-4556f22e32c2?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=inflatable+kayak+beginner&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "kayaking",
    name: "Life jacket (PFD)",
    description: "Always wear one. Fits comfortably over any clothing.",
    cost: 60,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1564415051543-cb73a0109032?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=kayak+life+jacket+PFD&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "kayaking",
    name: "Dry bag (10L)",
    description: "Keeps phone, keys, and snacks safe from splashes.",
    cost: 20,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=dry+bag+10L+waterproof&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "kayaking",
    name: "Paddle leash",
    description: "Attaches paddle to kayak so you never lose it if you capsize.",
    cost: 15,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=kayak+paddle+leash&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Gardening ---
  {
    hobbyId: "gardening",
    name: "Hand tool set (trowel, fork, pruner)",
    description: "Stainless steel tools that won't rust. Comfortable grips for long sessions.",
    cost: 35,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=garden+hand+tool+set+stainless&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "gardening",
    name: "Seed starter kit",
    description: "Propagation tray with dome lid and soil pellets. Grow 50+ seedlings.",
    cost: 18,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=seed+starter+kit+propagation&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "gardening",
    name: "Potting soil (20L)",
    description: "All-purpose organic potting mix for containers and raised beds.",
    cost: 10,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=organic+potting+soil+20L&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "gardening",
    name: "Gardening gloves",
    description: "Breathable with reinforced fingertips. Protects against thorns and soil.",
    cost: 12,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=gardening+gloves+thorn+proof&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Stargazing ---
  {
    hobbyId: "stargazing",
    name: "Planisphere star chart",
    description: "Rotating disc shows tonight's visible constellations for your latitude.",
    cost: 15,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1532968961962-8a0cb3a2d4f0?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=planisphere+star+chart+europe&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "stargazing",
    name: "Red LED headlamp",
    description: "Red light preserves night vision while letting you read charts.",
    cost: 20,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=red+LED+headlamp+astronomy&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "stargazing",
    name: "Astronomy binoculars (10x50)",
    description: "Wide aperture gathers more light than the eye. See craters on the Moon.",
    cost: 80,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1502982899975-893c9cf39028?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=astronomy+binoculars+10x50&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Geocaching ---
  {
    hobbyId: "geocaching",
    name: "Geocaching premium membership",
    description: "Unlocks all cache types and advanced filters. First month free.",
    cost: 30,
    isOptional: true,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=geocaching+GPS+handheld&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "geocaching",
    name: "Small pen (nano-sized)",
    description: "Many caches only fit a tiny log sheet. Carry a pen that fits.",
    cost: 5,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=mini+pen+geocaching&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "geocaching",
    name: "Small trade items",
    description: "Keychains, pins, or small toys to swap in cache containers.",
    cost: 10,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=geocaching+trade+items+swag&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Trail Running ---
  {
    hobbyId: "trail-running",
    name: "Trail running shoes",
    description: "Aggressive grip and rock plate for roots and stones. Not road shoes.",
    cost: 140,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=trail+running+shoes+men&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "trail-running",
    name: "Hydration vest",
    description: "Lightweight vest with soft flasks. Carries water without bouncing.",
    cost: 80,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=trail+running+hydration+vest&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "trail-running",
    name: "Running gaiters",
    description: "Keep stones, mud, and debris out of your shoes on technical trails.",
    cost: 25,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1452626038306-9aae5e071dd3?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=trail+running+gaiters&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Rock Climbing ---
  {
    hobbyId: "rock-climbing",
    name: "Climbing shoes",
    description: "Snug-fitting shoes with sticky rubber. The most important climbing gear.",
    cost: 90,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=climbing+shoes+beginner&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "rock-climbing",
    name: "Chalk bag and chalk",
    description: "Keeps hands dry for better grip. Essential for any climbing session.",
    cost: 25,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1564769662533-4f00a87b4056?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=climbing+chalk+bag&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "rock-climbing",
    name: "Climbing harness",
    description: "For top-rope and lead climbing. Adjustable, padded, and certified.",
    cost: 60,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=climbing+harness+beginner&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "rock-climbing",
    name: "Belay device",
    description: "Assisted braking device for safe rope management. Take a belay course first.",
    cost: 35,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=belay+device+assisted+braking&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Surfing ---
  {
    hobbyId: "surfing",
    name: "Foam surfboard (8ft)",
    description: "Soft-top longboard. Stable, forgiving, and safe to learn on.",
    cost: 200,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1502680390548-bdbac40cef78?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=foam+surfboard+8ft+beginner&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "surfing",
    name: "Wetsuit (3/2mm)",
    description: "Full-body neoprene suit for Atlantic surf temperatures.",
    cost: 120,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1502680390548-bdbac40cef78?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=wetsuit+3+2mm+surfing&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "surfing",
    name: "Surf wax",
    description: "Apply to board deck for grip. Match wax type to water temperature.",
    cost: 8,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1502680390548-bdbac40cef78?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=surf+wax+cold+water&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "surfing",
    name: "Leash (8ft)",
    description: "Tethers board to your ankle. Prevents losing your board in waves.",
    cost: 20,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1502680390548-bdbac40cef78?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=surfboard+leash+8ft&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Camping ---
  {
    hobbyId: "camping",
    name: "2-person tent",
    description: "Freestanding dome tent. Easy setup, waterproof, and packs small.",
    cost: 150,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=2+person+tent+waterproof&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "camping",
    name: "Sleeping bag (3-season)",
    description: "Comfort-rated to 0°C. Synthetic fill dries faster than down.",
    cost: 80,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sleeping+bag+3+season+0+degrees&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "camping",
    name: "Sleeping pad",
    description: "Insulated inflatable pad. R-value 3+ for ground insulation.",
    cost: 50,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=camping+sleeping+pad+insulated&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "camping",
    name: "Headlamp",
    description: "Rechargeable, red-light mode for camp use. 200+ lumens.",
    cost: 30,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12f032f55?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=rechargeable+headlamp+camping&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "camping",
    name: "Camping stove + gas",
    description: "Compact screw-on canister stove. Boils water in 3 minutes.",
    cost: 40,
    isOptional: true,
    sortOrder: 4,
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=camping+stove+canister+compact&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Fishing ---
  {
    hobbyId: "fishing",
    name: "Spinning rod and reel combo",
    description: "Versatile setup for lake and river fishing. Medium action, 2m length.",
    cost: 80,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1532015421997-7bf740e0dcca?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=spinning+rod+reel+combo+beginner&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "fishing",
    name: "Tackle box with basics",
    description: "Hooks, floats, weights, swivels, and a few spinners to get started.",
    cost: 30,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1532015421997-7bf740e0dcca?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fishing+tackle+box+starter+set&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "fishing",
    name: "SaNa fishing licence course",
    description: "Mandatory Swiss fishing certification. Online course + exam.",
    cost: 50,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1532015421997-7bf740e0dcca?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fishing+licence+switzerland&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "fishing",
    name: "Landing net",
    description: "Rubber-mesh net for safely landing and releasing fish.",
    cost: 25,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1532015421997-7bf740e0dcca?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=fishing+landing+net+rubber&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Mountain Biking ---
  {
    hobbyId: "mountain-biking",
    name: "Mountain bike (hardtail)",
    description: "Entry-level hardtail with disc brakes. Rent first, buy when committed.",
    cost: 800,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=hardtail+mountain+bike&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "mountain-biking",
    name: "MTB helmet",
    description: "Full-coverage trail helmet with MIPS protection. Non-negotiable.",
    cost: 80,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=mountain+bike+helmet+MIPS&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "mountain-biking",
    name: "Gloves and knee pads",
    description: "Padded gloves for grip. Knee pads for confidence on descents.",
    cost: 60,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=mountain+bike+gloves+knee+pads&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "mountain-biking",
    name: "Repair kit (multi-tool, tube, pump)",
    description: "Trailside essentials. A flat tyre shouldn't end your ride.",
    cost: 35,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=mountain+bike+repair+kit&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Foraging ---
  {
    hobbyId: "foraging",
    name: "Foraging field guide",
    description: "Illustrated guide to edible wild plants in Central Europe. Photo ID essential.",
    cost: 25,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=foraging+field+guide+europe&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "foraging",
    name: "Wicker basket",
    description: "Traditional open basket allows spores to spread as you walk. Better than bags.",
    cost: 20,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=foraging+wicker+basket&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "foraging",
    name: "Folding knife",
    description: "Small, sharp blade for cleanly cutting mushrooms and herbs at the base.",
    cost: 20,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1504387828636-abeb50778c0c?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=foraging+folding+knife&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Nature Photography ---
  {
    hobbyId: "nature-photography",
    name: "Camera or smartphone with manual mode",
    description: "Start with your phone. Upgrade when you understand exposure and composition.",
    cost: 0,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=mirrorless+camera+beginner&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "nature-photography",
    name: "Compact tripod",
    description: "Stabilises shots in low light. Essential for sunrise and macro work.",
    cost: 45,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=compact+travel+tripod+camera&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "nature-photography",
    name: "Telephoto lens (70-300mm)",
    description: "For wildlife and birds. Makes distant subjects fill the frame.",
    cost: 250,
    isOptional: true,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=telephoto+lens+70-300mm&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Sailing ---
  {
    hobbyId: "sailing",
    name: "Sailing course (D-Schein)",
    description: "Swiss inland sailing licence course. Theory + practical over 5-10 days.",
    cost: 500,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1500930287596-c1ecaa210571?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sailing+theory+book&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "sailing",
    name: "Sailing gloves",
    description: "Fingerless gloves protect palms from rope burn during sheet handling.",
    cost: 30,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1500930287596-c1ecaa210571?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sailing+gloves+fingerless&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "sailing",
    name: "Non-slip deck shoes",
    description: "White-soled shoes that grip wet surfaces without marking the deck.",
    cost: 70,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1500930287596-c1ecaa210571?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sailing+deck+shoes&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "sailing",
    name: "Waterproof jacket",
    description: "Lightweight, breathable, and fully waterproof for spray and rain.",
    cost: 120,
    isOptional: true,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1500930287596-c1ecaa210571?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sailing+waterproof+jacket&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Skiing ---
  {
    hobbyId: "skiing",
    name: "Ski rental package (skis, boots, poles)",
    description: "Always rent your first season. Shops fit boots properly and match ski length.",
    cost: 45,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=ski+equipment+beginner&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "skiing",
    name: "Ski helmet",
    description: "MIPS-certified helmet. Mandatory for safety, often required at Swiss resorts.",
    cost: 80,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=ski+helmet+MIPS&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "skiing",
    name: "Ski goggles",
    description: "Anti-fog lenses with UV protection. Variable-tint for changing light.",
    cost: 60,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=ski+goggles+anti+fog&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "skiing",
    name: "Base layer set",
    description: "Merino wool top and bottom. Warm when wet, no odour after all-day wear.",
    cost: 70,
    isOptional: false,
    sortOrder: 3,
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=merino+base+layer+skiing&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Horseback Riding ---
  {
    hobbyId: "horseback-riding",
    name: "Riding lessons (intro package)",
    description: "Block of 5 group lessons at a local riding school. Includes horse and tack.",
    cost: 250,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=horse+riding+equipment+beginner&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "horseback-riding",
    name: "Riding helmet",
    description: "Certified equestrian helmet. Most schools require your own after first lessons.",
    cost: 60,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=horse+riding+helmet+certified&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "horseback-riding",
    name: "Riding boots (short + chaps)",
    description: "Heeled boots prevent foot slipping through stirrup. Chaps protect calves.",
    cost: 80,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=horse+riding+boots+chaps&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },

  // --- Beach Volleyball ---
  {
    hobbyId: "beach-volleyball",
    name: "Beach volleyball",
    description: "Official size and weight. Softer than indoor balls for bare-hand play.",
    cost: 30,
    isOptional: false,
    sortOrder: 0,
    imageUrl: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=beach+volleyball+official+size&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "beach-volleyball",
    name: "Sports sunglasses",
    description: "Polarised lenses with secure fit. You'll be looking up into the sun constantly.",
    cost: 30,
    isOptional: false,
    sortOrder: 1,
    imageUrl: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sports+sunglasses+polarised+volleyball&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
  {
    hobbyId: "beach-volleyball",
    name: "Sunscreen SPF 50",
    description: "Sport-grade, sweat-resistant. Reapply every 2 hours on sand.",
    cost: 15,
    isOptional: false,
    sortOrder: 2,
    imageUrl: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400&q=80",
    affiliateUrl: "https://www.amazon.de/s?k=sport+sunscreen+SPF+50&tag=trysomething-21",
    affiliateSource: "amazon_de",
  },
];

// =============================================================================
// Roadmap Steps — 5 per hobby
// =============================================================================

export const outdoorsRoadmapSteps = [
  // --- Hiking ---
  { id: "hiking-1", hobbyId: "hiking", title: "Find a local trail", description: "Use AllTrails or SchweizMobil. Pick something rated easy, under 2 hours.", estimatedMinutes: 15, milestone: null, sortOrder: 0 },
  { id: "hiking-2", hobbyId: "hiking", title: "Gear up basics", description: "Good shoes, water bottle, daypack. No need to buy everything — just the essentials.", estimatedMinutes: 60, milestone: null, sortOrder: 1 },
  { id: "hiking-3", hobbyId: "hiking", title: "Complete your first hike", description: "Go! Start early, pace yourself, take photos at the top. Celebrate the accomplishment.", estimatedMinutes: 180, milestone: "First summit", sortOrder: 2 },
  { id: "hiking-4", hobbyId: "hiking", title: "Try a longer or steeper trail", description: "Increase distance or elevation. Pack lunch and make a day of it.", estimatedMinutes: 300, milestone: null, sortOrder: 3 },
  { id: "hiking-5", hobbyId: "hiking", title: "Join a group hike or tackle an iconic route", description: "Try a SAC (Swiss Alpine Club) outing or a classic like the Panoramaweg.", estimatedMinutes: 360, milestone: "Trail veteran", sortOrder: 4 },

  // --- Birdwatching ---
  { id: "birdwatching-1", hobbyId: "birdwatching", title: "Learn 10 common local birds", description: "Start with the obvious ones: robin, blackbird, great tit, chaffinch. Use the Merlin app.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "birdwatching-2", hobbyId: "birdwatching", title: "Get binoculars and practise focusing", description: "Set up at a park bench or window feeder. Practise tracking moving birds.", estimatedMinutes: 45, milestone: null, sortOrder: 1 },
  { id: "birdwatching-3", hobbyId: "birdwatching", title: "Visit a local birding hotspot", description: "Reservoirs, wetlands, and river deltas attract diverse species. Check eBird for nearby hotspots.", estimatedMinutes: 120, milestone: "First rare sighting", sortOrder: 2 },
  { id: "birdwatching-4", hobbyId: "birdwatching", title: "Start a life list", description: "Log every species you identify. Use eBird or a notebook. Track date, location, and behaviour.", estimatedMinutes: 20, milestone: null, sortOrder: 3 },
  { id: "birdwatching-5", hobbyId: "birdwatching", title: "Learn birdsong identification", description: "Most birds are heard before seen. Use BirdNET app to record and identify calls.", estimatedMinutes: 60, milestone: "50 species logged", sortOrder: 4 },

  // --- Kayaking ---
  { id: "kayaking-1", hobbyId: "kayaking", title: "Book a beginner lesson or rental", description: "Most Swiss lakeside towns have rental shops. Book a 1-hour intro session.", estimatedMinutes: 15, milestone: null, sortOrder: 0 },
  { id: "kayaking-2", hobbyId: "kayaking", title: "Learn basic paddle strokes", description: "Forward stroke, sweep turn, reverse. Keep a low centre of gravity.", estimatedMinutes: 60, milestone: null, sortOrder: 1 },
  { id: "kayaking-3", hobbyId: "kayaking", title: "Complete a 1-hour flatwater paddle", description: "Paddle along the shoreline. Stay within swimming distance of shore.", estimatedMinutes: 60, milestone: "First lake crossing", sortOrder: 2 },
  { id: "kayaking-4", hobbyId: "kayaking", title: "Extend to a half-day trip", description: "Pack lunch, explore a new section of lake. Practise navigation and reading the wind.", estimatedMinutes: 180, milestone: null, sortOrder: 3 },
  { id: "kayaking-5", hobbyId: "kayaking", title: "Try a river or multi-day trip", description: "Graduate to gentle river sections or plan an overnight lakeside camp by kayak.", estimatedMinutes: 300, milestone: "River paddler", sortOrder: 4 },

  // --- Gardening ---
  { id: "gardening-1", hobbyId: "gardening", title: "Choose your growing space", description: "Window box, balcony pots, or garden bed. Assess sunlight hours — most herbs need 6+.", estimatedMinutes: 20, milestone: null, sortOrder: 0 },
  { id: "gardening-2", hobbyId: "gardening", title: "Plant 3 easy herbs", description: "Basil, parsley, and chives. Use quality potting soil and water consistently.", estimatedMinutes: 30, milestone: null, sortOrder: 1 },
  { id: "gardening-3", hobbyId: "gardening", title: "Harvest and use your first herbs", description: "Snip fresh basil onto pasta. This moment hooks most people for life.", estimatedMinutes: 15, milestone: "First harvest", sortOrder: 2 },
  { id: "gardening-4", hobbyId: "gardening", title: "Expand to vegetables", description: "Try tomatoes, lettuce, or radishes. Learn about feeding, watering schedules, and pests.", estimatedMinutes: 60, milestone: null, sortOrder: 3 },
  { id: "gardening-5", hobbyId: "gardening", title: "Plan a seasonal garden calendar", description: "Map out what to sow each month. Start seeds indoors in spring, succession plant for continuous harvest.", estimatedMinutes: 45, milestone: "Season planner", sortOrder: 4 },

  // --- Stargazing ---
  { id: "stargazing-1", hobbyId: "stargazing", title: "Download a star chart app", description: "Stellarium or SkySafari. Point your phone at the sky and learn what's up tonight.", estimatedMinutes: 10, milestone: null, sortOrder: 0 },
  { id: "stargazing-2", hobbyId: "stargazing", title: "Learn 5 major constellations", description: "Orion, Ursa Major, Cassiopeia, Scorpius, Leo. These are your anchor points.", estimatedMinutes: 30, milestone: null, sortOrder: 1 },
  { id: "stargazing-3", hobbyId: "stargazing", title: "Find a dark sky site and observe", description: "Drive 30 min from city lights. Give your eyes 20 minutes to adapt. The Milky Way will appear.", estimatedMinutes: 120, milestone: "First Milky Way sighting", sortOrder: 2 },
  { id: "stargazing-4", hobbyId: "stargazing", title: "Observe the Moon and planets", description: "With binoculars, see lunar craters and Jupiter's moons. Track planet positions monthly.", estimatedMinutes: 60, milestone: null, sortOrder: 3 },
  { id: "stargazing-5", hobbyId: "stargazing", title: "Catch a meteor shower or eclipse", description: "Perseids (Aug), Geminids (Dec) are the best. Set an alarm, bring a blanket, lie back.", estimatedMinutes: 120, milestone: "Meteor shower watched", sortOrder: 4 },

  // --- Geocaching ---
  { id: "geocaching-1", hobbyId: "geocaching", title: "Create a free account and find your first cache", description: "Download the Geocaching app. Filter by difficulty 1/1. Your first find is nearby — guaranteed.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "geocaching-2", hobbyId: "geocaching", title: "Find 5 different cache types", description: "Traditional, multi, mystery, letterbox, EarthCache. Each type has different rules and fun.", estimatedMinutes: 120, milestone: null, sortOrder: 1 },
  { id: "geocaching-3", hobbyId: "geocaching", title: "Complete a trail or power run", description: "Many areas have themed trails with 10+ caches along a route. Great for a half-day adventure.", estimatedMinutes: 180, milestone: "Trail completed", sortOrder: 2 },
  { id: "geocaching-4", hobbyId: "geocaching", title: "Hide your own cache", description: "Choose a meaningful location, get a waterproof container, submit for review. Give back to the community.", estimatedMinutes: 60, milestone: null, sortOrder: 3 },
  { id: "geocaching-5", hobbyId: "geocaching", title: "Attend a geocaching event", description: "Meet local cachers at an official event. Trade trackables and learn tips from veterans.", estimatedMinutes: 120, milestone: "Community cacher", sortOrder: 4 },

  // --- Trail Running ---
  { id: "trail-running-1", hobbyId: "trail-running", title: "Get proper trail shoes", description: "Visit a running shop. Trail shoes need grip and a rock plate — road shoes won't cut it.", estimatedMinutes: 45, milestone: null, sortOrder: 0 },
  { id: "trail-running-2", hobbyId: "trail-running", title: "Run your first easy trail (3-5km)", description: "Pick a flat forest path. Walk the uphills, jog the flats. No pace pressure.", estimatedMinutes: 40, milestone: null, sortOrder: 1 },
  { id: "trail-running-3", hobbyId: "trail-running", title: "Add elevation — run a hilly loop", description: "Find a trail with 200m+ elevation gain. Hike up, run down. Feel the difference from road running.", estimatedMinutes: 60, milestone: "First summit run", sortOrder: 2 },
  { id: "trail-running-4", hobbyId: "trail-running", title: "Build to 10km on trails", description: "Increase distance by 10% per week. Carry water and a snack for anything over 1 hour.", estimatedMinutes: 75, milestone: null, sortOrder: 3 },
  { id: "trail-running-5", hobbyId: "trail-running", title: "Enter a local trail race", description: "Sign up for a 10-15km trail race. The atmosphere and aid stations make it special.", estimatedMinutes: 90, milestone: "First trail race", sortOrder: 4 },

  // --- Rock Climbing ---
  { id: "rock-climbing-1", hobbyId: "rock-climbing", title: "Visit an indoor climbing gym", description: "Rent shoes, try bouldering. Most gyms offer free intro sessions. No partner needed.", estimatedMinutes: 90, milestone: null, sortOrder: 0 },
  { id: "rock-climbing-2", hobbyId: "rock-climbing", title: "Take a beginner course", description: "Learn footwork, body positioning, and basic safety. Indoor courses run 2-3 hours.", estimatedMinutes: 150, milestone: null, sortOrder: 1 },
  { id: "rock-climbing-3", hobbyId: "rock-climbing", title: "Send your first V2 boulder or 5b route", description: "Consistent practice pays off. When you top out a problem that stumped you, it feels incredible.", estimatedMinutes: 90, milestone: "First project sent", sortOrder: 2 },
  { id: "rock-climbing-4", hobbyId: "rock-climbing", title: "Learn to belay and try top-rope", description: "Take a belay course. Climbing higher walls with a rope opens up a whole new dimension.", estimatedMinutes: 120, milestone: null, sortOrder: 3 },
  { id: "rock-climbing-5", hobbyId: "rock-climbing", title: "Climb outdoors for the first time", description: "Join an experienced climber or guided group. Real rock feels completely different from plastic.", estimatedMinutes: 240, milestone: "Outdoor climber", sortOrder: 4 },

  // --- Surfing ---
  { id: "surfing-1", hobbyId: "surfing", title: "Book a surf lesson", description: "2-hour group lesson on a beach break. They provide board and wetsuit. Just show up.", estimatedMinutes: 120, milestone: null, sortOrder: 0 },
  { id: "surfing-2", hobbyId: "surfing", title: "Practise the pop-up on land", description: "Lie flat, hands by chest, jump to feet in one motion. Drill it 20 times a day.", estimatedMinutes: 15, milestone: null, sortOrder: 1 },
  { id: "surfing-3", hobbyId: "surfing", title: "Catch your first green wave", description: "Move beyond whitewater. Paddle into an unbroken wave and stand up. Pure magic.", estimatedMinutes: 120, milestone: "First green wave", sortOrder: 2 },
  { id: "surfing-4", hobbyId: "surfing", title: "Learn to read surf forecasts", description: "Understand swell direction, period, wind, and tide. Magicseaweed and Surfline are your tools.", estimatedMinutes: 30, milestone: null, sortOrder: 3 },
  { id: "surfing-5", hobbyId: "surfing", title: "Surf consistently and try a new break", description: "Aim for 2 sessions/week. Travel to a different beach and adapt to new conditions.", estimatedMinutes: 120, milestone: "Wave rider", sortOrder: 4 },

  // --- Camping ---
  { id: "camping-1", hobbyId: "camping", title: "Practise tent setup at home", description: "Set up in your living room or garden. Learn it before dark and rain add pressure.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "camping-2", hobbyId: "camping", title: "Pack your gear and make a checklist", description: "Tent, sleeping bag, pad, headlamp, stove, food, water, first aid. Less is more.", estimatedMinutes: 30, milestone: null, sortOrder: 1 },
  { id: "camping-3", hobbyId: "camping", title: "Spend your first night outdoors", description: "Book a campsite with facilities. Cook dinner on your stove, sleep under stars.", estimatedMinutes: 720, milestone: "First night out", sortOrder: 2 },
  { id: "camping-4", hobbyId: "camping", title: "Camp somewhere without facilities", description: "Wild camping (where legal) or a basic site. Practise leave-no-trace principles.", estimatedMinutes: 720, milestone: null, sortOrder: 3 },
  { id: "camping-5", hobbyId: "camping", title: "Plan a multi-day camping trip", description: "2-3 nights in a row. Hike between camps or explore a new region entirely by tent.", estimatedMinutes: 2880, milestone: "Wilderness camper", sortOrder: 4 },

  // --- Fishing ---
  { id: "fishing-1", hobbyId: "fishing", title: "Get your SaNa fishing licence", description: "Complete the Swiss fishing certification course online. Required before you can fish legally.", estimatedMinutes: 480, milestone: null, sortOrder: 0 },
  { id: "fishing-2", hobbyId: "fishing", title: "Set up your first rod", description: "Spinning rod, reel, line, float, hook, bait. Watch a YouTube tutorial for your specific setup.", estimatedMinutes: 30, milestone: null, sortOrder: 1 },
  { id: "fishing-3", hobbyId: "fishing", title: "Catch your first fish", description: "Head to a stocked lake or calm river. Use worms or corn for bait. Patience is the skill.", estimatedMinutes: 180, milestone: "First catch", sortOrder: 2 },
  { id: "fishing-4", hobbyId: "fishing", title: "Learn a new technique", description: "Try lure fishing, fly fishing, or bottom fishing. Each method targets different species.", estimatedMinutes: 120, milestone: null, sortOrder: 3 },
  { id: "fishing-5", hobbyId: "fishing", title: "Cook your catch", description: "Clean, fillet, and cook a fish you caught yourself. Pan-fried trout with butter and lemon.", estimatedMinutes: 60, milestone: "Catch and cook", sortOrder: 4 },

  // --- Mountain Biking ---
  { id: "mountain-biking-1", hobbyId: "mountain-biking", title: "Rent a mountain bike for a day", description: "Visit a bike park or rental shop. Try a hardtail on easy trails before buying.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "mountain-biking-2", hobbyId: "mountain-biking", title: "Learn basic bike handling", description: "Braking, cornering, body position. Practise on a flat gravel path before hitting trails.", estimatedMinutes: 60, milestone: null, sortOrder: 1 },
  { id: "mountain-biking-3", hobbyId: "mountain-biking", title: "Ride your first singletrack trail", description: "Blue-graded flow trail. Stay loose, look ahead, and let the bike do the work.", estimatedMinutes: 90, milestone: "First singletrack", sortOrder: 2 },
  { id: "mountain-biking-4", hobbyId: "mountain-biking", title: "Learn trail maintenance and etiquette", description: "Yield to hikers, don't skid on corners, close gates. Join a trail-building day.", estimatedMinutes: 120, milestone: null, sortOrder: 3 },
  { id: "mountain-biking-5", hobbyId: "mountain-biking", title: "Ride a challenging red trail", description: "Steeper, rockier, with drops and roots. Progress naturally — don't skip grades.", estimatedMinutes: 120, milestone: "Red trail rider", sortOrder: 4 },

  // --- Foraging ---
  { id: "foraging-1", hobbyId: "foraging", title: "Join a guided foraging walk", description: "Local nature centres and mushroom clubs offer seasonal walks. Learn safely from an expert.", estimatedMinutes: 150, milestone: null, sortOrder: 0 },
  { id: "foraging-2", hobbyId: "foraging", title: "Learn 5 unmistakable edible species", description: "Wild garlic, elderflower, blackberry, chanterelle, sweet chestnut. Zero lookalike confusion.", estimatedMinutes: 60, milestone: null, sortOrder: 1 },
  { id: "foraging-3", hobbyId: "foraging", title: "Forage and cook your first wild meal", description: "Wild garlic pesto or chanterelle risotto. The taste of something you found yourself is unbeatable.", estimatedMinutes: 120, milestone: "First wild meal", sortOrder: 2 },
  { id: "foraging-4", hobbyId: "foraging", title: "Learn to preserve wild foods", description: "Dry mushrooms, make elderflower cordial, pickle wild garlic buds. Extend the season.", estimatedMinutes: 90, milestone: null, sortOrder: 3 },
  { id: "foraging-5", hobbyId: "foraging", title: "Forage across all four seasons", description: "Spring greens, summer berries, autumn mushrooms, winter roots. Each season offers different treasures.", estimatedMinutes: 180, milestone: "Four-season forager", sortOrder: 4 },

  // --- Nature Photography ---
  { id: "nature-photography-1", hobbyId: "nature-photography", title: "Learn the rule of thirds", description: "Divide your frame into a 3x3 grid. Place subjects on the intersections. Instantly better photos.", estimatedMinutes: 20, milestone: null, sortOrder: 0 },
  { id: "nature-photography-2", hobbyId: "nature-photography", title: "Shoot during golden hour", description: "Go out at sunrise or sunset. The warm, low light transforms ordinary scenes into extraordinary ones.", estimatedMinutes: 60, milestone: null, sortOrder: 1 },
  { id: "nature-photography-3", hobbyId: "nature-photography", title: "Take 100 photos in one outing", description: "Quantity leads to quality. Try different angles, distances, and subjects. Review and pick your best 5.", estimatedMinutes: 120, milestone: "First portfolio pick", sortOrder: 2 },
  { id: "nature-photography-4", hobbyId: "nature-photography", title: "Learn basic editing", description: "Lightroom Mobile or Snapseed. Adjust exposure, contrast, and colour. Subtle edits improve every shot.", estimatedMinutes: 60, milestone: null, sortOrder: 3 },
  { id: "nature-photography-5", hobbyId: "nature-photography", title: "Specialise in a niche", description: "Macro insects, bird portraits, landscapes, or astrophotography. Deep focus accelerates growth.", estimatedMinutes: 120, milestone: "Found your niche", sortOrder: 4 },

  // --- Sailing ---
  { id: "sailing-1", hobbyId: "sailing", title: "Take an introductory sailing lesson", description: "Most Swiss sailing schools offer taster sessions on the lake. Feel the wind and learn the basics.", estimatedMinutes: 120, milestone: null, sortOrder: 0 },
  { id: "sailing-2", hobbyId: "sailing", title: "Learn the points of sail", description: "Understand close-hauled, beam reach, broad reach, and running. This is the core theory.", estimatedMinutes: 60, milestone: null, sortOrder: 1 },
  { id: "sailing-3", hobbyId: "sailing", title: "Complete your first solo tack and gybe", description: "Change direction through the wind confidently. This is when sailing starts to click.", estimatedMinutes: 90, milestone: "First tack", sortOrder: 2 },
  { id: "sailing-4", hobbyId: "sailing", title: "Enrol in a D-Schein course", description: "Swiss inland sailing licence. 5-10 days of theory and practice. Opens access to boat rentals.", estimatedMinutes: 2400, milestone: null, sortOrder: 3 },
  { id: "sailing-5", hobbyId: "sailing", title: "Rent a boat and sail independently", description: "With your licence in hand, rent a dinghy or keelboat. Plan a day sail across the lake.", estimatedMinutes: 240, milestone: "Licensed sailor", sortOrder: 4 },

  // --- Skiing ---
  { id: "skiing-1", hobbyId: "skiing", title: "Book a beginner group lesson", description: "Swiss ski schools (ESS) offer half-day group lessons. Equipment rental included at most resorts.", estimatedMinutes: 180, milestone: null, sortOrder: 0 },
  { id: "skiing-2", hobbyId: "skiing", title: "Learn the snowplough and basic stopping", description: "Pizza/wedge position to control speed. Master this before anything else.", estimatedMinutes: 180, milestone: null, sortOrder: 1 },
  { id: "skiing-3", hobbyId: "skiing", title: "Ski your first blue run top to bottom", description: "Link snowplough turns and control your speed all the way down. Huge milestone.", estimatedMinutes: 180, milestone: "First blue run", sortOrder: 2 },
  { id: "skiing-4", hobbyId: "skiing", title: "Progress to parallel turns", description: "Bring your skis parallel instead of wedge. This is where skiing gets fast and fluid.", estimatedMinutes: 360, milestone: null, sortOrder: 3 },
  { id: "skiing-5", hobbyId: "skiing", title: "Tackle your first red run", description: "Steeper terrain, more speed, tighter turns. Ski with friends who push your comfort zone.", estimatedMinutes: 360, milestone: "Red run skier", sortOrder: 4 },

  // --- Horseback Riding ---
  { id: "horseback-riding-1", hobbyId: "horseback-riding", title: "Book an intro lesson at a riding school", description: "Group lessons include horse, tack, and instruction. Wear long trousers and closed shoes.", estimatedMinutes: 60, milestone: null, sortOrder: 0 },
  { id: "horseback-riding-2", hobbyId: "horseback-riding", title: "Learn to mount, walk, and halt", description: "Correct mounting, balanced seated position, and stopping. The fundamentals of communication.", estimatedMinutes: 60, milestone: null, sortOrder: 1 },
  { id: "horseback-riding-3", hobbyId: "horseback-riding", title: "Trot for the first time", description: "Rising trot (posting) takes timing. Once you find the rhythm, riding transforms.", estimatedMinutes: 60, milestone: "First trot", sortOrder: 2 },
  { id: "horseback-riding-4", hobbyId: "horseback-riding", title: "Learn to groom and tack up", description: "Understanding the horse before and after riding deepens the bond. Learn to clean hooves and fit a saddle.", estimatedMinutes: 45, milestone: null, sortOrder: 3 },
  { id: "horseback-riding-5", hobbyId: "horseback-riding", title: "Go on a trail ride", description: "Leave the arena and ride through countryside. The relationship with the horse truly develops on the trail.", estimatedMinutes: 120, milestone: "Trail rider", sortOrder: 4 },

  // --- Beach Volleyball ---
  { id: "beach-volleyball-1", hobbyId: "beach-volleyball", title: "Learn the basic bump pass", description: "Forearms together, platform flat, let the ball bounce off your arms. The foundation of every rally.", estimatedMinutes: 30, milestone: null, sortOrder: 0 },
  { id: "beach-volleyball-2", hobbyId: "beach-volleyball", title: "Practise setting and serving", description: "Overhead set for accuracy, underhand serve for consistency. Practise with a partner against a wall.", estimatedMinutes: 45, milestone: null, sortOrder: 1 },
  { id: "beach-volleyball-3", hobbyId: "beach-volleyball", title: "Play your first 2v2 game", description: "Find a sand court, grab a partner, challenge anyone. The first rally that goes back and forth is addicting.", estimatedMinutes: 60, milestone: "First match", sortOrder: 2 },
  { id: "beach-volleyball-4", hobbyId: "beach-volleyball", title: "Learn court positioning and communication", description: "Call 'mine' early, cover your half, rotate after serves. Communication wins games.", estimatedMinutes: 60, milestone: null, sortOrder: 3 },
  { id: "beach-volleyball-5", hobbyId: "beach-volleyball", title: "Join a local open play night or tournament", description: "City beach bars run weekly games. Show up solo and get placed on a team. Best way to improve.", estimatedMinutes: 120, milestone: "Tournament player", sortOrder: 4 },
];

// =============================================================================
// FAQ Items — 2-3 per hobby (first 8 hobbies + selected others)
// =============================================================================

export const outdoorsFaqItems = [
  // Hiking
  { hobbyId: "hiking", question: "How long should my first hike be?", answer: "Start with 1-2 hours on relatively flat terrain. Most people can handle 5-8km at a casual pace. Add elevation gradually after a few easy hikes.", upvotes: 47 },
  { hobbyId: "hiking", question: "Do I need expensive hiking boots?", answer: "Not at first. Trail running shoes or sturdy sneakers with good grip work for easy trails. Invest in proper boots when you tackle rocky or alpine terrain.", upvotes: 52 },
  { hobbyId: "hiking", question: "What should I carry in my daypack?", answer: "Water (1L minimum), snacks, phone, rain layer, sunscreen, first aid basics, and a paper map or downloaded offline map. Keep it under 5kg for day hikes.", upvotes: 38 },

  // Birdwatching
  { hobbyId: "birdwatching", question: "Do I need binoculars to start?", answer: "Not immediately — you can learn garden birds with your eyes and a phone app like Merlin. But binoculars dramatically improve the experience. Budget CHF 100-200 for a solid pair.", upvotes: 41 },
  { hobbyId: "birdwatching", question: "What's the best time of day for birding?", answer: "Early morning, within 2 hours of sunrise. Birds are most active and vocal then. Dawn chorus in spring is unforgettable.", upvotes: 35 },

  // Kayaking
  { hobbyId: "kayaking", question: "Should I buy a kayak right away?", answer: "Absolutely not. Rent for your first 5-10 sessions to learn what type you prefer — sit-on-top, sit-in, inflatable. Then buy used if you're committed.", upvotes: 55 },
  { hobbyId: "kayaking", question: "Is kayaking safe if I'm not a strong swimmer?", answer: "Always wear a life jacket, stay near shore, and go with a buddy. Consider a swimming course alongside kayaking — both skills reinforce each other.", upvotes: 43 },

  // Gardening
  { hobbyId: "gardening", question: "Can I garden on a small balcony?", answer: "Absolutely. Herbs, cherry tomatoes, chillies, and salad greens all thrive in pots with 6+ hours of sunlight. Vertical planters maximize small spaces.", upvotes: 61 },
  { hobbyId: "gardening", question: "When should I start planting in Switzerland?", answer: "After the Eisheiligen (Ice Saints) in mid-May for outdoor warm-season crops. Start seeds indoors from March. Hardy greens and herbs can go out in April.", upvotes: 44 },
  { hobbyId: "gardening", question: "How often should I water my plants?", answer: "Stick your finger 2cm into the soil. If it's dry, water. If it's damp, wait. Overwatering is the number one beginner mistake — most plants prefer slightly dry to soaking wet.", upvotes: 39 },

  // Stargazing
  { hobbyId: "stargazing", question: "Do I need a telescope to start?", answer: "No. Start with your naked eyes and a star chart app. Binoculars (10x50) are the best next step — they show far more than you'd expect and are easier to use than a telescope.", upvotes: 48 },
  { hobbyId: "stargazing", question: "Where can I find dark skies in Switzerland?", answer: "Head to the Jura mountains, Emmental, or high Alpine passes. Even 30 minutes from a city makes a huge difference. Check lightpollutionmap.info for your area.", upvotes: 36 },

  // Geocaching
  { hobbyId: "geocaching", question: "Is geocaching really free?", answer: "The basic app is free and gives you access to thousands of caches. Premium membership (CHF 30/year) unlocks all cache types and advanced search — worth it after you're hooked.", upvotes: 33 },
  { hobbyId: "geocaching", question: "What do I do when I find a cache?", answer: "Sign the logbook inside with your name and date. If the cache has trade items, you can take one but leave one of equal or greater value. Then log the find in the app.", upvotes: 29 },

  // Trail Running
  { hobbyId: "trail-running", question: "I'm a road runner — is trail running much harder?", answer: "It uses different muscles and is slower per kilometre, but that's expected. Forget your road pace. On trails, effort matters more than speed. Your first runs should feel easy.", upvotes: 42 },
  { hobbyId: "trail-running", question: "Are trail running shoes really different from road shoes?", answer: "Yes. Trail shoes have aggressive grip, a rock plate to protect from stones, and usually more lateral support. Road shoes will slip on mud, rocks, and roots.", upvotes: 37 },

  // Rock Climbing
  { hobbyId: "rock-climbing", question: "Do I need to be strong to start climbing?", answer: "No. Climbing builds the strength you need. Technique and footwork matter far more than arm strength. Many beginners who rely on muscles plateau quickly.", upvotes: 58 },
  { hobbyId: "rock-climbing", question: "Is bouldering or rope climbing better for beginners?", answer: "Bouldering is easier to start — no partner, no gear beyond shoes and chalk. Rope climbing (top-rope) lets you go higher and build endurance. Try both.", upvotes: 45 },

  // Surfing
  { hobbyId: "surfing", question: "Can I learn to surf in Switzerland?", answer: "River surfing exists (Bremgarten, Thun), but most people take surf trips to France, Portugal, or Spain. Biarritz is a 7-hour drive from Bern with perfect beginner waves.", upvotes: 51 },
  { hobbyId: "surfing", question: "How many lessons until I can stand up?", answer: "Most people stand up on whitewater in lesson 1-2. Catching unbroken green waves and riding them takes 5-10 sessions. Consistent practice over a week-long trip is ideal.", upvotes: 40 },

  // Camping
  { hobbyId: "camping", question: "Is wild camping legal in Switzerland?", answer: "It's tolerated above the treeline in most cantons, but technically not a right. Avoid nature reserves, private land, and areas with signs. Always leave no trace.", upvotes: 53 },

  // Fishing
  { hobbyId: "fishing", question: "Do I really need a licence to fish in Switzerland?", answer: "Yes. The SaNa (Sachkundenachweis) is mandatory. It's an online course covering fish species, conservation, and humane handling, followed by an exam. Budget a weekend for it.", upvotes: 46 },

  // Mountain Biking
  { hobbyId: "mountain-biking", question: "Should I get a hardtail or full suspension?", answer: "Hardtail for beginners. It's cheaper, lighter, teaches better technique, and handles 90% of Swiss trails. Full suspension is for aggressive descending and bike parks.", upvotes: 44 },

  // Nature Photography
  { hobbyId: "nature-photography", question: "Is a phone camera good enough for nature photography?", answer: "Modern phones are excellent for landscapes, macro, and close subjects. For wildlife at distance, you'll eventually want a camera with a telephoto lens. But start with your phone — composition matters more than gear.", upvotes: 49 },
];

// =============================================================================
// Cost Breakdowns — one per hobby
// =============================================================================

export const outdoorsCostBreakdowns = [
  {
    hobbyId: "hiking",
    starter: 95,
    threeMonth: 120,
    oneYear: 200,
    tips: ["Borrow trekking poles before buying", "Swiss Alpine Club membership (CHF 80/yr) gives hut discounts", "SchweizMobil app is free and has every official trail"],
  },
  {
    hobbyId: "birdwatching",
    starter: 180,
    threeMonth: 195,
    oneYear: 220,
    tips: ["Don't cheap out on binoculars — CHF 150+ for usable optics", "The Merlin bird ID app is free and incredibly accurate", "Join BirdLife Switzerland for guided walks and newsletters"],
  },
  {
    hobbyId: "kayaking",
    starter: 60,
    threeMonth: 200,
    oneYear: 450,
    tips: ["Rent for your first 10 sessions before buying anything", "Inflatable kayaks store in a closet and cost half the price of rigid", "Many Swiss lakes have free launch points — no marina fees needed"],
  },
  {
    hobbyId: "gardening",
    starter: 50,
    threeMonth: 75,
    oneYear: 120,
    tips: ["Save seeds from your harvest for next year — free plants", "Compost kitchen scraps instead of buying fertiliser", "Swap seedlings with neighbours through local gardening groups"],
  },
  {
    hobbyId: "stargazing",
    starter: 15,
    threeMonth: 35,
    oneYear: 100,
    tips: ["Start with free apps — Stellarium, SkySafari, ISS Detector", "Binoculars are better value than a cheap telescope", "Join a local astronomy club for access to shared telescopes"],
  },
  {
    hobbyId: "geocaching",
    starter: 0,
    threeMonth: 5,
    oneYear: 35,
    tips: ["The free Geocaching app has thousands of caches", "All you need is a phone and a pen", "Premium membership pays for itself if you cache weekly"],
  },
  {
    hobbyId: "trail-running",
    starter: 140,
    threeMonth: 175,
    oneYear: 280,
    tips: ["Shoes are the one non-negotiable investment", "Hydration vest doubles as a lightweight daypack for hikes", "Many trail races have free entry for your first event"],
  },
  {
    hobbyId: "rock-climbing",
    starter: 115,
    threeMonth: 260,
    oneYear: 600,
    tips: ["Buy shoes and chalk; rent harness and rope until committed", "Gym membership (CHF 50-80/month) is cheaper than buying outdoor gear", "Climb with experienced friends to learn fastest"],
  },
  {
    hobbyId: "surfing",
    starter: 50,
    threeMonth: 350,
    oneYear: 600,
    tips: ["Lesson packages (3-5 days) are far cheaper per session than singles", "Buy a used foam board — they're virtually indestructible", "Portugal and France are cheapest for Swiss surfers (budget flights)"],
  },
  {
    hobbyId: "camping",
    starter: 280,
    threeMonth: 310,
    oneYear: 400,
    tips: ["Borrow gear from friends for your first trip", "Decathlon has solid budget tents and sleeping bags", "Swiss campsites average CHF 20-35/night — still cheaper than any hotel"],
  },
  {
    hobbyId: "fishing",
    starter: 160,
    threeMonth: 200,
    oneYear: 350,
    tips: ["SaNa course is mandatory — factor it into startup cost", "Annual fishing permits vary by canton (CHF 30-100)", "Buy a combo rod+reel set rather than separate components"],
  },
  {
    hobbyId: "mountain-biking",
    starter: 150,
    threeMonth: 350,
    oneYear: 1100,
    tips: ["Rent for 3-5 rides before committing to a purchase", "Buy last year's model for 30-40% savings", "Learn basic maintenance (brake pads, tyre pressure) to avoid shop costs"],
  },
  {
    hobbyId: "foraging",
    starter: 45,
    threeMonth: 50,
    oneYear: 65,
    tips: ["A guided walk (CHF 30-50) is the safest way to learn", "Your phone camera is your best ID tool — photograph everything", "Preserved wild foods (dried mushrooms, cordials) make great gifts"],
  },
  {
    hobbyId: "nature-photography",
    starter: 0,
    threeMonth: 45,
    oneYear: 300,
    tips: ["Your phone is a legitimate nature camera — master it first", "Lightroom Mobile's free version handles most editing needs", "Golden hour shoots are free — just set an alarm for sunrise"],
  },
  {
    hobbyId: "sailing",
    starter: 100,
    threeMonth: 600,
    oneYear: 900,
    tips: ["D-Schein course is the biggest upfront cost but unlocks everything", "Crew on other people's boats to gain experience for free", "Sailing club membership includes boat access for CHF 300-600/year"],
  },
  {
    hobbyId: "skiing",
    starter: 175,
    threeMonth: 450,
    oneYear: 800,
    tips: ["Rent equipment your entire first season", "Half-day passes after 12:00 are 30-40% cheaper", "Magic Pass or similar season passes pay for themselves after 5 days"],
  },
  {
    hobbyId: "horseback-riding",
    starter: 250,
    threeMonth: 650,
    oneYear: 2200,
    tips: ["Group lessons are half the price of private ones", "Buy a helmet and boots; the school provides everything else", "Some stables offer work-for-ride arrangements — help muck out in exchange for saddle time"],
  },
  {
    hobbyId: "beach-volleyball",
    starter: 30,
    threeMonth: 50,
    oneYear: 80,
    tips: ["Public sand courts are free in most Swiss cities", "Open play nights at beach bars cost CHF 0-10", "One good ball lasts years — don't buy the cheapest one"],
  },
];
